-- Generated from content/aud-batch-001.csv by scripts/csv-to-seed-sql.mjs — do not edit by hand.
-- Idempotent: skips any question whose stem already exists.
with t as (
  select tp.id, tp.name, s.code from public.topics tp
  join public.subjects s on s.id = tp.subject_id
),
q(subject_code, topic, stem, a, b, c, d, correct_index, explanation, difficulty) as (values
  ('AUD', 'Framework, Standards & Professional Ethics',
   'Which of the following is NOT an element of an assurance engagement under the Philippine Framework for Assurance Engagements?',
   'A three-party relationship involving a practitioner, a responsible party, and intended users', 'A guarantee by the practitioner that the subject matter information is free from error', 'Suitable criteria against which the subject matter is evaluated', 'A written assurance report in a form appropriate to the engagement',
   1, 'Assurance engagements have five elements: a three-party relationship, an appropriate subject matter, suitable criteria, sufficient appropriate evidence, and a written report. The practitioner never guarantees accuracy; only reasonable or limited assurance is provided.', 1),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'A CPA is engaged to review the annual financial statements of a non-listed entity. The CPA''s conclusion will most appropriately be expressed in which manner?',
   'In a negative form, such as ''nothing has come to our attention that causes us to believe the financial statements are materially misstated''', 'As a positive opinion that the financial statements present fairly in all material respects', 'As a summary of factual findings without any conclusion', 'As a certification that the financial statements are accurate',
   0, 'A review provides limited assurance, expressed in a negative form of conclusion. A positive opinion belongs to an audit, factual findings to agreed-upon procedures, and CPAs never certify accuracy.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'A bank engaged a CPA to perform specific procedures on the accounts receivable of a loan applicant and to report the results. Which statement best describes this engagement?',
   'It is a review engagement providing limited assurance to the bank', 'It is an audit restricted to receivables, so a qualified opinion is issued', 'It is a compilation, so the CPA expresses negative assurance', 'It is an agreed-upon procedures engagement; the CPA expresses no assurance and the report on factual findings is restricted to the parties that agreed to the procedures',
   3, 'In an agreed-upon procedures engagement the practitioner performs procedures agreed with the engaging parties and reports factual findings. Users draw their own conclusions, and the report is restricted to those parties.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'In a compilation engagement, the level of assurance provided by the CPA on the financial information is:',
   'Limited assurance', 'Reasonable assurance', 'No assurance', 'Absolute assurance',
   2, 'A compilation involves applying accounting expertise, not assurance skills, to assist management in preparing financial information. No assurance of any kind is expressed.', 1),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'Under RA 9298, the Professional Regulatory Board of Accountancy is composed of:',
   'A chairman and six members', 'A chairman and four members', 'Seven members, one of whom is elected as chairman by the members themselves', 'A chairman and eight members',
   0, 'Section 5 of RA 9298 provides that the Board of Accountancy consists of a chairman and six members appointed by the President of the Philippines.', 1),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'Under RA 9298, members of the Board of Accountancy are appointed by:',
   'The chairman of the Professional Regulation Commission from a list submitted by accredited accounting schools', 'The President of the Philippines from a list of recommendees submitted by the PRC, drawn from nominees of the accredited national professional organization of CPAs', 'The Securities and Exchange Commission upon recommendation of the PICPA national board', 'Direct election by all CPAs in good standing during the annual national convention',
   1, 'RA 9298 requires the accredited professional organization to submit nominees to the PRC, which then submits a list of recommendees to the President of the Philippines, who makes the appointment.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'Under RA 9298 and its IRR, which form of organization is NOT allowed for the practice of public accountancy in the Philippines?',
   'Sole proprietorship', 'General partnership of CPAs', 'A sole practitioner employing CPA staff members', 'A corporation organized for the practice of public accountancy',
   3, 'RA 9298 limits public accountancy practice to sole proprietorships and partnerships of CPAs. The SEC is prohibited from registering any corporation organized for the practice of public accountancy.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'An auditor disclosed confidential client information while testifying in court pursuant to a subpoena issued in a fraud case. Under the Code of Ethics, the auditor:',
   'Did not violate the confidentiality principle because disclosure required by a legal process is a permitted exception', 'Violated the confidentiality principle because client consent was not obtained', 'Violated the confidentiality principle unless the information was already public', 'Should have refused to testify and claimed accountant-client privilege',
   0, 'Confidentiality does not prohibit disclosure when it is required by law, such as producing documents or giving evidence in legal proceedings. Client consent is not needed in that case, and Philippine law grants no general accountant-client privilege in such proceedings.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'A CPA accepted an engagement to audit a bank despite having no experience in the banking industry, and made no effort to obtain training or to engage someone with relevant expertise. Which fundamental principle is most directly violated?',
   'Integrity', 'Objectivity', 'Professional competence and due care', 'Professional behavior',
   2, 'Professional competence and due care requires a CPA to attain and maintain the knowledge and skill needed for the engagement, or to obtain appropriate assistance. Accepting specialized work without competence or support violates this principle.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'During the audit, the engagement team discovered that the firm''s accounting services division had prepared many of the journal entries now subject to audit. Which threat to independence is most directly created?',
   'Advocacy threat', 'Self-review threat', 'Intimidation threat', 'Familiarity threat',
   1, 'A self-review threat arises when the firm evaluates the results of its own previous service. Auditing journal entries prepared by the same firm means the auditors may not appropriately question their own work.', 1),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'The brother of an audit manager assigned to the engagement was recently promoted to finance director of the audit client. The threat most directly created is a:',
   'Self-review threat', 'Advocacy threat', 'Intimidation threat', 'Familiarity threat',
   3, 'A close family member holding a position with significant influence over the client''s financial statements creates a familiarity threat: the manager may be too sympathetic to the relative''s interests or too accepting of his work. The firm should reassign the manager or apply other safeguards.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'An audit firm was asked by its audit client to act as the client''s representative in defending a tax assessment case before the Court of Tax Appeals, where the amounts involved are material to the financial statements. Which threat is most directly created?',
   'Familiarity threat', 'Self-interest threat', 'Advocacy threat', 'Intimidation threat',
   2, 'Acting as the client''s advocate in resolving a dispute before a court or tribunal creates an advocacy threat: the firm promotes the client''s position to the point that its objectivity may be compromised. When the amounts are material, the Code generally prohibits an audit firm from acting in this capacity.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'A client''s CEO told the engagement partner that the firm will be replaced unless it stops questioning a revenue transaction. Which threat to compliance with the fundamental principles is created?',
   'Intimidation threat', 'Self-review threat', 'Familiarity threat', 'Advocacy threat',
   0, 'An intimidation threat arises when the auditor is deterred from acting objectively by actual or perceived pressures, including threats of dismissal or replacement.', 1),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'Fees from one audit client and its subsidiaries constitute 40% of an audit firm''s total annual revenue, and the firm fears losing the client. Which threat is most significant?',
   'Advocacy threat', 'Self-interest threat', 'Self-review threat', 'Familiarity threat',
   1, 'Heavy fee dependence on a single client creates a self-interest threat: concern over losing the fees may improperly influence the firm''s judgments. Safeguards include reducing dependence, external quality reviews, or consulting on key judgments.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'Which of the following safeguards against threats to independence is created by the profession, legislation, or regulation rather than by the firm''s own work environment?',
   'The firm''s policy requiring rotation of senior engagement personnel', 'An engagement quality review performed before the report is released', 'Continuing professional development requirements imposed as a condition for renewing accreditation', 'The firm''s internal monitoring of staff compliance with independence declarations',
   2, 'CPD requirements, professional standards, and external monitoring or disciplinary processes are safeguards created by the profession, legislation, or regulation. Rotation policies, engagement quality reviews, and internal monitoring are safeguards within the firm''s own work environment.', 3),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'Under the Code of Ethics, ''independence in appearance'' is best described as:',
   'The state of mind that permits the expression of a conclusion without being affected by influences that compromise professional judgment', 'Freedom from any financial interest in the client, however immaterial', 'The auditor''s ability to act with integrity and exercise professional skepticism', 'The avoidance of facts and circumstances so significant that a reasonable and informed third party would likely conclude that integrity, objectivity, or professional skepticism has been compromised',
   3, 'Independence in appearance focuses on how a reasonable and informed third party would perceive the circumstances. Independence of mind refers to the auditor''s actual state of mind.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'An audit firm proposed that its fee for the statutory audit be set at 1% of the loan proceeds the client obtains using the audited financial statements. Under the Code of Ethics, this arrangement is:',
   'Prohibited, because a fee contingent on the outcome of the engagement creates a self-interest threat so significant that no safeguard could reduce it to an acceptable level', 'Permitted, provided the percentage is disclosed in the audit report', 'Permitted, because the fee relates to the loan rather than to the audit opinion', 'Prohibited only if the loan is not ultimately granted',
   0, 'Contingent fee arrangements for audit and other assurance engagements are prohibited outright; the self-interest threat to independence cannot be eliminated or reduced by any safeguard. Disclosure does not cure the threat.', 3),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'A CPA in public practice will receive a referral fee from another CPA for referring a continuing client who needs services the CPA does not offer. Under the Code of Ethics, the arrangement is:',
   'Prohibited in all cases because it compromises objectivity', 'Permitted, provided the resulting self-interest threat is addressed, such as by disclosing the arrangement to the client', 'Permitted without any conditions because the client benefits from the referral', 'Prohibited unless the fee is donated to a professional body',
   1, 'Referral fees and commissions create a self-interest threat to objectivity and to competence and due care, but they are not prohibited. The Code requires the threat to be addressed, with disclosure of the arrangement to the client being a key action.', 3),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'Under the standards on quality management adopted in the Philippines, which of the following is a component of a firm''s system of quality management?',
   'The control environment', 'Segregation of incompatible duties', 'Preliminary analytical procedures', 'Governance and leadership',
   3, 'The firm''s system of quality management includes components such as governance and leadership, relevant ethical requirements, acceptance and continuance, engagement performance, resources, information and communication, and the monitoring and remediation process. The control environment and segregation of duties are entity-level internal control concepts.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'For audits of financial statements of listed entities, an engagement quality review must be performed by:',
   'The engagement partner, after the team completes fieldwork', 'Any member of the engagement team with sufficient experience', 'A partner or other suitably qualified individual who is not a member of the engagement team', 'The client''s audit committee before the report is dated',
   2, 'An engagement quality review provides an objective evaluation of the significant judgments made and conclusions reached, so the reviewer must be a suitably qualified person who is not part of the engagement team. It must be completed before the report is dated.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'Before accepting an audit, PSA 210 requires the auditor to establish whether the preconditions for an audit are present. These preconditions include:',
   'Confirmation that the prior auditor issued an unmodified opinion', 'Use by management of an acceptable financial reporting framework and management''s agreement to its responsibilities for the financial statements, internal control, and providing the auditor access to information', 'Completion of the auditor''s risk assessment procedures', 'An assessment that internal control is operating effectively',
   1, 'The preconditions are an acceptable financial reporting framework and management''s acknowledgment of its responsibilities, including granting the auditor access to all relevant information. Risk assessment and control testing come after acceptance.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'On a recurring audit, which circumstance would most likely cause the auditor to send a new engagement letter rather than simply continue under the existing terms?',
   'A recent change in the entity''s ownership and senior management', 'An increase in the assessed risk of material misstatement at the assertion level', 'The client''s request to move the audit fieldwork two weeks later', 'Hiring of additional staff by the entity''s accounting department',
   0, 'PSA 210 lists factors such as changes in ownership, senior management, the nature or size of the business, or legal requirements as reasons to revisit the terms of engagement. Routine scheduling or staffing matters do not require new terms.', 3),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'Under PSA 200, the overall objectives of the auditor in a financial statement audit are to obtain reasonable assurance about whether the financial statements as a whole are free from material misstatement and to:',
   'Guarantee the future viability of the entity', 'Detect all fraud and error affecting the accounts', 'Report on the financial statements and communicate as required by the PSAs, in accordance with the auditor''s findings', 'Express an opinion on the effectiveness of internal control',
   2, 'PSA 200 frames the auditor''s objectives as obtaining reasonable assurance that the statements are free of material misstatement, whether due to fraud or error, and reporting and communicating in accordance with the PSAs. The audit does not guarantee viability or opine on control effectiveness.', 1),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'While auditing inventory, the auditor received an explanation from the controller that contradicted evidence obtained from warehouse personnel and from inspection of records. Exercising professional skepticism, the auditor should:',
   'Accept the controller''s explanation because management is the most informed source', 'Disregard both sources and rely solely on a management representation letter', 'Accept whichever explanation supports the lower inventory balance for conservatism', 'Investigate the inconsistency further and obtain corroborating evidence before relying on either explanation',
   3, 'Professional skepticism requires a questioning mind and a critical assessment of evidence. PSA 200 directs the auditor to investigate when evidence is inconsistent and to determine what modifications or additions to procedures are necessary.', 2),
  ('AUD', 'Framework, Standards & Professional Ethics',
   'An audit conducted in accordance with PSAs cannot provide absolute assurance primarily because:',
   'Management always conceals fraud from the auditor', 'The nature of financial reporting involves judgment and estimates, audit procedures have limitations, and most evidence is persuasive rather than conclusive', 'Materiality cannot be quantified in monetary terms', 'PSAs require only limited assurance in a financial statement audit',
   1, 'Inherent limitations arise from the judgmental nature of financial reporting, the limitations of audit procedures, and the need to conduct the audit within a reasonable time and cost. Because evidence is generally persuasive rather than conclusive, only reasonable assurance is possible.', 1),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Which statement best distinguishes the overall audit strategy from the audit plan?',
   'The strategy sets the scope, timing, and direction of the audit, while the plan describes the nature, timing, and extent of specific procedures', 'The plan is prepared first and the strategy is derived from it', 'The strategy lists individual procedures while the plan states overall objectives', 'The strategy is optional for recurring engagements while the plan is mandatory',
   0, 'Under PSA 300 the overall strategy establishes scope, timing, and direction and guides development of the more detailed audit plan, which specifies the nature, timing, and extent of risk assessment and further audit procedures.', 1),
  ('AUD', 'Audit Planning & Risk Assessment',
   'An auditor obtains an understanding of the entity and its environment primarily to:',
   'Reduce detection risk to zero', 'Identify and assess the risks of material misstatement', 'Express an opinion on management performance', 'Eliminate the need for tests of controls',
   1, 'PSA 315 requires the auditor to understand the entity and its environment, including internal control, to provide a basis for identifying and assessing risks of material misstatement at the financial statement and assertion levels.', 1),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Using the audit risk model AR = IR x CR x DR, if the auditor wants to keep audit risk constant but raises the combined assessment of inherent and control risk, the planned detection risk must:',
   'Remain unchanged because it is set independently', 'Increase, allowing less substantive work', 'Decrease, requiring more extensive substantive procedures', 'Decrease, allowing less substantive work',
   2, 'Detection risk is inversely related to the assessed risks of material misstatement. Higher IR and CR force the auditor to lower detection risk, which means more persuasive and extensive substantive testing.', 2),
  ('AUD', 'Audit Planning & Risk Assessment',
   'An auditor sets desired audit risk at 5 percent, assesses inherent risk at 100 percent and control risk at 50 percent. The implied acceptable detection risk is approximately:',
   '50 percent', '5 percent', '25 percent', '10 percent',
   3, 'Rearranging AR = IR x CR x DR gives DR = AR / (IR x CR) = 0.05 / (1.00 x 0.50) = 0.10, or about 10 percent.', 2),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Compared with an engagement where control risk is assessed as low, an engagement where the auditor assesses control risk as high will generally call for substantive procedures performed:',
   'Closer to year-end rather than at an interim date', 'Earlier at interim with little year-end work', 'Only on a rotational basis', 'With smaller sample sizes',
   0, 'Higher assessed risk of material misstatement reduces acceptable detection risk, prompting the auditor to perform more substantive work at or near period end rather than relying on interim testing.', 2),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Overall materiality for the financial statements as a whole is best described as:',
   'A fixed five percent of net income required by PSA 320', 'The amount above which misstatements could reasonably be expected to influence users economic decisions', 'The smallest error the auditor is able to detect', 'The total of all uncorrected misstatements at year-end',
   1, 'PSA 320 defines materiality in terms of misstatements that, individually or in aggregate, could reasonably be expected to influence the economic decisions of users taken on the basis of the financial statements.', 1),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Performance materiality is set at an amount lower than overall materiality in order to:',
   'Ensure that no misstatement is ever left uncorrected', 'Comply with the PSA requirement that it equal half of overall materiality', 'Reduce to an appropriately low level the probability that aggregate uncorrected and undetected misstatements exceed overall materiality', 'Replace the need to assess inherent risk',
   2, 'Performance materiality is set below overall materiality so that the aggregate of undetected and uncorrected misstatements is unlikely to exceed materiality for the statements as a whole.', 1),
  ('AUD', 'Audit Planning & Risk Assessment',
   'During the audit the auditor finds that actual financial results are far below the budget used to set materiality at planning. The auditor should:',
   'Withdraw from the engagement', 'Ignore the change because materiality is fixed once set', 'Increase materiality to reduce audit effort', 'Reconsider and possibly revise materiality and related procedures',
   3, 'PSA 320 requires the auditor to revise materiality if information comes to light during the audit that would have caused a different initial determination, and to consider the effect on the nature, timing, and extent of procedures.', 2),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Which of the following is a risk assessment procedure rather than a substantive procedure?',
   'Inquiries of management and others within the entity about changes in the business', 'Confirmation of accounts receivable balances with customers', 'Recalculation of depreciation expense', 'Reperformance of a bank reconciliation',
   0, 'Risk assessment procedures under PSA 315 include inquiries, analytical procedures, and observation and inspection used to understand the entity; confirmation, recalculation, and reperformance are substantive in nature.', 1),
  ('AUD', 'Audit Planning & Risk Assessment',
   'A significant risk is one that the auditor:',
   'May ignore if controls appear strong', 'Identifies and treats as requiring special audit consideration', 'Always responds to only through tests of controls', 'Communicates only to the engagement quality reviewer',
   1, 'PSA 315 defines a significant risk as an identified risk of material misstatement requiring special audit consideration; the auditor must understand related controls and may not rely solely on substantive analytical procedures for it.', 1),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Under PSA 240, the three conditions generally present when fraud occurs are:',
   'Materiality, risk, and evidence', 'Collusion, override, and concealment', 'Incentive or pressure, opportunity, and rationalization or attitude', 'Authorization, custody, and recording',
   2, 'The fraud triangle in PSA 240 comprises an incentive or pressure to commit fraud, a perceived opportunity, and an ability to rationalize the act.', 1),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Under PSA 240 the auditor ordinarily presumes that there are risks of fraud in:',
   'Petty cash custody', 'Property additions', 'Prepaid expenses', 'Revenue recognition',
   3, 'PSA 240 contains a rebuttable presumption that there are risks of fraud in revenue recognition, requiring the auditor to evaluate which types of revenue give rise to such risks.', 2),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Because management is in a unique position to perpetrate fraud, PSA 240 requires the auditor, irrespective of risk assessment, to design procedures to address the risk of:',
   'Management override of controls', 'Theft of petty cash by junior staff', 'Errors in clerical arithmetic', 'Late posting of routine entries',
   0, 'PSA 240 requires specific procedures to address management override of controls, including testing journal entries, reviewing accounting estimates for bias, and evaluating significant unusual transactions.', 3),
  ('AUD', 'Audit Planning & Risk Assessment',
   'A controller records fictitious sales near year-end by posting top-side journal entries that bypass the normal sales system. This is best characterized as:',
   'Misappropriation of assets', 'Fraudulent financial reporting through management override', 'An unintentional clerical error', 'A control deficiency without fraud',
   1, 'Deliberate posting of fictitious revenue through manual entries that circumvent normal processing is fraudulent financial reporting accomplished by management override of controls.', 3),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Analytical procedures are required by the PSAs:',
   'Only when controls are weak', 'Only as substantive procedures during fieldwork', 'In the planning stage as risk assessment procedures and near the end of the audit to form an overall conclusion', 'Only for first-year audits',
   2, 'PSA 315 requires analytical procedures during risk assessment, and PSA 520 requires analytical procedures near the end of the audit to assist in forming an overall conclusion on the financial statements.', 2),
  ('AUD', 'Audit Planning & Risk Assessment',
   'During planning analytics the auditor notes that gross margin rose sharply while the industry margin fell. The most appropriate response is to:',
   'Lower performance materiality automatically', 'Conclude the entity is simply more efficient and do no further work', 'Reduce planned substantive procedures on revenue', 'Treat the unexpected fluctuation as a possible indicator of misstatement requiring further investigation',
   3, 'Unexpected or unusual relationships identified by planning analytics may indicate risks of material misstatement and should be investigated to understand the cause before designing the audit response.', 3),
  ('AUD', 'Audit Planning & Risk Assessment',
   'When the external auditor plans to use the work of the entity internal audit function under PSA 610, the auditor must first evaluate:',
   'The function objectivity, competence, and whether it applies a systematic and disciplined approach', 'Only whether the internal auditors are CPAs', 'Only the size of the internal audit department', 'Whether internal audit reports directly to the external auditor',
   0, 'PSA 610 requires the external auditor to evaluate the internal audit function objectivity, level of competence, and whether it applies a systematic and disciplined approach before deciding whether and how to use its work.', 3),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Even when the external auditor uses the work of internal audit, responsibility for the audit opinion:',
   'Is shared equally with internal audit', 'Remains solely with the external auditor', 'Transfers to those charged with governance', 'Is divided according to hours worked',
   1, 'PSA 610 makes clear that the external auditor has sole responsibility for the audit opinion expressed, and that responsibility is not reduced by use of the internal audit function work.', 2),
  ('AUD', 'Audit Planning & Risk Assessment',
   'An auditor engages a valuation specialist to assist in auditing a complex fair value. Under PSA 620 this person is best described as:',
   'An internal auditor subject to PSA 610', 'A management expert independent of the audit', 'An auditor expert whose work the auditor evaluates for use as audit evidence', 'A component auditor under group audit standards',
   2, 'PSA 620 covers an auditor expert, an individual or organization with expertise in a field other than accounting or auditing whose work the auditor uses to obtain sufficient appropriate audit evidence.', 3),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Before relying on the findings of an auditor expert, PSA 620 requires the auditor to:',
   'Disclose the expert identity in the auditor report in every case', 'Re-perform all of the expert calculations personally', 'Obtain the expert agreement to share liability', 'Evaluate the competence, capabilities, and objectivity of the expert and the appropriateness of the expert work',
   3, 'PSA 620 requires evaluation of the expert competence, capabilities, and objectivity, plus an assessment of the adequacy of the expert work as audit evidence for the relevant assertion.', 2),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Audit documentation prepared under PSA 230 should be sufficient to enable an experienced auditor with no previous connection to the audit to understand the:',
   'Nature, timing, and extent of procedures performed, the results, and significant matters and conclusions', 'Personal opinions of each staff member about the client management', 'Detailed fee computation for the engagement', 'Marketing strategy of the audit firm',
   0, 'PSA 230 requires documentation sufficient for an experienced auditor with no previous connection to understand the procedures performed, evidence obtained, significant matters, and the conclusions reached.', 1),
  ('AUD', 'Audit Planning & Risk Assessment',
   'The auditor should assemble the final audit file on a timely basis after the date of the auditor report, ordinarily within:',
   '14 days', '60 days', '90 days', 'One year',
   1, 'PSA 230 sets a time limit for completing the assembly of the final audit file that is ordinarily not more than 60 days after the date of the auditor report.', 2),
  ('AUD', 'Audit Planning & Risk Assessment',
   'An entity introduces a complex new revenue system and enters several large nonroutine transactions just before year-end. These factors most directly increase:',
   'Control risk only', 'Detection risk regardless of testing', 'Inherent risk at the assertion level', 'Sampling risk only',
   2, 'Complexity, nonroutine transactions, and significant change increase the susceptibility of assertions to misstatement before considering controls, which is inherent risk.', 3),
  ('AUD', 'Audit Planning & Risk Assessment',
   'Which matter would the auditor most likely discuss in the required engagement team discussion under PSA 315 and PSA 240?',
   'The historical billing rates of competitors', 'The personal scheduling preferences of the staff', 'The firm overall marketing plan', 'How and where the financial statements may be susceptible to material misstatement, including due to fraud',
   3, 'The standards require the engagement team to discuss the susceptibility of the entity financial statements to material misstatement, including how fraud could occur, to share insights and emphasize professional skepticism.', 2),
  ('AUD', 'Audit Planning & Risk Assessment',
   'If the auditor reduces detection risk for a particular assertion, an appropriate response is to:',
   'Perform substantive tests at year-end rather than interim and increase sample sizes', 'Decrease the extent of substantive procedures', 'Rely entirely on inquiry of management', 'Eliminate confirmation procedures',
   0, 'Lower acceptable detection risk calls for more effective procedures, larger samples, and timing closer to period end to obtain more persuasive evidence.', 2),
  ('AUD', 'Internal Control Consideration',
   'A code of conduct, the board commitment to integrity, and the assignment of authority and responsibility are examples of which component of internal control?',
   'Risk assessment', 'The control environment', 'Control activities', 'Monitoring of controls',
   1, 'Under PSA 315 and COSO, integrity and ethical values, board oversight, organizational structure, and assignment of authority are part of the control environment, the foundation for the other components.', 1),
  ('AUD', 'Internal Control Consideration',
   'Management process for identifying business risks relevant to financial reporting objectives and deciding how to address them is the component called:',
   'Information and communication', 'The control environment', 'The entity risk assessment process', 'Control activities',
   2, 'The entity risk assessment process identifies and analyzes risks to achievement of objectives, including financial reporting objectives, and forms the basis for managing those risks.', 1),
  ('AUD', 'Internal Control Consideration',
   'Performing monthly bank reconciliations and approving purchase orders before payment are examples of which internal control component?',
   'Monitoring of controls', 'The control environment', 'Information and communication', 'Control activities',
   3, 'Control activities are the policies and procedures, such as authorizations, reconciliations, and reviews of performance, that help ensure management directives are carried out.', 1),
  ('AUD', 'Internal Control Consideration',
   'An internal audit department that periodically evaluates whether controls are operating as intended and reports deficiencies to the audit committee illustrates which component?',
   'Monitoring of controls', 'Control activities', 'Risk assessment', 'Information and communication',
   0, 'Monitoring of controls involves ongoing or separate evaluations to assess whether controls are operating effectively and to take corrective action; internal audit evaluations are a classic example.', 1),
  ('AUD', 'Internal Control Consideration',
   'The accounting system that captures, records, processes, and reports transactions and maintains accountability for assets relates most directly to which component?',
   'The control environment', 'The information system relevant to financial reporting and communication', 'Risk assessment', 'Monitoring of controls',
   1, 'The information and communication component includes the information system, comprising the procedures and records that initiate, record, process, and report entity transactions and maintain accountability.', 1),
  ('AUD', 'Internal Control Consideration',
   'Because two or more employees can act together to circumvent procedures that would otherwise prevent fraud, internal control is inherently limited by:',
   'Management philosophy', 'Cost-benefit constraints', 'Collusion', 'Documentation standards',
   2, 'Collusion among employees is an inherent limitation because controls designed around segregation of duties can be defeated when individuals cooperate to conceal irregularities.', 1),
  ('AUD', 'Internal Control Consideration',
   'Which of the following is an inherent limitation of internal control rather than a deficiency in its design?',
   'Lack of any approval for large disbursements', 'A failure to reconcile the bank account monthly', 'Granting one clerk both custody and recording of cash', 'The possibility that management overrides controls it has established',
   3, 'Management override is an inherent limitation that exists even in a well-designed system; the other items are specific deficiencies in design or operation.', 2),
  ('AUD', 'Internal Control Consideration',
   'The principle that the cost of a control should not exceed the benefits expected from it reflects the inherent limitation known as:',
   'Cost-benefit considerations', 'Human error', 'Collusion', 'Management override',
   0, 'Internal control is constrained by the requirement that its benefits, in reduced risk, justify its costs; this cost-benefit balance is an inherent limitation.', 1),
  ('AUD', 'Internal Control Consideration',
   'Proper segregation of duties requires separating which three functions?',
   'Planning, execution, and reporting', 'Authorization, custody of assets, and recording', 'Hiring, training, and supervision', 'Budgeting, forecasting, and analysis',
   1, 'Effective segregation separates authorization of transactions, custody of related assets, and recording in the accounts so that no single person can both perpetrate and conceal errors or fraud.', 1),
  ('AUD', 'Internal Control Consideration',
   'The same employee opens incoming mail containing customer checks, records the cash receipts in the ledger, and reconciles the bank account. This situation indicates:',
   'A strength because fewer people reduces error', 'An acceptable control because one person ensures consistency', 'A segregation of duties violation combining custody and recording', 'An information system deficiency only',
   2, 'Combining custody of cash with recording and reconciliation gives one person the ability to misappropriate receipts and conceal the act, a classic segregation of duties violation.', 3),
  ('AUD', 'Internal Control Consideration',
   'The distinction between understanding controls and testing controls is that understanding controls is performed to:',
   'Confirm balances with third parties', 'Conclude on operating effectiveness over the period', 'Project a deviation rate to the population', 'Evaluate the design of controls and determine whether they have been implemented',
   3, 'PSA 315 requires the auditor to understand controls by evaluating design and determining implementation; testing operating effectiveness over time is a separate step under PSA 330.', 2),
  ('AUD', 'Internal Control Consideration',
   'A walkthrough, in which the auditor traces one transaction from initiation through the records to the financial statements, is primarily used to:',
   'Confirm the auditor understanding of the process and whether controls are implemented', 'Establish operating effectiveness for the whole year', 'Compute the sample size for substantive tests', 'Provide sufficient evidence to assess control risk as low',
   0, 'A walkthrough helps confirm that the auditor understanding of the flow of transactions is accurate and that relevant controls have been implemented; it is not sufficient alone to conclude on operating effectiveness.', 2),
  ('AUD', 'Internal Control Consideration',
   'Tests of controls to evaluate operating effectiveness ordinarily combine which procedures?',
   'Confirmation and recalculation only', 'Inquiry combined with observation, inspection, and reperformance', 'Analytical procedures alone', 'Inquiry alone',
   1, 'Because inquiry alone is not sufficient, PSA 330 indicates tests of controls usually combine inquiry with observation, inspection of documents, and reperformance to obtain evidence about operating effectiveness.', 2),
  ('AUD', 'Internal Control Consideration',
   'Tests of controls are required when:',
   'The client requests reliance on its controls', 'Controls are documented in a flowchart', 'The auditor intends to rely on controls or substantive procedures alone cannot provide sufficient appropriate evidence', 'Every audit, regardless of strategy',
   2, 'Under PSA 330 tests of controls are required when the auditor plans to rely on operating effectiveness, and also when substantive procedures alone cannot provide sufficient appropriate evidence at the assertion level.', 2),
  ('AUD', 'Internal Control Consideration',
   'The auditor plans to rely on a control that operates many times a day in a highly automated, routine process. Once the control program logic is tested and general IT controls are effective, the auditor may:',
   'Assess control risk as low without any testing', 'Test the control on every transaction in the year', 'Disregard general IT controls entirely', 'Rely on the consistency of automated processing and limit the extent of further testing of that programmed control',
   3, 'For automated controls the inherent consistency of computer processing means that once the program and supporting general IT controls are tested, the auditor can rely on the control without testing each operation.', 3),
  ('AUD', 'Internal Control Consideration',
   'Under PSA 265, a deficiency in internal control exists when:',
   'A control is designed, implemented, or operated so it cannot prevent or detect and correct misstatements, or a needed control is missing', 'Any misstatement at all is found in the records', 'The client refuses to pay the audit fee', 'The auditor disagrees with management accounting estimate',
   0, 'PSA 265 defines a control deficiency as a control that is unable to prevent, or detect and correct, misstatements on a timely basis, or the absence of a control necessary to do so.', 2),
  ('AUD', 'Internal Control Consideration',
   'Under PSA 265, a significant deficiency is one that:',
   'Always results in a qualified opinion', 'In the auditor professional judgment is important enough to merit the attention of those charged with governance', 'Must be reported to the public regulator', 'Is the same as an immaterial clerical error',
   1, 'PSA 265 defines a significant deficiency as a deficiency or combination of deficiencies that, in the auditor professional judgment, is of sufficient importance to merit the attention of those charged with governance.', 2),
  ('AUD', 'Internal Control Consideration',
   'Under PSA 265, significant deficiencies identified during the audit must be communicated:',
   'To the general public in the auditor report', 'Orally only and only to management', 'In writing to those charged with governance on a timely basis', 'Solely in the engagement working papers',
   2, 'PSA 265 requires the auditor to communicate significant deficiencies in writing to those charged with governance on a timely basis.', 2),
  ('AUD', 'Internal Control Consideration',
   'A user entity outsources its payroll processing to a service organization. To obtain assurance about controls at that organization over a period of time, the user auditor would most prefer:',
   'A marketing brochure from the service organization', 'A Type 1 report on description and design only', 'A management representation letter from the service organization', 'A Type 2 report on the description, design, and operating effectiveness of controls',
   3, 'A Type 2 report covers the description and design of controls and their operating effectiveness throughout a specified period, providing evidence the user auditor can rely on; a Type 1 report addresses design as of a point in time only.', 2),
  ('AUD', 'Internal Control Consideration',
   'A Type 1 service organization report differs from a Type 2 report in that the Type 1 report:',
   'Reports on the suitability of design at a point in time without testing operating effectiveness over a period', 'Always provides more assurance than a Type 2 report', 'Tests operating effectiveness over the whole year', 'Is prepared by the user auditor',
   0, 'A Type 1 report addresses the description and suitability of design of controls as at a specified date and does not include tests of operating effectiveness, which a Type 2 report covers over a period.', 2),
  ('AUD', 'Internal Control Consideration',
   'Authorizing a sales transaction, shipping the goods, and recording the sale in the ledger are performed by three different departments. This arrangement is intended primarily to:',
   'Speed up the order-to-cash cycle', 'Achieve segregation of duties so that errors or fraud are detected in the normal course of work', 'Reduce the number of employees needed', 'Eliminate the need for management review',
   1, 'Dividing authorization, custody, and recording across departments means the work of one serves as a check on another, helping detect or prevent errors and fraud during normal operations.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'In the context of audit evidence, sufficiency and appropriateness refer respectively to:',
   'The number of staff used and their experience', 'The cost of evidence and its timeliness', 'The quantity of evidence and its quality in terms of relevance and reliability', 'The wording of the report and its date',
   2, 'PSA 500 describes sufficiency as the measure of the quantity of audit evidence and appropriateness as the measure of its quality, namely its relevance and reliability in supporting the conclusions.', 1),
  ('AUD', 'Audit Evidence & Procedures',
   'Which source of audit evidence is generally considered the most reliable?',
   'An internally generated document not subject to controls', 'An oral representation by management', 'A photocopy provided by the client', 'Evidence obtained directly by the auditor, such as observation of a control being applied',
   3, 'PSA 500 indicates that evidence obtained directly by the auditor is more reliable than evidence obtained indirectly or by inference; direct observation outranks client representations and internally generated copies.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'All else equal, which item provides the most reliable audit evidence about a receivable balance?',
   'A confirmation received directly from an independent customer', 'A duplicate sales invoice prepared by the client', 'A verbal assurance from the credit manager', 'An entry in the client subsidiary ledger',
   0, 'External evidence received directly from an independent party is more reliable than internally generated documents or oral statements, making the customer confirmation the strongest of the choices.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Inspecting shipping documents and matching them to recorded sales tests primarily which assertion for sales transactions?',
   'Occurrence', 'Completeness', 'Classification', 'Cutoff',
   1, 'Starting from shipping documents and tracing into the sales records tests completeness, because it detects shipments that were made but not recorded.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Selecting recorded sales entries and vouching them to shipping documents and customer orders tests primarily which assertion?',
   'Valuation', 'Completeness', 'Occurrence', 'Rights',
   2, 'Beginning with recorded sales and vouching back to supporting documents tests occurrence, providing evidence that recorded sales actually took place.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Vouching, the direction of testing from recorded amounts back to source documents, is most useful for detecting:',
   'Errors in the prior period opening balance', 'Understatement from unrecorded items', 'Misclassification between equity accounts', 'Overstatement of recorded items',
   3, 'Vouching tests existence or occurrence and is therefore directed at detecting overstatement, because it confirms that what is recorded is supported by underlying documentation.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Tracing source documents forward into the accounting records is the directional test most useful for detecting:',
   'Understatement from unrecorded transactions', 'Overstatement of recorded balances', 'Misposting between two asset accounts', 'Arithmetical errors in footing',
   0, 'Tracing from source documents to the records tests completeness and is aimed at detecting understatement, because it reveals transactions that occurred but were never recorded.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'To obtain evidence about the existence assertion for inventory, the most appropriate procedure is to:',
   'Trace purchase requisitions to the inventory subsidiary records', 'Observe the physical inventory count and inspect selected items', 'Recompute the lower of cost and net realizable value', 'Confirm inventory quantities with the customers',
   1, 'Existence of inventory is best supported by physically observing the count and inspecting items, which provides direct evidence that the recorded inventory actually exists.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'An auditor recomputes the client provision for depreciation. This procedure is best classified as:',
   'Observation', 'External confirmation', 'Recalculation', 'Inquiry',
   2, 'Recalculation consists of checking the mathematical accuracy of documents or records, such as independently recomputing depreciation expense.', 1),
  ('AUD', 'Audit Evidence & Procedures',
   'The auditor independently re-performs the bank reconciliation prepared by the client. This procedure is best described as:',
   'Analytical procedure', 'Inquiry', 'Observation', 'Reperformance',
   3, 'Reperformance is the auditor independent execution of procedures or controls that were originally performed as part of the entity internal control, such as redoing a bank reconciliation.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Which procedure provides evidence only at the moment it is performed and may not be representative of other times?',
   'Observation of a control being applied', 'Inspection of a signed contract', 'External confirmation of a balance', 'Recalculation of interest',
   0, 'Observation provides evidence limited to the point in time it occurs and to the fact that being observed may change behavior, so it is generally corroborated by other procedures.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Comparing this year recorded interest expense with an independent expectation based on average loan balances and interest rates is an example of a:',
   'Test of details of balances', 'Substantive analytical procedure', 'Test of controls', 'External confirmation',
   1, 'Developing an independent expectation of an account such as interest expense and comparing it to the recorded amount is a substantive analytical procedure under PSA 520.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'A substantive analytical procedure is most likely to be effective and efficient when:',
   'Controls over the data are known to be ineffective', 'The account contains many nonroutine and unpredictable transactions', 'The relationship being tested is plausible and predictable and data are reliable', 'The auditor cannot develop any expectation',
   2, 'Substantive analytical procedures are most suitable for large volumes of transactions that are predictable over time, supported by reliable data from which a precise expectation can be developed.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Under PSA 540, the auditor primary objective when auditing an accounting estimate such as a warranty provision is to obtain evidence about whether:',
   'No estimate is required at all', 'Management used the exact method the auditor would have chosen', 'The estimate equals the figure realized in the following year', 'The estimate and related disclosures are reasonable in the context of the applicable framework',
   3, 'PSA 540 requires the auditor to evaluate whether accounting estimates and related disclosures are reasonable in the context of the financial reporting framework and to assess estimation uncertainty and management bias.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'When auditing a fair value estimate with high estimation uncertainty, the auditor would most appropriately:',
   'Apply increased professional skepticism and consider whether specialized skills or a range of reasonable outcomes are needed', 'Accept management point estimate without further inquiry', 'Reduce the extent of testing because the figure is judgmental', 'Treat the estimate as a routine transaction',
   0, 'High estimation uncertainty under PSA 540 calls for heightened skepticism, evaluation of the methods and assumptions, possible use of an auditor expert, and consideration of a range of reasonable outcomes.', 3),
  ('AUD', 'Audit Evidence & Procedures',
   'Under PSA 505, a positive external confirmation request asks the respondent to:',
   'Reply only if they disagree with the information', 'Reply directly to the auditor in all cases, whether or not they agree with the stated information', 'Confirm only balances above materiality', 'Send the reply to the client first',
   1, 'A positive confirmation requests the respondent to respond directly to the auditor indicating whether they agree, providing evidence whether or not a discrepancy exists; a negative request asks for a reply only when the respondent disagrees.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Negative confirmation requests provide less persuasive evidence and under PSA 505 are appropriate only when, among other conditions:',
   'Exceptions are expected to be numerous', 'The risk of material misstatement is high', 'The risk of material misstatement is low and a large number of small, homogeneous balances are involved', 'The respondents are unlikely to read the request',
   2, 'PSA 505 permits sole reliance on negative confirmations only when the assessed risk is low, the population comprises a large number of small homogeneous balances, a very low exception rate is expected, and respondents are likely to consider the requests.', 3),
  ('AUD', 'Audit Evidence & Procedures',
   'When a positive confirmation request receives no reply, the auditor should:',
   'Send a negative confirmation instead and stop', 'Treat the nonresponse as full confirmation of the balance', 'Automatically conclude the balance is misstated', 'Perform alternative procedures such as examining subsequent cash receipts and shipping documents',
   3, 'For nonresponses to positive confirmations, PSA 505 requires the auditor to perform alternative audit procedures, such as inspecting subsequent receipts, shipping documentation, and sales near period end.', 3),
  ('AUD', 'Audit Evidence & Procedures',
   'A customer returns a confirmation reporting a balance lower than the client records, and investigation shows the client recorded a payment in the wrong period. This exception is best treated as:',
   'A possible misstatement to be evaluated and, if confirmed, accumulated', 'Conclusive proof of pervasive fraud', 'An immaterial item requiring no further work', 'Evidence that confirmations are unreliable',
   0, 'Under PSA 505 the auditor investigates exceptions to determine whether they indicate misstatements; a confirmed timing error is a misstatement to be evaluated and accumulated for consideration.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Under PSA 510, when an auditor accepts an initial engagement, audit procedures over opening balances are designed to obtain evidence about whether:',
   'The prior auditor was negligent', 'Opening balances contain misstatements that materially affect the current period and accounting policies are consistently applied', 'The client should change its accounting framework', 'All prior period transactions must be re-audited in full',
   1, 'PSA 510 requires the auditor to obtain sufficient appropriate evidence about whether opening balances contain misstatements that materially affect the current period statements and whether appropriate accounting policies have been consistently applied.', 3),
  ('AUD', 'Audit Evidence & Procedures',
   'To test the rights and obligations assertion for recorded equipment, the auditor would most appropriately:',
   'Recompute accumulated depreciation', 'Observe the physical condition of the equipment', 'Inspect title documents and supporting purchase and finance agreements', 'Trace requisitions into the fixed asset register',
   2, 'Rights and obligations is best supported by examining ownership documentation such as titles, deeds, and purchase or financing agreements that establish the entity rights to the asset.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'An auditor reviews the listing of liabilities and searches for unrecorded payables by examining disbursements after year-end. This procedure principally addresses which assertion for liabilities?',
   'Classification', 'Existence', 'Rights and obligations', 'Completeness',
   3, 'Searching for unrecorded liabilities, including reviewing subsequent disbursements, tests the completeness assertion for liabilities, which are prone to understatement.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Inquiry as an audit procedure:',
   'Alone seldom provides sufficient appropriate evidence and is usually corroborated by other procedures', 'Is the most reliable single procedure available', 'Is sufficient to test the operating effectiveness of controls by itself', 'Provides external evidence directly to the auditor',
   0, 'Inquiry consists of seeking information from knowledgeable persons; while important, it alone seldom provides sufficient appropriate evidence and is normally corroborated by other procedures.', 1),
  ('AUD', 'Audit Evidence & Procedures',
   'Examining a recorded repairs expense to determine whether it should have been capitalized as an asset tests primarily which transaction assertion?',
   'Cutoff', 'Classification', 'Occurrence', 'Completeness',
   1, 'Determining whether an item was recorded in the proper account, such as expense versus asset, addresses the classification assertion for transactions.', 2),
  ('AUD', 'Audit Evidence & Procedures',
   'Recording a December sale only in January, after goods shipped in December, is a misstatement of which transaction assertion?',
   'Occurrence', 'Classification', 'Cutoff', 'Rights',
   2, 'Recording transactions in the wrong accounting period, when goods shipped in one period but the sale is booked in the next, is a cutoff error for sales transactions.', 2),
  ('AUD', 'Audit Sampling',
   'Sampling risk is best described as the risk that:',
   'The control does not operate as designed', 'The auditor uses an inappropriate procedure for the assertion', 'The auditor misinterprets evidence or applies a procedure incorrectly', 'The auditor conclusion based on a sample differs from the conclusion if the entire population were tested',
   3, 'Sampling risk arises because the sample may not be representative of the population, so the auditor conclusion based on the sample may differ from the conclusion reached by examining the entire population.', 1),
  ('AUD', 'Audit Sampling',
   'Nonsampling risk refers to the risk that:',
   'The auditor reaches an erroneous conclusion for reasons unrelated to sample size, such as using unsuitable procedures or misinterpreting evidence', 'The sample selected is too small', 'The population deviation rate exceeds the tolerable rate', 'The auditor selects items haphazardly',
   0, 'Nonsampling risk is the risk that the auditor reaches an erroneous conclusion for any reason not related to sampling, such as applying inappropriate procedures or failing to recognize a misstatement.', 2),
  ('AUD', 'Audit Sampling',
   'In substantive testing, the risk of incorrect acceptance is the risk that the auditor concludes:',
   'A material misstatement exists when it does not', 'A material misstatement does not exist when in fact it does', 'Controls are effective when they are not', 'The sample is too large',
   1, 'The risk of incorrect acceptance is that the sample supports the conclusion that the recorded balance is not materially misstated when in fact it is, which relates to audit effectiveness.', 2),
  ('AUD', 'Audit Sampling',
   'Of the two aspects of sampling risk in substantive tests, the one that relates to the effectiveness of the audit is the risk of:',
   'Overreliance through smaller samples', 'Incorrect rejection', 'Incorrect acceptance', 'Underreliance through larger samples',
   2, 'Incorrect acceptance affects effectiveness because the auditor may fail to detect a material misstatement; incorrect rejection affects efficiency, prompting unnecessary additional work.', 2),
  ('AUD', 'Audit Sampling',
   'In tests of controls, the risk of overreliance, or assessing control risk too low, is the risk that the auditor concludes:',
   'The sample size is insufficient', 'Controls are less effective than they actually are', 'The balance is fairly stated when it is not', 'Controls are more effective than they actually are',
   3, 'Overreliance, or assessing control risk too low, occurs when the sample suggests controls are operating effectively when they are not, which impairs audit effectiveness.', 2),
  ('AUD', 'Audit Sampling',
   'Between the two aspects of sampling risk in tests of controls, the one that primarily affects audit efficiency rather than effectiveness is the risk of:',
   'Underreliance, or assessing control risk too high', 'Overreliance, or assessing control risk too low', 'Incorrect acceptance', 'Tolerable deviation',
   0, 'Underreliance leads the auditor to perform more substantive work than necessary, affecting efficiency, whereas overreliance affects effectiveness by leaving misstatements undetected.', 2),
  ('AUD', 'Audit Sampling',
   'The essential characteristic that distinguishes statistical from nonstatistical sampling is that statistical sampling:',
   'Always uses a larger sample size', 'Uses random-based selection and allows the sampling risk to be measured quantitatively', 'Eliminates nonsampling risk', 'Requires no auditor judgment at any stage',
   1, 'Statistical sampling uses random selection and probability theory to measure sampling risk quantitatively; nonstatistical sampling relies on judgment and does not permit such measurement, though both require judgment.', 2),
  ('AUD', 'Audit Sampling',
   'In attribute sampling for a test of controls, the tolerable deviation rate is:',
   'The expected rate based on prior years', 'The rate of deviation actually found in the sample', 'The maximum rate of deviation the auditor is willing to accept and still rely on the control', 'The difference between two confidence levels',
   2, 'The tolerable deviation rate is the maximum rate of deviation from a prescribed control the auditor will permit and still conclude the control can be relied upon for the planned assessment.', 2),
  ('AUD', 'Audit Sampling',
   'In an attribute sample of 100 items the auditor finds 3 deviations and computes an upper deviation rate of 7.6 percent against a tolerable deviation rate of 8 percent. The auditor should:',
   'Treat the result as inconclusive and stop work', 'Conclude that the control cannot be relied upon', 'Increase the tolerable rate to match the result', 'Conclude that the control can be relied upon as planned',
   3, 'Because the computed upper deviation rate of 7.6 percent does not exceed the tolerable deviation rate of 8 percent, the sample supports reliance on the control at the planned level.', 3),
  ('AUD', 'Audit Sampling',
   'Holding other factors constant, an increase in the expected population deviation rate will cause the required sample size for a test of controls to:',
   'Increase', 'Decrease', 'Remain the same', 'Become zero',
   0, 'A higher expected deviation rate, with tolerable rate and risk held constant, narrows the allowance for sampling risk and therefore increases the required sample size.', 2),
  ('AUD', 'Audit Sampling',
   'Using monetary unit sampling, an auditor finds an item with a book value of 10,000 that should be 8,000. The tainting percentage applied to project the misstatement for this item is:',
   '80 percent', '20 percent', '25 percent', '100 percent',
   1, 'Tainting percentage equals the misstatement divided by the book value, here 2,000 divided by 10,000, or 20 percent, which is applied to the sampling interval to project the misstatement.', 3),
  ('AUD', 'Audit Sampling',
   'Monetary unit sampling, a form of probability-proportional-to-size selection, is most useful when the auditor:',
   'Wants every item to have an equal chance of selection regardless of size', 'Expects many understatements of recorded amounts', 'Expects few misstatements and wants to focus selection on larger peso items', 'Is testing the completeness of unrecorded liabilities',
   2, 'Monetary unit sampling gives larger peso items a higher chance of selection and is efficient when few misstatements are expected; it is less suited to detecting understatements or testing unrecorded items.', 3),
  ('AUD', 'Audit Sampling',
   'Selecting a starting point at random and then choosing every nth item from the population describes which selection method?',
   'Stratified selection', 'Haphazard selection', 'Block selection', 'Systematic selection',
   3, 'Systematic selection divides the population by the sample size to obtain an interval and selects every nth item after a random start; haphazard and block methods do not use a fixed interval.', 2)
)
insert into public.questions (topic_id, stem, choices, correct_index, explanation, difficulty)
select t.id, q.stem, jsonb_build_array(q.a, q.b, q.c, q.d), q.correct_index, q.explanation, q.difficulty
from q join t on t.code = q.subject_code and lower(t.name) = lower(q.topic)
where not exists (select 1 from public.questions x where x.stem = q.stem);
