-- Generated from content/far-batch-003.csv by scripts/csv-to-seed-sql.mjs — do not edit by hand.
-- Idempotent: skips any question whose stem already exists.
with t as (
  select tp.id, tp.name, s.code from public.topics tp
  join public.subjects s on s.id = tp.subject_id
),
q(subject_code, topic, stem, a, b, c, d, correct_index, explanation, difficulty) as (values
  ('FAR', 'Property, Plant & Equipment',
   'An item of PPE was acquired on a deferred payment plan extending beyond normal credit terms. The asset is recorded at:',
   'Its cash price equivalent, with the excess of total payments recognized as interest expense over the credit period', 'The total of all payments to be made', 'The total payments less any residual value', 'The first installment paid',
   0, 'When payment is deferred beyond normal credit terms, cost is the cash price equivalent (present value); the difference between that amount and total payments is interest expense over the period of credit, unless capitalized under PAS 23.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'An entity constructed a machine for its own use at a total cost lower than the price quoted by outside suppliers. The saving is:',
   'Recognized as income in the year of completion', 'Credited to a revaluation surplus', 'Not recognized — the asset is simply recorded at its actual cost of construction', 'Deducted from depreciation over the asset''s life',
   2, 'Self-constructed assets are measured at the actual directly attributable costs of construction. Internal ''profit'' or savings versus an outside purchase price is never recognized as income or equity.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'Under PAS 20, a government grant related to a depreciable asset may be presented as:',
   'Either deferred income amortized over the asset''s life, or a deduction from the asset''s carrying amount', 'Direct credit to retained earnings', 'Immediate income upon receipt in all cases', 'Share premium from government contribution',
   0, 'Grants related to assets are presented either as deferred income recognized in profit or loss over the asset''s useful life, or by deducting the grant from the asset''s carrying amount (reducing depreciation). Immediate income or equity treatment is prohibited.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'A government grant is recognized only when there is reasonable assurance that:',
   'The grant has been received in cash', 'The entity will generate taxable income against the grant', 'The government will not request repayment within five years', 'The entity will comply with the conditions attaching to the grant and the grant will be received',
   3, 'PAS 20 requires reasonable assurance on both counts — compliance with conditions and receipt — before recognition. Receipt of cash alone is not conclusive, as conditions may remain unfulfilled.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'An asset costing P1,100,000 with a residual value of P100,000 has a four-year useful life. Under the sum-of-the-years''-digits method, depreciation for the second year is:',
   'P200,000', 'P250,000', 'P300,000', 'P400,000',
   2, 'SYD denominator = 4+3+2+1 = 10. Depreciable amount = P1,000,000. Year 2 uses the fraction 3/10: P1,000,000 × 3/10 = P300,000 (Year 1 was 4/10 = P400,000).', 2),
  ('FAR', 'Property, Plant & Equipment',
   'A machine costing P5,000,000 with a residual value of P500,000 is expected to produce 1,000,000 units over its life. It produced 150,000 units this year. Depreciation under the units-of-production method is:',
   'P600,000', 'P675,000', 'P750,000', 'P825,000',
   1, 'Depreciation rate = (P5,000,000 − P500,000) ÷ 1,000,000 = P4.50 per unit. Charge for the year = 150,000 × P4.50 = P675,000.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'Under PAS 16, each part of an item of PPE with a cost that is significant in relation to the total cost of the item (e.g., an aircraft''s engines and airframe):',
   'Shall be depreciated separately', 'Shall be depreciated using the rate applicable to the principal asset', 'May be expensed when replaced', 'Shall be combined and depreciated over the average useful life',
   0, 'Component (parts) depreciation is mandatory: significant parts with different useful lives or patterns of consumption are depreciated separately, and replacements are capitalized with the replaced part derecognized.', 1),
  ('FAR', 'Property, Plant & Equipment',
   'Equipment costing P3,000,000 with no residual value was being depreciated over 10 years. At the start of Year 5, the remaining useful life was revised to 4 years. Depreciation for Year 5 is:',
   'P300,000', 'P360,000', 'P450,000', 'P600,000',
   2, 'Carrying amount after 4 years = P3,000,000 − (4 × P300,000) = P1,800,000. The change in estimate is applied prospectively: P1,800,000 ÷ 4 remaining years = P450,000 per year.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'Which of the following is classified as a land improvement rather than land?',
   'Special assessments for public improvements levied by the local government', 'Cost of clearing and grading prior to construction', 'Legal fees and title insurance on acquisition', 'Cost of driveways, fences and parking lots',
   3, 'Driveways, fences, parking lots and similar depreciable additions are land improvements. Special assessments, clearing/grading incident to acquisition, and title costs attach to the land account, which is not depreciated.', 1),
  ('FAR', 'Property, Plant & Equipment',
   'A ship requires a dry-dock overhaul every three years as a condition of continued operation. The cost of each overhaul is:',
   'Expensed when paid', 'Capitalized as part of the ship''s carrying amount and depreciated over three years, derecognizing any remaining cost of the previous overhaul', 'Accrued as a provision evenly over the three years preceding the overhaul', 'Charged directly to retained earnings',
   1, 'Major inspections and overhauls are accounted for as a separate component: capitalized when performed and depreciated until the next overhaul, with any carrying amount of the previous inspection derecognized. Accruing in advance is prohibited because there is no present obligation.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'Equipment with a cost of P2,400,000 and accumulated depreciation of P1,500,000 was sold for P1,100,000. The disposal results in:',
   'A gain of P200,000', 'A loss of P200,000', 'A gain of P900,000', 'A gain of P1,100,000',
   0, 'Carrying amount = P2,400,000 − P1,500,000 = P900,000. Proceeds of P1,100,000 less carrying amount of P900,000 = P200,000 gain, presented in profit or loss (not as revenue).', 1),
  ('FAR', 'Property, Plant & Equipment',
   'In an exchange of assets that lacks commercial substance, the asset received is measured at:',
   'Fair value of the asset received', 'Fair value of the asset given up', 'Carrying amount of the asset given up, with no gain or loss recognized', 'The lower of fair value and carrying amount, with a loss recognized',
   2, 'When an exchange lacks commercial substance (or fair values are not reliably measurable), the acquired asset is measured at the carrying amount of the asset surrendered, plus cash paid, and no gain or loss arises.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'Under PAS 36, the recoverable amount of an asset is:',
   'Fair value less costs of disposal in all cases', 'The higher of fair value less costs of disposal and value in use', 'The lower of carrying amount and fair value', 'The present value of future cash flows in all cases',
   1, 'Recoverable amount is the higher of (1) fair value less costs of disposal and (2) value in use. An impairment loss exists only when carrying amount exceeds this recoverable amount.', 1),
  ('FAR', 'Property, Plant & Equipment',
   'An asset has a carrying amount of P4,000,000, a fair value less costs of disposal of P3,400,000, and a value in use of P3,600,000. The impairment loss is:',
   'P0', 'P400,000', 'P600,000', 'P1,000,000',
   1, 'Recoverable amount = higher of P3,400,000 and P3,600,000 = P3,600,000. Impairment loss = P4,000,000 − P3,600,000 = P400,000. Using fair value less costs of disposal alone would overstate the loss.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'The reversal of an impairment loss on an asset other than goodwill is limited to:',
   'The original impairment loss recognized', 'The asset''s recoverable amount, without limit', 'The asset''s fair value at the reversal date', 'The carrying amount that would have been determined, net of depreciation, had no impairment been recognized',
   3, 'A reversal cannot lift the asset above its ''depreciated historical cost ceiling'' — the carrying amount it would have had if no impairment had ever been recognized. Goodwill impairment is never reversed.', 3),
  ('FAR', 'Property, Plant & Equipment',
   'An impairment loss on a cash-generating unit is allocated:',
   'First to goodwill allocated to the unit, then pro rata to the other assets based on their carrying amounts', 'Pro rata to all assets including goodwill', 'First to the asset with the longest remaining life', 'Entirely to the asset with the most observable fair value',
   0, 'CGU impairment reduces goodwill first; any remainder is allocated pro rata to the unit''s other assets, but no asset is reduced below the highest of its fair value less costs of disposal, value in use, or zero.', 3),
  ('FAR', 'Property, Plant & Equipment',
   'A mining property was acquired for P9,000,000, with development costs of P3,000,000 and an estimated restoration obligation (at present value) of P1,000,000. Expected residual value of the land is P1,000,000 and estimated reserves are 3,000,000 tons. If 400,000 tons were extracted this year, depletion is:',
   'P1,200,000', 'P1,440,000', 'P1,600,000', 'P1,733,333',
   2, 'Depletable amount = P9,000,000 + P3,000,000 + P1,000,000 − P1,000,000 = P12,000,000; rate = P12,000,000 ÷ 3,000,000 tons = P4/ton. Depletion = 400,000 × P4 = P1,600,000.', 3),
  ('FAR', 'Property, Plant & Equipment',
   'An asset that is fully depreciated but still used in operations:',
   'Is removed from the accounts', 'Is restored to its fair value with a credit to income', 'Is reported at residual value as a separate line item', 'Remains in the accounts at cost less accumulated depreciation, with no further depreciation recognized',
   3, 'The cost and accumulated depreciation stay on the books until disposal; depreciation stops once the depreciable amount is consumed. Writing the asset back up is prohibited (disclosure of material fully depreciated assets in use is encouraged).', 1),
  ('FAR', 'Property, Plant & Equipment',
   'After a revaluation, an entity may transfer the revaluation surplus to retained earnings as the asset is used. The amount transferred each period is:',
   'The total revaluation surplus divided by the asset''s original life', 'The difference between depreciation based on the revalued amount and depreciation based on original cost', 'The full surplus, in the year following revaluation', 'Nothing — the surplus must remain until disposal',
   1, 'The piecemeal transfer equals the extra depreciation caused by the revaluation (revalued depreciation minus historical-cost depreciation). The transfer is made directly within equity, never through profit or loss. Transferring only on disposal is also permitted.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'An entity financed construction of a qualifying asset from its general borrowings. Average expenditures on the asset during the year were P4,000,000 and the weighted average borrowing rate on general loans (totaling P10,000,000) was 10%, with actual borrowing costs of P1,000,000. The capitalizable borrowing cost is:',
   'P0', 'P400,000', 'P600,000', 'P1,000,000',
   1, 'For general borrowings, capitalization = average expenditures × capitalization rate = P4,000,000 × 10% = P400,000, capped at the actual borrowing costs incurred (P1,000,000). The unused P600,000 is expensed.', 3),
  ('FAR', 'Intangibles & Investment Property',
   'Goodwill is recognized as an asset:',
   'Whenever an entity''s market value exceeds its book value', 'When it is internally generated through superior management and customer loyalty', 'Only when it is acquired in a business combination', 'Whenever an independent appraiser can measure it reliably',
   2, 'Goodwill is recognized only as the residual in a business combination under PFRS 3. Internally generated goodwill is never recognized because it is not an identifiable resource controlled by the entity that can be measured reliably at cost.', 1),
  ('FAR', 'Intangibles & Investment Property',
   'The residual value of an intangible asset with a finite useful life is assumed to be zero unless:',
   'A third party has committed to purchase the asset at the end of its useful life, or an active market exists and is expected to exist at the end of its useful life', 'Management expects to sell the asset eventually', 'The asset was acquired in a business combination', 'The asset''s fair value exceeds its carrying amount',
   0, 'PAS 38 presumes a zero residual value except when there is a committed buyer or an active market from which residual value can be determined and which is probable to exist at the end of the asset''s useful life.', 2),
  ('FAR', 'Intangibles & Investment Property',
   'Equipment acquired for use in research and development activities, which has alternative future uses, is:',
   'Expensed immediately in full', 'Capitalized and depreciated, with the depreciation charged to research and development expense while so used', 'Capitalized but not depreciated until R&D activities end', 'Charged directly to retained earnings',
   1, 'Capital assets with alternative future uses are capitalized as PPE; only their depreciation while used in R&D forms part of R&D expense. Equipment usable solely for a single R&D project is expensed (research) or assessed under development criteria.', 2),
  ('FAR', 'Intangibles & Investment Property',
   'The design, construction and testing of a chosen alternative for a new process before the start of commercial production is an example of:',
   'A research activity', 'An activity expensed as incurred in all cases', 'Routine quality control', 'A development activity',
   3, 'Designing, constructing and testing a chosen alternative (e.g., a prototype or pilot plant) is a development activity, capitalizable once the PAS 38 recognition criteria are demonstrated. Searching for and evaluating alternatives is research.', 2),
  ('FAR', 'Intangibles & Investment Property',
   'If an entity cannot distinguish the research phase from the development phase of an internal project, the expenditure on the project is:',
   'Treated as if incurred in the research phase only, and expensed', 'Treated as development and capitalized', 'Allocated equally between research and development', 'Deferred until the distinction becomes clear',
   0, 'When the phases cannot be distinguished, PAS 38 requires treating all expenditure as research-phase expenditure, which is expensed as incurred.', 2),
  ('FAR', 'Intangibles & Investment Property',
   'Continuing (periodic) franchise fees based on the franchisee''s revenue are:',
   'Capitalized and amortized over the franchise term', 'Added to the cost of the franchise intangible', 'Expensed in the period the related revenue is earned', 'Charged against the initial franchise fee liability',
   2, 'The initial franchise fee is capitalized as an intangible asset; continuing fees are payments for ongoing services rendered each period and are expensed as incurred against the related revenue.', 1),
  ('FAR', 'Intangibles & Investment Property',
   'A patent with a remaining legal life of 15 years is expected to generate cash flows for only 8 more years. The patent should be amortized over:',
   '15 years', '8 years', '20 years', 'The average of the legal and useful lives',
   1, 'An intangible asset is amortized over the shorter of its useful (economic) life and its legal life — here, 8 years. Legal life sets only the maximum.', 1),
  ('FAR', 'Intangibles & Investment Property',
   'Which of the following is NOT investment property under PAS 40?',
   'Land held for long-term capital appreciation', 'Land held for a currently undetermined future use', 'A building leased out under an operating lease', 'Property held for sale in the ordinary course of business',
   3, 'Property held for sale in the ordinary course of business is inventory (PAS 2). Land for appreciation, land with undetermined use, and buildings leased out under operating leases are all investment property.', 1),
  ('FAR', 'Intangibles & Investment Property',
   'An entity that adopts the cost model for its investment property:',
   'Need not determine the property''s fair value', 'Must nevertheless disclose the fair value of the investment property', 'Must transfer the property to PPE', 'Recognizes fair value changes in OCI',
   1, 'Even under the cost model, PAS 40 requires disclosure of the fair value of investment property (with limited exceptions when fair value cannot be measured reliably).', 2),
  ('FAR', 'Intangibles & Investment Property',
   'When an investment property carried under the fair value model becomes owner-occupied, its deemed cost for subsequent accounting under PAS 16 is:',
   'Its original cost', 'Its carrying amount under the cost model', 'Its fair value at the date of change in use', 'Its value in use at the date of transfer',
   2, 'On transfer from investment property at fair value to owner-occupied property, the property''s deemed cost is its fair value at the date of the change in use; PAS 16 then applies prospectively.', 3),
  ('FAR', 'Investments in Debt & Equity Securities',
   'Significant influence over an investee is presumed to exist when the investor holds, directly or indirectly:',
   '20% or more of the voting power of the investee, unless it can be clearly demonstrated otherwise', 'Any amount of preference shares', '10% or more of the investee''s total assets', 'More than half of the investee''s board seats in all cases',
   0, 'PAS 28 presumes significant influence at 20% or more of voting power (rebuttable), and presumes its absence below 20% (also rebuttable by evidence such as board representation or participation in policy-making).', 1),
  ('FAR', 'Investments in Debt & Equity Securities',
   'On disposal of financial assets measured at FVOCI, the cumulative gain or loss in OCI is:',
   'Always transferred to profit or loss', 'Always transferred directly to retained earnings', 'Reclassified to profit or loss for debt instruments, but transferred within equity (never to profit or loss) for equity investments', 'Left permanently in the OCI reserve',
   2, 'Recycling applies only to FVOCI debt instruments. For equity investments designated at FVOCI, cumulative fair value changes are never reclassified to profit or loss; they may be transferred to retained earnings within equity.', 2),
  ('FAR', 'Investments in Debt & Equity Securities',
   'Bonds with face value of P5,000,000 and a nominal rate of 8% were purchased for P4,600,000 to yield 10%, and are held to collect contractual cash flows. The carrying amount at the end of the first year is:',
   'P4,600,000', 'P4,660,000', 'P4,700,000', 'P5,000,000',
   1, 'Interest income = P4,600,000 × 10% = P460,000; cash received = P5,000,000 × 8% = P400,000; discount amortization = P60,000. Carrying amount = P4,600,000 + P60,000 = P4,660,000.', 2),
  ('FAR', 'Investments in Debt & Equity Securities',
   'Interest income on a debt investment measured at FVOCI is computed using:',
   'The nominal rate applied to face value', 'The nominal rate applied to fair value', 'The effective rate applied to the fair value at each reporting date', 'The effective interest method, exactly as if the asset were measured at amortized cost',
   3, 'FVOCI debt instruments recognize interest income, impairment, and FX in profit or loss exactly as amortized-cost assets do; only the residual fair value changes go to OCI. This is why disposal triggers recycling.', 3),
  ('FAR', 'Investments in Debt & Equity Securities',
   'When bonds are purchased between interest payment dates, the accrued interest paid to the seller is:',
   'Included in the cost of the investment', 'Recorded separately and offset against the first interest collection', 'Expensed immediately', 'Credited to interest income at acquisition',
   1, 'Accrued interest purchased is not part of the bond''s cost; it is recorded as accrued interest receivable (or a charge to interest income) and recovered from the first coupon received.', 2),
  ('FAR', 'Investments in Debt & Equity Securities',
   'An entity''s portfolio of trading equity securities cost P2,000,000 and has a year-end fair value of P2,300,000. The entity should report:',
   'A P300,000 unrealized gain in other comprehensive income', 'No gain until the securities are sold', 'A P300,000 unrealized gain in profit or loss', 'A P300,000 credit directly to retained earnings',
   2, 'Trading securities are measured at FVPL: the P300,000 increase in fair value is an unrealized gain recognized in profit or loss in the current period.', 1),
  ('FAR', 'Investments in Debt & Equity Securities',
   'On acquiring an associate, the excess of the acquisition cost over the investor''s share of the fair value of identifiable net assets, attributable to a depreciable asset, is:',
   'Amortized over the asset''s remaining life, reducing the investor''s share of the associate''s profit', 'Recognized immediately as an expense', 'Recognized as a separate goodwill asset in the investor''s statement of financial position', 'Ignored under the equity method',
   0, 'Fair value differentials on depreciable assets are amortized against equity-method income over the asset''s remaining life. (Any residual excess is implicit goodwill, included in the investment''s carrying amount and not separately recognized or amortized.)', 3),
  ('FAR', 'Investments in Debt & Equity Securities',
   'When an investor''s share of an associate''s losses equals or exceeds its interest in the associate, the investor:',
   'Recognizes a liability for all further losses', 'Continues recognizing losses, reporting a negative investment balance', 'Must dispose of the investment', 'Discontinues recognizing further losses, unless it has incurred legal or constructive obligations or made payments on behalf of the associate',
   3, 'Equity-method losses stop at zero carrying amount (including long-term interests forming part of the net investment). Further losses are recognized only to the extent of obligations or payments made on the associate''s behalf.', 2),
  ('FAR', 'Investments in Debt & Equity Securities',
   'When an investor loses significant influence over an associate, any retained interest is:',
   'Carried over at its equity-method carrying amount', 'Remeasured at fair value, with the difference from carrying amount included in the gain or loss on disposal in profit or loss', 'Transferred to OCI at carrying amount', 'Written down to zero',
   1, 'On loss of significant influence, the equity method ceases: the retained interest is remeasured to fair value (its deemed cost as a financial asset), and the total gain or loss — including the remeasurement — goes to profit or loss.', 2),
  ('FAR', 'Investments in Debt & Equity Securities',
   'An associate has outstanding cumulative preference shares held by parties other than the investor. In computing its share of the associate''s profit, the investor deducts:',
   'Preference dividends only when declared', 'Preference dividends only when paid', 'One year''s preference dividends, whether or not declared', 'Nothing, because the investor holds only ordinary shares',
   2, 'For cumulative preference shares, the investor computes its share of profit after deducting the preference dividends for the period whether or not declared; for noncumulative shares, only when declared.', 3),
  ('FAR', 'Investments in Debt & Equity Securities',
   'Cash dividends on equity securities measured at FVPL are recognized as income:',
   'When the entity''s right to receive payment is established', 'When the dividend is received in cash', 'Ratably over the holding period', 'As a reduction of the investment''s carrying amount',
   0, 'Dividend income is recognized when the right to receive payment is established (generally the date of declaration / record), it is probable the benefits will flow, and the amount is measurable.', 1),
  ('FAR', 'Investments in Debt & Equity Securities',
   'Share dividends of the same class received on an equity investment are:',
   'Recognized as dividend income at fair value', 'Recognized as dividend income at par value', 'Credited to OCI', 'Not recognized as income; a memorandum entry is made and cost per share decreases',
   3, 'Share dividends are not income — the investor''s proportionate interest is unchanged. Only a memo entry is made; the original cost is spread over more shares, reducing cost per share.', 1),
  ('FAR', 'Leases',
   'A lessee recognized an initial lease liability of P3,790,800 on a five-year lease with annual year-end payments of P1,000,000 and a 10% implicit rate. Interest expense for the first year is:',
   'P316,988', 'P379,080', 'P500,000', 'P1,000,000',
   1, 'Interest = carrying amount × implicit rate = P3,790,800 × 10% = P379,080. The P1,000,000 payment is split between this interest and a P620,920 reduction of the liability, leaving P3,169,880.', 2),
  ('FAR', 'Leases',
   'A lessee depreciates a right-of-use asset over the useful life of the underlying asset (rather than the lease term) when:',
   'The lease is for twelve months or less', 'The underlying asset is of low value', 'The lease payments are variable', 'Ownership transfers to the lessee by the end of the term, or the lessee is reasonably certain to exercise a purchase option',
   3, 'Depreciation normally covers the shorter of the lease term and the asset''s useful life; the full useful life is used only when ownership will transfer or a purchase option is reasonably certain of exercise.', 2),
  ('FAR', 'Leases',
   'A four-year lease requires payments of P500,000 at the beginning of each year, starting at commencement. The implicit rate is 8% (PV of an ordinary annuity of 1 at 8% for 3 periods = 2.5771). Immediately after the first payment, the lease liability is:',
   'P1,288,550', 'P1,500,000', 'P1,788,550', 'P2,000,000',
   0, 'With an annuity due, the first payment occurs at commencement, leaving three payments to discount: P500,000 × 2.5771 = P1,288,550. The right-of-use asset starts at P1,788,550 (the liability plus the payment made at commencement).', 3),
  ('FAR', 'Leases',
   'A lessor grants a five-year operating lease with no rent in the first year and P500,000 per year for the remaining four years. Rental income in the first year is:',
   'P0', 'P400,000', 'P500,000', 'P2,000,000',
   1, 'Operating lease income is recognized on a straight-line basis over the lease term unless another systematic basis is more representative: total rentals of P2,000,000 ÷ 5 years = P400,000 per year, with a corresponding rent receivable in Year 1.', 2),
  ('FAR', 'Leases',
   'In a finance lease, the difference between the lessor''s gross investment in the lease and its net investment represents:',
   'The unguaranteed residual value', 'Initial direct costs', 'Unearned finance (interest) income', 'The underlying asset''s residual fair value',
   2, 'Gross investment is the undiscounted lease payments plus unguaranteed residual value; net investment is their present value. The difference is unearned finance income, recognized over the term to produce a constant periodic return.', 2),
  ('FAR', 'Leases',
   'In a sale-and-leaseback where the transfer qualifies as a sale under PFRS 15, the seller-lessee recognizes a gain:',
   'Equal to the full excess of the sale price over carrying amount', 'In full, deferred and amortized over the leaseback term', 'Of zero, in all cases', 'Only for the portion of the gain that relates to the rights transferred to the buyer-lessor',
   3, 'The seller-lessee retains a right of use, so only the gain attributable to the rights actually transferred to the buyer is recognized; the portion relating to the retained right of use is embedded in the measurement of the ROU asset.', 3),
  ('FAR', 'Leases',
   'Initial direct costs incurred by a lessor in negotiating an operating lease are:',
   'Added to the carrying amount of the underlying asset and expensed over the lease term on the same basis as the lease income', 'Expensed immediately', 'Charged against unearned interest income', 'Recognized as a separate intangible asset',
   0, 'For operating leases, the lessor capitalizes initial direct costs as part of the underlying asset''s carrying amount and recognizes them as expense over the term on the same basis as rental income.', 2),
  ('FAR', 'Leases',
   'The low-value asset exemption under PFRS 16 is assessed:',
   'Based on the asset''s value relative to the lessee''s total assets', 'Based on materiality to the lessee''s financial statements', 'On an absolute basis, based on the value of the asset when new, regardless of the lessee''s size', 'Only for leases shorter than twelve months',
   2, 'Low value is an absolute notion judged on the asset''s value when new (e.g., tablets, small office furniture) — independent of the lessee''s size or materiality. The election is made lease-by-lease; the short-term exemption is a separate election by class.', 2)
)
insert into public.questions (topic_id, stem, choices, correct_index, explanation, difficulty)
select t.id, q.stem, jsonb_build_array(q.a, q.b, q.c, q.d), q.correct_index, q.explanation, q.difficulty
from q join t on t.code = q.subject_code and lower(t.name) = lower(q.topic)
where not exists (select 1 from public.questions x where x.stem = q.stem);
