-- Generated from content/far-batch-002.csv by scripts/csv-to-seed-sql.mjs — do not edit by hand.
-- Idempotent: skips any question whose stem already exists.
with t as (
  select tp.id, tp.name, s.code from public.topics tp
  join public.subjects s on s.id = tp.subject_id
),
q(subject_code, topic, stem, a, b, c, d, correct_index, explanation, difficulty) as (values
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Under the 2018 Conceptual Framework, an asset is defined as:',
   'A resource owned by the entity from which future economic benefits are certain to flow', 'A present economic resource controlled by the entity as a result of past events', 'Any expenditure expected to benefit future periods', 'A right that has produced economic benefits for the entity in past periods',
   1, 'The 2018 Framework defines an asset as a present economic resource controlled by the entity as a result of past events, where an economic resource is a right that has the potential to produce economic benefits. Neither ownership nor certainty of benefits is required.', 1),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Under the 2018 Conceptual Framework, an element is recognized in the financial statements when:',
   'Recognition provides users with relevant information and a faithful representation of the element', 'It is probable that future economic benefits will flow and the cost can be measured reliably', 'Cash relating to the element has been received or paid', 'Management judges the item to be material to the entity',
   0, 'The 2018 Framework replaced the old probability and reliable-measurement criteria: an element is recognized when recognition provides relevant information and a faithful representation, subject to the cost constraint.', 2),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Which of the following is a current value measurement basis under the Conceptual Framework?',
   'Historical cost', 'Amortized cost', 'Fair value', 'Transaction price at initial recognition',
   2, 'Current value bases include fair value, value in use (fulfilment value for liabilities), and current cost. Historical cost and measures derived from it, such as amortized cost, are historical cost bases.', 2),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Information is material if:',
   'It exceeds 5% of total assets', 'It relates to a related party', 'Its amount is precise and verifiable', 'Omitting, misstating or obscuring it could reasonably be expected to influence the decisions of primary users',
   3, 'Materiality is an entity-specific aspect of relevance: information is material if omitting, misstating, or obscuring it could influence primary users'' decisions based on the financial statements. There is no fixed quantitative threshold.', 1),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Under the Conceptual Framework, prudence is described as:',
   'The exercise of caution when making judgments under uncertainty, without allowing deliberate understatement of assets or income', 'The deliberate understatement of assets and income to protect creditors', 'Recording probable losses but never probable gains', 'A justification for creating hidden reserves',
   0, 'Prudence supports neutrality: it is the exercise of caution under conditions of uncertainty. It does not permit deliberate understatement of assets or income or overstatement of liabilities or expenses, which would make information non-neutral.', 2),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Which of the following is NOT a component of a complete set of financial statements under PAS 1?',
   'Statement of changes in equity', 'Notes comprising material accounting policy information', 'A report of the board of directors on enterprise performance', 'Comparative information in respect of the preceding period',
   2, 'A complete set comprises the statement of financial position, statement(s) of profit or loss and OCI, statement of changes in equity, statement of cash flows, notes, and comparative information. Directors'' reports and similar reviews are outside the financial statements.', 1),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Which of the following is an adjusting event after the reporting period under PAS 10?',
   'A decline in the fair value of investments between the reporting date and the date the FS are authorized for issue', 'The bankruptcy of a customer occurring after the reporting period, on an account receivable existing at the reporting date', 'A business combination completed after the reporting period', 'Destruction of a major plant by fire after the reporting period',
   1, 'A customer''s bankruptcy after the reporting period normally confirms that a loss already existed on the receivable at the reporting date, so the allowance is adjusted. The other events arose after the reporting date and are non-adjusting (disclosed if material).', 2),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Dividends declared by the board after the reporting period but before the financial statements are authorized for issue are:',
   'Recognized as a liability at the reporting date', 'Deducted directly from retained earnings at the reporting date', 'Recognized as an expense of the current period', 'Not recognized as a liability at the reporting date, but disclosed',
   3, 'Under PAS 10, there is no present obligation at the reporting date for dividends declared afterward, so no liability is recognized. The declaration is disclosed as a non-adjusting event.', 1),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'A change in the estimated useful life of a depreciable asset is accounted for:',
   'Prospectively, in the period of change and future periods', 'Retrospectively, by restating prior years'' depreciation', 'By adjusting the opening balance of retained earnings', 'As a correction of a prior period error',
   0, 'A revision of useful life is a change in accounting estimate under PAS 8, recognized prospectively by depreciating the remaining carrying amount over the revised remaining life. No restatement is made.', 1),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'A material prior period error discovered in the current period is corrected by:',
   'Including the correction in the current period''s profit or loss', 'Prospective application over the current and future periods', 'Retrospective restatement, adjusting the opening balances of the earliest prior period presented', 'Disclosure only, without changing any reported amounts',
   2, 'PAS 8 requires retrospective restatement of material prior period errors: comparative amounts are restated and, if the error precedes the earliest period presented, opening balances of assets, liabilities and equity of that period are restated.', 2),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'An entity may change an accounting policy only when the change:',
   'Is approved by the entity''s external auditor', 'Is required by a PFRS, or results in reliable and more relevant information', 'Will increase reported profit for the period', 'Has been ratified by the shareholders',
   1, 'PAS 8 permits a voluntary change in accounting policy only if it results in reliable and more relevant information; otherwise a change must be required by a PFRS. Changes are applied retrospectively unless transitional provisions or impracticability dictate otherwise.', 2),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Which of the following is recognized in other comprehensive income?',
   'Unrealized gain on financial assets held for trading', 'Increase in revaluation surplus on property, plant and equipment', 'Gain on sale of equipment', 'Impairment loss on inventories',
   1, 'Revaluation surplus movements are an OCI component under PAS 16. Trading gains, disposal gains on PPE, and inventory write-downs are all recognized in profit or loss.', 1),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Which item of other comprehensive income may be reclassified to profit or loss in a subsequent period?',
   'Remeasurements of defined benefit plans', 'Changes in revaluation surplus', 'Gains on equity investments designated at FVOCI', 'Exchange differences on translating a foreign operation',
   3, 'Translation differences are reclassified to profit or loss on disposal of the foreign operation. Defined-benefit remeasurements, revaluation surplus and FVOCI-equity gains are never recycled to profit or loss (they may be transferred within equity).', 3),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Faithful representation requires that financial information be:',
   'Complete, neutral and free from error', 'Relevant, comparable and timely', 'Conservative, prudent and verifiable', 'Precise, certain and objective',
   0, 'A faithful representation is complete, neutral, and free from error. Free from error does not mean perfectly accurate — estimates can faithfully represent if properly described and determined.', 1),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Under the physical capital maintenance concept, profit is earned only if:',
   'Net assets at year-end exceed net assets at the beginning, measured at historical cost', 'Total equity increased during the period from any source', 'The physical productive capacity of the entity at year-end exceeds that at the beginning, after excluding owner transactions', 'Revenue exceeds expenses measured at nominal monetary amounts',
   2, 'Physical capital maintenance defines profit as the increase in physical productive capacity (operating capability) over the period, excluding contributions from and distributions to owners, and requires the current cost basis of measurement.', 3),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Under the 2018 Conceptual Framework, income is defined as:',
   'Inflows of cash and cash equivalents during the period', 'Revenue arising from the ordinary course of business activities only', 'Any credit adjustment to retained earnings', 'Increases in assets, or decreases in liabilities, that result in increases in equity, other than contributions from holders of equity claims',
   3, 'Income encompasses both revenue and gains: increases in assets or decreases in liabilities that increase equity, excluding contributions from equity holders. Cash receipt is not required.', 2),
  ('FAR', 'Cash & Cash Equivalents',
   'An entity''s records show: cash on hand P50,000 (including a customer''s postdated check of P10,000), demand deposit P200,000, payroll fund P30,000, and a bond sinking fund of P100,000 for bonds maturing in five years. Cash to be reported in the current assets section is:',
   'P270,000', 'P280,000', 'P370,000', 'P380,000',
   0, 'Cash = (P50,000 − P10,000 postdated check, which remains a receivable) + P200,000 demand deposit + P30,000 payroll fund = P270,000. The sinking fund follows the related liability''s classification — noncurrent investment for bonds due in five years.', 2),
  ('FAR', 'Cash & Cash Equivalents',
   'At year-end, an entity had drawn and recorded checks that had not yet been released to payees. For financial reporting purposes, these undelivered checks should be:',
   'Ignored, since the checks have been recorded', 'Deducted from the cash balance and disclosed', 'Added back to the cash balance, with the corresponding liabilities restored', 'Treated as outstanding checks in the bank reconciliation',
   2, 'An undelivered (unreleased) check is not a payment — the entity still controls the cash. The entry recording the disbursement is reversed: cash is restored and the liability re-established.', 2),
  ('FAR', 'Cash & Cash Equivalents',
   'A bank overdraft should generally be reported as:',
   'Part of cash and cash equivalents in all cases', 'A current liability, unless it can be offset against a positive balance in another account with the same bank', 'A deduction from accounts receivable', 'A noncurrent liability',
   1, 'Overdrafts are generally current liabilities. Offsetting is acceptable when the entity has another account in the same bank with an available balance (the bank has a right of offset). Under PAS 7, overdrafts repayable on demand that form an integral part of cash management may be included in cash equivalents for cash flow purposes.', 2),
  ('FAR', 'Cash & Cash Equivalents',
   'The primary purpose of a proof of cash (four-column reconciliation) is to:',
   'Compute the correct petty cash balance', 'Estimate cash to be collected from customers', 'Reconcile only the year-end balances of book and bank', 'Detect unrecorded items and discrepancies in cash receipts and disbursements between two reconciliation dates',
   3, 'A proof of cash reconciles beginning balances, receipts, disbursements, and ending balances per book and per bank, exposing errors or irregularities in receipts and disbursements that a single-date reconciliation would miss.', 1),
  ('FAR', 'Cash & Cash Equivalents',
   'A petty cash fund has an imprest balance of P10,000. At year-end the fund contains currency and coins of P2,500, paid vouchers for P6,800, and an employee IOU of P500. The cash shortage is:',
   'P200', 'P700', 'P1,200', 'P7,500',
   0, 'Accounted items = P2,500 + P6,800 + P500 = P9,800 against the P10,000 imprest balance, leaving a P200 shortage charged to a cash short or over account (or a receivable from the custodian).', 2),
  ('FAR', 'Cash & Cash Equivalents',
   'Which of the following qualifies as a cash equivalent?',
   'A six-month treasury bill purchased at the start of its term', 'Redeemable preference shares acquired three months before their specified redemption date', 'Equity securities held for trading', 'A money market placement with a term of one year',
   1, 'Cash equivalents are short-term, highly liquid investments with original maturities of three months or less from acquisition date. Redeemable preference shares acquired close to redemption meet this; ordinary equity securities have no maturity.', 2),
  ('FAR', 'Cash & Cash Equivalents',
   'A compensating balance agreement that does NOT legally restrict the withdrawal of funds should be:',
   'Excluded from cash and reported as a receivable from the bank', 'Reported as a noncurrent investment', 'Offset against the related borrowing', 'Included in cash, with disclosure of the arrangement in the notes',
   3, 'If the compensating balance is not legally restricted, the funds remain available and are included in cash; the arrangement is disclosed. Only legally restricted balances are segregated from cash.', 2),
  ('FAR', 'Cash & Cash Equivalents',
   'An entity''s book balance is P300,000. The bank statement reveals a credit memo of P50,000 for a note collected by the bank, a service charge of P1,000, and a customer NSF check of P9,000. The adjusted cash balance is:',
   'P240,000', 'P260,000', 'P340,000', 'P360,000',
   2, 'Adjusted book balance = P300,000 + P50,000 note collected − P1,000 service charge − P9,000 NSF = P340,000. All three items are book reconciling items requiring adjusting entries.', 2),
  ('FAR', 'Receivables',
   'An entity estimates doubtful accounts at 1% of credit sales. Credit sales were P5,000,000 and the allowance for doubtful accounts had a P20,000 credit balance before adjustment. Doubtful accounts expense for the year is:',
   'P30,000', 'P50,000', 'P70,000', 'P100,000',
   1, 'Under the percentage-of-sales (income statement) approach, the expense is computed directly: 1% × P5,000,000 = P50,000. The existing allowance balance is ignored — it matters only under the aging or percentage-of-receivables approaches.', 2),
  ('FAR', 'Receivables',
   'Writing off a specific account against the allowance for doubtful accounts:',
   'Has no effect on the net realizable value of accounts receivable', 'Decreases the net realizable value of accounts receivable', 'Increases doubtful accounts expense', 'Decreases total current assets',
   0, 'The write-off reduces gross receivables and the allowance by the same amount, so net realizable value — and expense — are unaffected. The expense was recognized earlier when the allowance was established.', 1),
  ('FAR', 'Receivables',
   'The collection of an account previously written off under the allowance method:',
   'Increases doubtful accounts expense', 'Has no effect on the allowance for doubtful accounts', 'Increases the allowance for doubtful accounts', 'Increases net income in the period of collection',
   2, 'The recovery reinstates the account (debit AR, credit allowance) and records the collection (debit cash, credit AR). The net effect is an increase in cash and in the allowance; no income is recognized.', 2),
  ('FAR', 'Receivables',
   'An entity sold goods in exchange for a P1,000,000 three-year noninterest-bearing note when the market rate was 10% (PV factor of 1 at 10% for 3 periods = 0.7513). Interest income for the first year is:',
   'P0', 'P75,130', 'P100,000', 'P248,700',
   1, 'The note is initially recorded at P1,000,000 × 0.7513 = P751,300. First-year interest income under the effective interest method = P751,300 × 10% = P75,130, amortizing the discount toward face value.', 2),
  ('FAR', 'Receivables',
   'An entity sold used equipment and received a two-year note bearing 3% interest when the prevailing market rate for similar notes was 12%. The sale price (and initial measurement of the note) is best measured at:',
   'The face amount of the note', 'The face amount plus total interest at 3%', 'The maturity value of the note', 'The present value of all note cash flows discounted at 12%',
   3, 'When the stated rate is unreasonably low relative to the market rate, the note is initially measured at present value using the market (imputed) rate, which represents the cash price equivalent of the equipment sold.', 2),
  ('FAR', 'Receivables',
   'In a factoring arrangement, the factor''s holdback (amount withheld to cover expected sales returns and allowances) is reported by the seller as:',
   'A receivable from the factor', 'A loss on factoring', 'An offset against accounts payable', 'Interest expense of the period',
   0, 'The holdback is the seller''s residual claim collectible from the factor once returns and allowances are settled, so it is a receivable (commonly ''receivable from factor''), not an expense or loss.', 2),
  ('FAR', 'Receivables',
   'A P600,000, one-year note bearing 12% interest was discounted at a bank at 15% six months before maturity. The proceeds from discounting are:',
   'P600,000', 'P621,600', 'P636,000', 'P672,000',
   1, 'Maturity value = P600,000 + (P600,000 × 12%) = P672,000. Discount = P672,000 × 15% × 6/12 = P50,400. Proceeds = P672,000 − P50,400 = P621,600.', 3),
  ('FAR', 'Receivables',
   'When a note receivable is discounted with a bank on a without-recourse basis, the transaction is:',
   'A secured borrowing, with the note remaining on the books', 'A conditional sale requiring disclosure of a contingent liability', 'An outright sale of the note, with no contingent liability', 'Recorded only by a memorandum entry',
   2, 'Without recourse, the bank assumes the risk of nonpayment; the transferor derecognizes the note and recognizes a gain or loss, with no contingent liability. With recourse, the transfer is a conditional sale (contingent liability disclosed) or a secured borrowing.', 2),
  ('FAR', 'Receivables',
   'Loan origination fees received by a bank from a borrower are:',
   'Recognized as fee income when the loan is released', 'Credited directly to retained earnings', 'Recognized as income evenly over the loan term', 'Deducted from the initial carrying amount of the loan and recognized over the term as an adjustment of the effective yield',
   3, 'Origination fees are integral to the effective interest rate: they reduce the loan''s initial carrying amount and are amortized into interest income over the term, recalibrating the yield (direct origination costs have the opposite effect).', 3),
  ('FAR', 'Receivables',
   'Under the PFRS 9 simplified approach, the loss allowance for trade receivables without a significant financing component is measured at:',
   '12-month expected credit losses', 'An amount equal to actual write-offs during the period', '5% of outstanding receivables', 'Lifetime expected credit losses',
   3, 'The simplified approach — required for trade receivables without a significant financing component — always measures the allowance at lifetime expected credit losses, avoiding the need to track significant increases in credit risk.', 2),
  ('FAR', 'Receivables',
   'Customers'' accounts with credit balances at the reporting date (e.g., from overpayments or returns after payment) are:',
   'Reported as current liabilities', 'Netted against accounts receivable with debit balances', 'Ignored if individually immaterial', 'Reported as contra-assets',
   0, 'Credit balances in customers'' accounts represent obligations to deliver goods or refund cash, so they are reclassified and presented as current liabilities. Netting against other customers'' debit balances is improper offsetting.', 1),
  ('FAR', 'Receivables',
   'Under the net method of recording credit sales, sales discounts forfeited by customers who pay after the discount period are:',
   'Credited to sales revenue', 'Credited to accounts receivable', 'Recognized as other income', 'Ignored',
   2, 'Under the net method, sales and receivables are recorded at the net-of-discount amount. When a customer pays beyond the discount period, the forfeited discount is collected in excess of the recorded receivable and is recognized as other income.', 2),
  ('FAR', 'Inventories',
   'Merchandise with an invoice price of P1,000,000 was purchased subject to a 10% trade discount. The entity also paid freight-in of P20,000, non-refundable import duties of P30,000, and refundable value-added tax of P108,000. The cost of the inventory is:',
   'P900,000', 'P950,000', 'P1,058,000', 'P1,150,000',
   1, 'Cost of purchase = (P1,000,000 × 90%) + P20,000 freight + P30,000 import duties = P950,000. Trade discounts are deducted and recoverable taxes such as creditable VAT are excluded from cost.', 2),
  ('FAR', 'Inventories',
   'Which of the following is included in the cost of inventories under PAS 2?',
   'Storage costs of finished goods awaiting shipment', 'Abnormal amounts of wasted materials', 'Selling and distribution costs', 'Fixed production overhead allocated based on normal capacity',
   3, 'Conversion costs include systematically allocated fixed production overhead based on normal capacity. Storage of finished goods, abnormal waste, and selling costs are expensed when incurred.', 2),
  ('FAR', 'Inventories',
   'Which statement about the FIFO cost formula is correct?',
   'It produces the same ending inventory whether a periodic or perpetual system is used', 'It produces a higher ending inventory under the perpetual system than the periodic system', 'It assigns the most recent costs to cost of goods sold', 'It is prohibited for inventories that are ordinarily interchangeable',
   0, 'Under FIFO, the earliest costs always exit first regardless of when sales are recorded, so periodic and perpetual FIFO yield identical ending inventory and cost of goods sold. (It is weighted average that differs between systems.)', 2),
  ('FAR', 'Inventories',
   'An entity began the period with 200 units at P50, then purchased 300 units at P60 and 500 units at P66. It sold 600 units during the period. Under the weighted average (periodic) method, ending inventory is:',
   'P20,000', 'P24,400', 'P26,400', 'P27,000',
   1, 'Total cost = (200 × 50) + (300 × 60) + (500 × 66) = P61,000 for 1,000 units, or P61 per unit. Ending inventory = 400 units × P61 = P24,400.', 2),
  ('FAR', 'Inventories',
   'A fire destroyed an entity''s warehouse. Records show beginning inventory P500,000, purchases P2,500,000, and sales P3,000,000. The gross profit rate is 25% of sales. Goods costing P50,000 were saved from the fire. The estimated fire loss is:',
   'P550,000', 'P600,000', 'P700,000', 'P750,000',
   2, 'Cost of goods sold = 75% × P3,000,000 = P2,250,000. Estimated ending inventory = P500,000 + P2,500,000 − P2,250,000 = P750,000, less P50,000 salvaged = P700,000 fire loss.', 3),
  ('FAR', 'Inventories',
   'Under the conservative (conventional) retail inventory method, the cost-to-retail ratio is computed by:',
   'Including both net markups and net markdowns', 'Excluding both net markups and net markdowns', 'Including net markdowns but excluding net markups', 'Including net markups but excluding net markdowns',
   3, 'The conservative approach includes net markups but excludes net markdowns from the ratio''s denominator, producing a lower ratio and an ending inventory that approximates the lower of average cost and net realizable value.', 3),
  ('FAR', 'Inventories',
   'A reversal of a prior inventory write-down to net realizable value is:',
   'Recognized as a reduction of the inventory expense (cost of goods sold) in the period of reversal, limited to the amount of the original write-down', 'Recognized as revenue in the period of reversal', 'Credited directly to retained earnings', 'Prohibited under PAS 2',
   0, 'When NRV recovers, the write-down is reversed — but never above original cost — and the reversal reduces the amount of inventories recognized as an expense in the period it occurs.', 2),
  ('FAR', 'Inventories',
   'Raw materials held for use in production are written down below cost:',
   'Whenever their replacement cost declines below original cost', 'Whenever the supplier reduces its list price', 'Only when the finished products in which they will be incorporated are expected to be sold below cost', 'At each reporting date, to current replacement cost in all cases',
   2, 'Materials are not written down if the finished goods containing them are expected to sell at or above cost. When a write-down is required, replacement cost may be the best available measure of the materials'' NRV.', 3),
  ('FAR', 'Inventories',
   'Goods shipped to a consignee, plus the freight paid by the consignor to ship them, are reported as:',
   'Inventory of the consignee, including the freight', 'Inventory of the consignor, with the freight expensed as incurred', 'Inventory of the consignor, with the freight included in inventory cost', 'Sales revenue of the consignor upon shipment',
   2, 'Consigned goods remain the consignor''s inventory until sold by the consignee, and the freight to place them at the consignee''s location is a cost of bringing inventory to its present location, so it is inventoriable.', 2),
  ('FAR', 'Inventories',
   'An entity purchased two lots of inventory for a lump sum of P6,000,000. Lot A has a sales value of P2,000,000 and Lot B of P6,000,000. The cost allocated to Lot A is:',
   'P1,500,000', 'P2,000,000', 'P3,000,000', 'P4,500,000',
   0, 'Under the relative sales value method, Lot A receives P6,000,000 × (P2,000,000 ÷ P8,000,000) = P1,500,000. Allocating equally or by individual sales value alone would misstate cost.', 2),
  ('FAR', 'Inventories',
   'Which cost formula is NOT permitted by PAS 2?',
   'Specific identification', 'First-in, first-out', 'Last-in, first-out', 'Weighted average',
   2, 'PAS 2 permits specific identification (required for items not ordinarily interchangeable), FIFO, and weighted average. LIFO was eliminated and is prohibited.', 1),
  ('FAR', 'Inventories',
   'Goods purchased in transit at year-end (FOB shipping point) were recorded as purchases, but were excluded from the physical count and from ending inventory. The effect on the current year is:',
   'Net income is overstated', 'Cost of goods sold is understated', 'Working capital is unaffected', 'Cost of goods sold is overstated and net income is understated',
   3, 'Including the purchase but omitting the goods from ending inventory inflates cost of goods sold (beginning + purchases − understated ending), thereby understating both net income and current assets.', 2)
)
insert into public.questions (topic_id, stem, choices, correct_index, explanation, difficulty)
select t.id, q.stem, jsonb_build_array(q.a, q.b, q.c, q.d), q.correct_index, q.explanation, q.difficulty
from q join t on t.code = q.subject_code and lower(t.name) = lower(q.topic)
where not exists (select 1 from public.questions x where x.stem = q.stem);
