-- Generated from content/far-batch-004.csv by scripts/csv-to-seed-sql.mjs — do not edit by hand.
-- Idempotent: skips any question whose stem already exists.
with t as (
  select tp.id, tp.name, s.code from public.topics tp
  join public.subjects s on s.id = tp.subject_id
),
q(subject_code, topic, stem, a, b, c, d, correct_index, explanation, difficulty) as (values
  ('FAR', 'Liabilities & Provisions',
   'Gift certificates sold but not yet redeemed at the reporting date are reported as:',
   'Sales revenue of the period of sale', 'A contract liability until redeemed or until breakage is appropriately recognized', 'An appropriation of retained earnings', 'A contingent liability disclosed in the notes',
   1, 'Cash received for gift certificates creates an obligation to deliver goods — a contract liability under PFRS 15. Revenue is recognized on redemption, and expected breakage is recognized in proportion to the pattern of redemption.', 1),
  ('FAR', 'Liabilities & Provisions',
   'An entity offers one premium (costing P50) for every 10 product wrappers returned. It sold 100,000 products and expects 60% of wrappers to be redeemed. Wrappers actually redeemed during the year totaled 40,000. The estimated premium liability at year-end is:',
   'P100,000', 'P200,000', 'P300,000', 'P500,000',
   0, 'Expected redemptions = 100,000 × 60% = 60,000 wrappers = 6,000 premiums × P50 = P300,000 expense. Redeemed: 40,000 wrappers = 4,000 premiums × P50 = P200,000. Liability = P300,000 − P200,000 = P100,000.', 3),
  ('FAR', 'Liabilities & Provisions',
   'When bonds are issued between interest payment dates, the accrued interest collected from bondholders is:',
   'Recognized as interest income', 'Added to the carrying amount of the bonds', 'Credited to share premium', 'Credited to interest payable (or interest expense), to be offset against the first full interest payment',
   3, 'The issuer collects interest accrued since the last payment date because the first coupon pays a full period''s interest. The amount collected is a payable (or a credit to interest expense), not income or part of the bond''s issue price.', 2),
  ('FAR', 'Liabilities & Provisions',
   'Bonds with face value of P3,000,000 and unamortized discount of P120,000 were retired at 101. The retirement results in:',
   'A gain of P30,000', 'A loss of P30,000', 'A gain of P150,000', 'A loss of P150,000',
   3, 'Carrying amount = P3,000,000 − P120,000 = P2,880,000. Retirement price = P3,000,000 × 101% = P3,030,000. Loss = P3,030,000 − P2,880,000 = P150,000, recognized in profit or loss.', 2),
  ('FAR', 'Liabilities & Provisions',
   'Bonds with face value of P1,000,000 and a nominal rate of 8% payable annually were issued for P924,200 to yield 10%. Interest expense for the first year under the effective interest method is:',
   'P80,000', 'P92,420', 'P100,000', 'P107,580',
   1, 'Interest expense = carrying amount × effective rate = P924,200 × 10% = P92,420. Cash paid = P80,000; the P12,420 difference is discount amortization, raising the carrying amount to P936,620.', 2),
  ('FAR', 'Liabilities & Provisions',
   'An entity breached a long-term loan covenant on or before the reporting date, making the loan payable on demand. The loan is classified as noncurrent only if, on or before the reporting date:',
   'The entity expects to remedy the breach within six months', 'The entity has begun negotiations with the lender', 'The lender granted a grace period ending at least twelve months after the reporting date, within which the entity can rectify the breach', 'The lender has not yet demanded payment',
   2, 'Under PAS 1, the breach makes the liability current unless the lender agreed, by the reporting date, to a grace period of at least twelve months after the reporting date. A waiver obtained after the reporting date is a non-adjusting event.', 3),
  ('FAR', 'Liabilities & Provisions',
   'A currently maturing obligation that the entity refinanced on a long-term basis after the reporting date but before the financial statements were authorized for issue is classified as:',
   'A current liability', 'A noncurrent liability', 'Partly current and partly noncurrent', 'An off-balance-sheet item with note disclosure',
   0, 'Classification reflects rights existing at the reporting date. Refinancing completed after that date does not change the liability''s current classification; it is disclosed as a non-adjusting event.', 2),
  ('FAR', 'Liabilities & Provisions',
   'Which of the following costs is included in a restructuring provision under PAS 37?',
   'Costs of retraining the remaining staff', 'Marketing costs to rebuild the entity''s image', 'Costs of relocating continuing employees', 'Termination benefits for employees made redundant by the restructuring',
   3, 'A restructuring provision includes only direct expenditures necessarily entailed by the restructuring and not associated with ongoing activities. Retraining, relocation of continuing staff, and marketing relate to the future conduct of the business and are excluded.', 2),
  ('FAR', 'Liabilities & Provisions',
   'For an onerous contract, the provision is measured at:',
   'The total expected revenue under the contract', 'The lower of the cost of fulfilling the contract and the penalty or compensation from failing to fulfill it', 'The full remaining contract price', 'The unavoidable fixed overhead of the entity',
   1, 'The provision reflects the least net cost of exiting: the lower of the cost of fulfilling the contract and the cost (penalties or compensation) of failing to fulfill it. Any impairment of assets dedicated to the contract is recognized first.', 3),
  ('FAR', 'Liabilities & Provisions',
   'An entity has a recognized provision for a lawsuit and expects reimbursement from its insurer. The reimbursement is recognized:',
   'As a reduction of the provision', 'Only in the notes to the financial statements', 'As a separate asset when receipt is virtually certain, not exceeding the provision', 'As income when the claim is filed with the insurer',
   2, 'Reimbursements are recognized as a separate asset only when virtually certain, capped at the provision''s amount. In profit or loss, the expense may be presented net of the reimbursement; on the balance sheet, no offsetting of the asset and provision.', 2),
  ('FAR', 'Liabilities & Provisions',
   'A provision involving a large population of items (e.g., product warranties) is measured using:',
   'The expected value — probability-weighting all possible outcomes', 'The single most likely outcome only', 'The maximum possible outflow', 'The minimum amount of the range',
   0, 'For large populations, PAS 37 requires the expected value method, weighting each outcome by its probability. The individual most likely outcome is more relevant for a single obligation, adjusted for other possible outcomes.', 2),
  ('FAR', 'Liabilities & Provisions',
   'Under the cost model, a change in the estimated amount of a decommissioning (asset retirement) obligation due to revised cost estimates is:',
   'Recognized immediately in profit or loss', 'Recognized in other comprehensive income', 'Charged directly to retained earnings', 'Added to or deducted from the carrying amount of the related asset',
   3, 'Under IFRIC 1, changes in a decommissioning liability from revised estimates or discount rates adjust the related asset''s carrying amount under the cost model (subject to impairment and a floor of zero); periodic unwinding of the discount, in contrast, is a finance cost.', 3),
  ('FAR', 'Liabilities & Provisions',
   'An entity issued a P1,500,000 noninterest-bearing note payable due in three years for equipment (no cash price available). The market rate is 8% (PV factor of 1 at 8% for 3 periods = 0.7938). The note is initially recorded at:',
   'P1,190,700', 'P1,300,000', 'P1,388,890', 'P1,500,000',
   0, 'The note and the equipment are recorded at the note''s present value: P1,500,000 × 0.7938 = P1,190,700. The P309,300 discount is amortized to interest expense over three years using the effective interest method.', 2),
  ('FAR', 'Liabilities & Provisions',
   'Advances received from customers for goods to be delivered next year are reported as:',
   'Revenue of the current period', 'An offset against accounts receivable', 'A current liability until the goods are delivered', 'Deferred credits within equity',
   2, 'Customer advances create an obligation to perform — a contract liability, classified as current when delivery is expected within the normal operating cycle/twelve months. Revenue is recognized when control of the goods transfers.', 1),
  ('FAR', 'Liabilities & Provisions',
   'A contingent asset is recognized in the statement of financial position when:',
   'The inflow of benefits is probable', 'The realization of income is virtually certain, at which point it is no longer a contingent asset', 'Legal proceedings have commenced', 'Management is confident of a favorable outcome',
   1, 'Contingent assets are never recognized — they are disclosed when an inflow is probable. Once realization becomes virtually certain, the related asset is no longer contingent and recognition is appropriate.', 1),
  ('FAR', 'Liabilities & Provisions',
   'An entity paid salaries of P1,200,000 during the year. Accrued salaries payable were P100,000 at the beginning of the year and P150,000 at year-end. Salaries expense for the year is:',
   'P1,150,000', 'P1,200,000', 'P1,250,000', 'P1,350,000',
   2, 'Expense = cash paid − beginning accrual + ending accrual = P1,200,000 − P100,000 + P150,000 = P1,250,000. The P50,000 increase in the accrual represents expense incurred but not yet paid.', 2),
  ('FAR', 'Employee Benefits & Income Taxes',
   'Past service cost arising from a plan amendment is recognized:',
   'Immediately in profit or loss at the earlier of when the amendment occurs and when related restructuring costs are recognized', 'In OCI over the average remaining service period', 'Only to the extent the benefits are already vested', 'As an adjustment to retained earnings',
   0, 'PAS 19 (revised) eliminated deferral of past service cost: the full amount — vested or not — is expensed immediately when the amendment or curtailment occurs (or when related restructuring costs are recognized, if earlier).', 2),
  ('FAR', 'Employee Benefits & Income Taxes',
   'When a defined benefit plan is in surplus, the net defined benefit asset recognized is limited to:',
   'The fair value of plan assets', 'The full surplus in all cases', 'The asset ceiling — the present value of available refunds from the plan or reductions in future contributions', 'The accumulated remeasurement gains in OCI',
   2, 'A surplus is recognized only up to the asset ceiling: the present value of economic benefits available as refunds or reduced future contributions. The effect of the ceiling is a remeasurement recognized in OCI.', 3),
  ('FAR', 'Employee Benefits & Income Taxes',
   'Which of the following characterizes a defined contribution plan?',
   'The entity guarantees a specified retirement benefit based on final salary', 'The entity''s obligation is limited to the agreed contributions, with actuarial and investment risk falling on the employee', 'Actuarial assumptions are required to measure the entity''s obligation', 'Remeasurements are recognized in OCI',
   1, 'In a defined contribution plan, the entity''s legal or constructive obligation is limited to the amount it agrees to contribute; the employee bears the actuarial and investment risk. No actuarial valuation of the obligation is needed.', 1),
  ('FAR', 'Employee Benefits & Income Taxes',
   'An employee''s bonus is 10% of income after deducting the bonus but before deducting income tax. Income before bonus and tax is P4,400,000. The bonus is:',
   'P360,000', 'P400,000', 'P440,000', 'P484,000',
   1, 'B = 10% × (P4,400,000 − B); 1.1B = P440,000; B = P400,000. Check: income after bonus = P4,000,000 × 10% = P400,000.', 2),
  ('FAR', 'Employee Benefits & Income Taxes',
   'Termination benefits are recognized as a liability and expense at the earlier of:',
   'When the employees are identified and when the plan is budgeted', 'When the offer is communicated and when employees render one more year of service', 'When the benefits are paid and when the employees leave', 'When the entity can no longer withdraw the offer of the benefits and when it recognizes related restructuring costs under PAS 37',
   3, 'Termination benefits arise from termination, not service, so they are recognized at the earlier of the date the entity can no longer withdraw the offer and the date it recognizes the costs of a related PAS 37 restructuring.', 2),
  ('FAR', 'Employee Benefits & Income Taxes',
   'Plan assets of a defined benefit plan are measured at:',
   'Fair value', 'Amortized cost', 'Present value of expected contributions', 'Historical cost less impairment',
   0, 'Plan assets — qualifying insurance policies and assets held by the fund — are measured at fair value at each reporting date. They are netted against the present value of the defined benefit obligation to arrive at the net liability or asset.', 1),
  ('FAR', 'Employee Benefits & Income Taxes',
   'An entity reported pretax accounting income of P5,000,000, which included nondeductible expenses of P200,000, nontaxable income of P300,000, and was computed after book depreciation P500,000 lower than allowable tax depreciation. At a 25% tax rate, current tax expense is:',
   'P1,000,000', 'P1,100,000', 'P1,250,000', 'P1,475,000',
   1, 'Taxable income = P5,000,000 + P200,000 − P300,000 − P500,000 = P4,400,000; current tax = P4,400,000 × 25% = P1,100,000. The excess tax depreciation also creates a deferred tax liability of P125,000.', 2),
  ('FAR', 'Employee Benefits & Income Taxes',
   'Which of the following differences does NOT give rise to deferred tax?',
   'Accrued warranty expense deductible only when paid', 'Excess of tax depreciation over book depreciation', 'Revenue collected in advance, taxable on receipt', 'Interest income on government securities that is exempt from income tax',
   3, 'Tax-exempt income is a permanent difference — it never enters taxable income, so there is no future tax consequence and no deferred tax. The other items are temporary differences that reverse in future periods.', 2),
  ('FAR', 'Employee Benefits & Income Taxes',
   'When the enacted tax rate changes, existing deferred tax assets and liabilities are:',
   'Left at the amounts computed using the old rate until reversal', 'Adjusted prospectively as the differences reverse', 'Remeasured using the new rate, with the effect recognized in profit or loss except for items previously recognized outside profit or loss', 'Derecognized in full',
   2, 'PAS 12 measures deferred taxes at the rates expected to apply on reversal, based on enacted or substantively enacted rates. A rate change remeasures the balances immediately, with the effect following the original item (P/L, OCI, or equity).', 2),
  ('FAR', 'Employee Benefits & Income Taxes',
   'An entity may offset deferred tax assets against deferred tax liabilities only when:',
   'The amounts are expected to reverse in the same period', 'The entity intends to settle on a net basis', 'It has a legally enforceable right to offset current tax amounts and the deferred taxes relate to income taxes levied by the same taxation authority', 'The net amount is immaterial',
   2, 'Offsetting requires both a legally enforceable right of offset for current taxes and that the deferred taxes relate to taxes levied by the same authority on the same taxable entity (or entities intending to settle net).', 3),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'An entity issued ordinary shares in exchange for a parcel of land. The transaction is best measured at:',
   'The par value of the shares issued', 'The fair value of the land received', 'The average market price of the shares over the past year', 'The carrying amount of the land in the seller''s books',
   1, 'Equity instruments issued for noncash consideration are measured by reference to the fair value of the goods received, unless that cannot be estimated reliably — in which case the fair value of the shares issued is used. Par value is a last resort.', 2),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'Subscriptions receivable on subscribed share capital, not collectible within one year, are presented as:',
   'A current asset', 'A noncurrent investment', 'An appropriation of retained earnings', 'A deduction from the related subscribed share capital in equity',
   3, 'Under Philippine practice, subscriptions receivable are shown as a deduction from subscribed share capital unless collectible within twelve months, in which case they may be shown as a current asset.', 2),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'When delinquent subscribed shares are sold at public auction, the shares are awarded to the bidder willing to pay the total amount due for:',
   'The smallest number of shares', 'The largest number of shares', 'The shares with the highest par value', 'Half of the subscribed shares',
   0, 'The highest bidder in a delinquency sale is the one willing to take the SMALLEST number of shares in exchange for paying the full balance due plus accrued interest and the costs of sale; remaining shares go to the delinquent subscriber.', 2),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'A 2-for-1 share split:',
   'Doubles total share capital', 'Requires a transfer from retained earnings to share capital', 'Is recorded by a memorandum entry only, halving par value per share with no change in total equity', 'Increases share premium',
   2, 'A split increases the number of shares and proportionately reduces par (or stated) value, leaving share capital and total equity unchanged — only a memo entry is needed. A share dividend, in contrast, capitalizes retained earnings.', 1),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'An entity declared noncash assets (equipment) as a property dividend. The dividend payable is measured at:',
   'The carrying amount of the equipment at declaration date', 'The par value of the shares held by the recipients', 'The original cost of the equipment', 'The fair value of the equipment, remeasured at each reporting date and at settlement, with changes recognized in equity',
   3, 'Under IFRIC 17, a dividend payable of noncash assets is measured at the fair value of the assets to be distributed, remeasured through equity until settlement; on settlement, the difference between the payable and the assets'' carrying amount goes to profit or loss.', 3),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'An appropriation of retained earnings for plant expansion:',
   'Sets aside cash for the expansion', 'Reduces total retained earnings and total equity', 'Reduces unappropriated retained earnings but leaves total retained earnings and total equity unchanged', 'Is recognized as a liability',
   2, 'An appropriation merely reclassifies retained earnings from unappropriated to appropriated to communicate restricted dividend capacity; it involves no cash segregation, no expense, and no change in total equity. It is reversed when the purpose is accomplished.', 1),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'An entity has 10,000 shares of 10% cumulative preference shares with P100 par (P1,000,000 total) and dividends in arrears for two years including the current year. If P500,000 in dividends is declared, the preference shareholders receive:',
   'P100,000', 'P200,000', 'P300,000', 'P500,000',
   1, 'Cumulative preference shares receive all arrears before ordinary shareholders: 10% × P1,000,000 × 2 years = P200,000. The remaining P300,000 goes to ordinary shareholders (the preference shares are not participating).', 2),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'Total shareholders'' equity is P5,500,000. Preference shares: 10,000 shares, P100 par, with a liquidation value of P110 per share and no dividends in arrears. With 100,000 ordinary shares outstanding, the book value per ordinary share is:',
   'P38', 'P41', 'P44', 'P55',
   2, 'Preference equity = 10,000 × P110 liquidation value = P1,100,000. Ordinary equity = P5,500,000 − P1,100,000 = P4,400,000 ÷ 100,000 shares = P44 per share.', 3),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'Convertible bonds were issued for total proceeds of P5,000,000. The fair value of similar bonds without the conversion feature is P4,600,000. At issuance, the amount credited to equity is:',
   'P0', 'P200,000', 'P400,000', 'P5,000,000',
   2, 'Compound instruments are split using the with-and-without method: the liability component is the fair value of a comparable bond without the equity feature (P4,600,000), and the residual P400,000 is the equity (conversion option) component. The split is never revised.', 2),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'An entity retired shares at a cost less than their original issue price. The difference is credited to:',
   'Share premium arising from retirement', 'Gain on retirement in profit or loss', 'Retained earnings', 'Treasury shares',
   0, 'Retirement cancels the share capital and related original share premium; when the retirement price is lower, the credit difference goes to share premium from retirement. A debit difference is charged against share premium then retained earnings — never profit or loss.', 2),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'Share appreciation rights payable in cash are accounted for as:',
   'An equity-settled share-based payment measured at grant date only', 'An expense only when exercised', 'A memorandum entry until exercise', 'A liability remeasured at fair value at each reporting date until settlement, with changes recognized in profit or loss',
   3, 'Cash-settled share-based payments create a liability measured at the fair value of the SARs, remeasured every reporting date and at settlement, with fair value changes in profit or loss — unlike equity-settled awards, which are fixed at grant-date fair value.', 2),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'A share option grant vests only if the entity''s share price reaches a specified level (a market condition). If employees complete the service period but the share price target is not met:',
   'Compensation expense is still recognized, because market conditions are reflected in the grant-date fair value and not subsequently trued up', 'All previously recognized expense is reversed', 'No expense is ever recognized for the grant', 'The expense is reclassified to OCI',
   0, 'Market conditions are incorporated into the grant-date fair value measurement; expense is recognized if service (and non-market) conditions are met, regardless of whether the market condition is achieved. Only failures of service/non-market conditions trigger reversal.', 3),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'An entity received cash from a customer, but the arrangement does not yet meet the PFRS 15 criteria for a contract (collectibility is not probable). The cash received is:',
   'Recognized as revenue immediately', 'Recognized as revenue using the installment method', 'Recognized as a liability until the criteria are met, the entity has no remaining obligations, or the contract is terminated', 'Credited to OCI',
   2, 'When contract criteria are unmet, consideration received is a liability. Revenue is recognized only when the criteria are subsequently met, or when the consideration is nonrefundable and the entity has fully performed or the contract is terminated.', 2),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'A promised good or service is distinct — and therefore a separate performance obligation — when:',
   'It is physically delivered separately from other goods', 'The customer can benefit from it on its own or with readily available resources, AND it is separately identifiable from other promises in the contract', 'It has a standalone selling price in any market', 'It is invoiced as a separate line item',
   1, 'Both criteria must be met: capable of being distinct (benefit on its own or with readily available resources) and distinct within the context of the contract (not an input to a combined output, not highly interdependent).', 2),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'An entity need not adjust the transaction price for a significant financing component when:',
   'The customer pays in cash rather than on credit', 'The financing rate is below the market rate', 'The contract price is fixed', 'At contract inception, the expected period between the transfer of goods and the customer''s payment is one year or less',
   3, 'PFRS 15 provides a practical expedient: no adjustment for the time value of money when the gap between performance and payment is expected to be one year or less at inception.', 2),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'In a bill-and-hold arrangement, the seller may recognize revenue before physical delivery when:',
   'The reason for the arrangement is substantive, the goods are separately identified as the customer''s, are ready for transfer, and the seller cannot use or redirect them', 'The customer has paid at least half of the price', 'The goods are expected to be shipped within the next quarter', 'The seller obtains insurance over the goods',
   0, 'Revenue requires the customer to have obtained control despite the seller''s physical possession — demonstrated by the four bill-and-hold criteria. Custodial services may be a separate performance obligation.', 3),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'An entity sells goods with a right of return. At the point of sale, the entity recognizes:',
   'Revenue for the full amount, with returns expensed when they occur', 'No revenue until the return period lapses', 'Revenue only for the consideration it expects to be entitled to, a refund liability for expected returns, and an asset for the right to recover the goods', 'A provision equal to the gross sales price',
   2, 'Expected returns are variable consideration: revenue is constrained to the expected entitled amount, a refund liability captures expected refunds, and a return asset (measured at former carrying amount less recovery costs) reflects the goods to be recovered.', 2),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'A consignor recognizes revenue on goods delivered to a consignee (dealer):',
   'Upon shipment to the consignee', 'When the consignee sells the goods to the end customer', 'When the consignment agreement is signed', 'Thirty days after delivery to the consignee',
   1, 'In a consignment, the dealer does not obtain control of the goods on delivery — the consignor retains control until sale to the end customer (or expiry of the consignment period), so revenue is deferred until that point.', 1),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'A franchise license that provides the customer the right to ACCESS the franchisor''s intellectual property as it evolves over the license period (e.g., an evolving brand and system) results in revenue recognized:',
   'At the point in time the license period begins', 'When the initial franchise fee is collected', 'Upon signing of the franchise agreement', 'Over time, throughout the license period',
   3, 'A right-to-access license (symbolic IP that the franchisor''s activities continue to affect) is a performance obligation satisfied over time. A right-to-use license (functional IP as it exists at grant) is satisfied at a point in time.', 2),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'An entity has satisfied a performance obligation but its right to the consideration is conditional on satisfying another performance obligation in the contract. The entity recognizes:',
   'A contract asset', 'An account receivable', 'Deferred revenue', 'An unbilled contingent asset disclosed only',
   0, 'A contract asset is a right to consideration conditioned on something other than the passage of time (e.g., further performance). Once the right becomes unconditional, it is reclassified to receivable.', 2),
  ('FAR', 'Cash Flows, Interim, Segment & Other Topics',
   'Sales for the year were P8,000,000. Accounts receivable were P1,200,000 at the beginning of the year and P1,500,000 at year-end. Cash collected from customers under the direct method is:',
   'P7,700,000', 'P8,000,000', 'P8,300,000', 'P9,500,000',
   0, 'Collections = sales + beginning AR − ending AR = P8,000,000 + P1,200,000 − P1,500,000 = P7,700,000. The P300,000 increase in receivables represents sales not yet collected.', 2),
  ('FAR', 'Cash Flows, Interim, Segment & Other Topics',
   'A noncurrent asset classified as held for sale under PFRS 5 is measured at:',
   'Fair value less costs to sell in all cases', 'The lower of its carrying amount and fair value less costs to sell, with depreciation ceasing', 'Carrying amount, with continued depreciation', 'Value in use',
   1, 'Held-for-sale assets are measured at the lower of carrying amount and fair value less costs to sell, presented separately as current, and are no longer depreciated while so classified.', 2),
  ('FAR', 'Cash Flows, Interim, Segment & Other Topics',
   'Under PAS 7, dividends PAID by a non-financial entity may be classified in the statement of cash flows as:',
   'Operating or investing activities', 'Investing activities only', 'Financing activities, or alternatively operating activities', 'Investing or financing activities',
   2, 'Dividends paid may be shown as financing (cost of obtaining financial resources) or as operating (to help users assess the ability to pay dividends from operating cash flows), applied consistently. Dividends received may be operating or investing.', 2)
)
insert into public.questions (topic_id, stem, choices, correct_index, explanation, difficulty)
select t.id, q.stem, jsonb_build_array(q.a, q.b, q.c, q.d), q.correct_index, q.explanation, q.difficulty
from q join t on t.code = q.subject_code and lower(t.name) = lower(q.topic)
where not exists (select 1 from public.questions x where x.stem = q.stem);
