-- Generated from content/far-batch-001.csv by scripts/csv-to-seed-sql.mjs — do not edit by hand.
-- Idempotent: skips any question whose stem already exists.
with t as (
  select tp.id, tp.name, s.code from public.topics tp
  join public.subjects s on s.id = tp.subject_id
),
q(subject_code, topic, stem, a, b, c, d, correct_index, explanation, difficulty) as (values
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Which enhancing qualitative characteristic enables users to identify and understand similarities in, and differences among, items?',
   'Verifiability', 'Timeliness', 'Comparability', 'Faithful representation',
   2, 'Comparability is the enhancing characteristic that lets users identify similarities and differences across entities and periods. Verifiability means independent observers could reach consensus; timeliness means information is available in time to influence decisions. Faithful representation is a fundamental, not enhancing, characteristic.', 1),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Financial statements are prepared on a going concern basis unless:',
   'Management intends to liquidate the entity or cease trading, or has no realistic alternative but to do so', 'The entity reported a net loss for the current year', 'The entity''s liabilities exceed its assets at the reporting date', 'The auditor expresses a qualified opinion',
   0, 'Under PAS 1, the going concern basis is abandoned only when management intends to liquidate or cease trading, or has no realistic alternative. A net loss or capital deficiency raises doubt but does not by itself require a liquidation basis.', 1),
  ('FAR', 'Conceptual Framework & FS Presentation',
   'Under PAS 1, assets and liabilities, or income and expenses, may be offset in the financial statements only when:',
   'The amounts are immaterial', 'They relate to the same counterparty', 'Offsetting is required or permitted by a PFRS', 'Management believes offsetting presents a fairer picture',
   2, 'PAS 1 prohibits offsetting unless it is required or permitted by another PFRS (e.g., PAS 32 criteria for financial instruments). Measuring assets net of valuation allowances, such as receivables net of allowance for doubtful accounts, is not offsetting.', 2),
  ('FAR', 'Cash & Cash Equivalents',
   'An entity shows a bank statement balance of P500,000 at year-end. Deposits in transit were P80,000 and outstanding checks were P120,000. The bank statement also reflects a service charge of P2,000 and a customer NSF check of P30,000, neither yet recorded in the books. The correct cash balance is:',
   'P430,000', 'P458,000', 'P460,000', 'P540,000',
   2, 'Adjusted bank balance = P500,000 + P80,000 deposits in transit − P120,000 outstanding checks = P460,000. The service charge and NSF check are book reconciling items — they adjust the book balance down to P460,000 but do not affect the computation from the bank side.', 2),
  ('FAR', 'Cash & Cash Equivalents',
   'A cash balance that is legally restricted as a compensating balance for a short-term borrowing should be:',
   'Included in cash and cash equivalents', 'Reported as a noncurrent investment', 'Offset against the related loan payable', 'Reported separately as a current asset',
   3, 'A legally restricted compensating balance is not available for general use, so it is excluded from cash and shown separately. Because the related loan is short-term, the restricted amount is a current asset; offsetting against the loan is prohibited.', 2),
  ('FAR', 'Cash & Cash Equivalents',
   'Under the imprest fund system, the journal entry to replenish the petty cash fund includes:',
   'A debit to Petty Cash Fund and a credit to Cash in Bank', 'A debit to the various expense accounts and a credit to Cash in Bank', 'A debit to the various expense accounts and a credit to Petty Cash Fund', 'A debit to Cash in Bank and a credit to Petty Cash Fund',
   1, 'Under the imprest system, the Petty Cash Fund account stays at its fixed balance. Expenses are recorded at replenishment by debiting the expense accounts and crediting Cash in Bank. The Petty Cash Fund account is touched only when the fund is established, increased, or decreased.', 1),
  ('FAR', 'Receivables',
   'Accounts receivable total P2,000,000 at year-end. The allowance for doubtful accounts has a credit balance of P40,000 before adjustment, and an aging schedule indicates a required allowance of P130,000. Doubtful accounts expense for the year is:',
   'P40,000', 'P90,000', 'P130,000', 'P170,000',
   1, 'Under the aging (balance sheet) approach, the required ending allowance is P130,000. With an existing credit balance of P40,000, the adjustment — and the expense — is P130,000 − P40,000 = P90,000. P170,000 would be correct only if the unadjusted allowance had a debit balance.', 2),
  ('FAR', 'Receivables',
   'An entity received a three-year noninterest-bearing promissory note in exchange for merchandise sold. The note has no cash price equivalent. It should initially be recognized at:',
   'Face amount', 'Face amount less unearned interest computed at the stated rate', 'Present value of future cash flows discounted at the prevailing market rate of interest', 'Net realizable value at the reporting date',
   2, 'A long-term noninterest-bearing note contains a significant financing component. It is initially measured at present value using an imputed market rate, and the discount is amortized to interest income over the term using the effective interest method.', 2),
  ('FAR', 'Receivables',
   'When accounts receivable are pledged as collateral security for a loan, the receivables:',
   'Remain on the borrower''s books, with the pledge disclosed', 'Are derecognized and a gain or loss is computed', 'Are transferred to a separate Pledged Receivables account and the loan is offset', 'Are written down to their net realizable value',
   0, 'Pledging is a general assignment of receivables as collateral; the borrower retains ownership, control, and collection. The receivables stay on the books and the arrangement is merely disclosed in the notes.', 1),
  ('FAR', 'Inventories',
   'At year-end an entity holds 1,000 units of inventory costing P500 per unit. The estimated selling price is P520 per unit and estimated costs to sell are P40 per unit. The inventory should be reported at:',
   'P440,000', 'P480,000', 'P500,000', 'P520,000',
   1, 'NRV = P520 − P40 = P480 per unit, which is below the P500 cost, so inventory is measured at NRV: 1,000 × P480 = P480,000. A write-down of P20,000 is recognized as an expense (or addition to cost of goods sold).', 2),
  ('FAR', 'Inventories',
   'Which of the following should be included in a buyer''s inventory at the reporting date?',
   'Goods purchased FOB destination, still in transit', 'Goods purchased FOB shipping point, still in transit', 'Goods held on consignment from a supplier', 'Goods sold FOB shipping point, shipped before year-end',
   1, 'Under FOB shipping point, title passes to the buyer upon shipment, so in-transit goods belong to the buyer. FOB destination goods in transit still belong to the seller; consigned goods belong to the consignor; and goods already sold and shipped FOB shipping point belong to the customer.', 1),
  ('FAR', 'Inventories',
   'At year-end, an entity has a noncancellable commitment to purchase raw materials next year at a fixed price, and the market price has fallen below the contract price. The entity should:',
   'Ignore the decline because no purchase has occurred', 'Disclose the commitment only, regardless of the price decline', 'Defer the loss until the goods are actually purchased', 'Recognize a loss and a liability for the excess of the contract price over market price',
   3, 'When a noncancellable purchase commitment becomes onerous because market price falls below the committed price, the expected loss is recognized immediately with a corresponding provision (estimated liability for purchase commitment), consistent with PAS 37.', 3),
  ('FAR', 'Property, Plant & Equipment',
   'An entity exchanged a machine for a delivery truck in a transaction with commercial substance. The machine had a carrying amount of P800,000 and a fair value of P950,000, and the entity paid cash of P100,000. The truck should be recorded at:',
   'P800,000', 'P900,000', 'P950,000', 'P1,050,000',
   3, 'With commercial substance, the asset received is measured at the fair value of the asset given up plus cash paid: P950,000 + P100,000 = P1,050,000. A gain of P150,000 (fair value less carrying amount of the machine) is recognized in profit or loss.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'A building with a cost of P5,000,000 and accumulated depreciation of P2,000,000 was revalued for the first time at a fair value of P4,200,000. The revaluation surplus to be recognized in other comprehensive income is:',
   'P0', 'P800,000', 'P1,200,000', 'P4,200,000',
   2, 'Carrying amount = P5,000,000 − P2,000,000 = P3,000,000. First-time revaluation increase = P4,200,000 − P3,000,000 = P1,200,000, credited to revaluation surplus through OCI since there is no previous revaluation decrease to reverse through profit or loss.', 2),
  ('FAR', 'Property, Plant & Equipment',
   'An entity borrowed P10,000,000 at 8% specifically to finance the construction of a qualifying asset for the entire current year. Pending use, idle funds were temporarily invested and earned P50,000. The borrowing cost to be capitalized for the year is:',
   'P50,000', 'P750,000', 'P800,000', 'P850,000',
   1, 'For specific borrowings, PAS 23 capitalizes actual borrowing costs incurred (P10,000,000 × 8% = P800,000) less investment income on the temporary investment of the funds (P50,000), giving P750,000.', 3),
  ('FAR', 'Intangibles & Investment Property',
   'Under PAS 38, an intangible asset arising from development is recognized when the entity can demonstrate all of the following, except:',
   'Technical feasibility of completing the asset', 'Intention and ability to complete and use or sell the asset', 'Probable future economic benefits and reliable measurement of cost', 'That the related expenditure was incurred after commercial production began',
   3, 'Development capitalization requires technical feasibility, intention and ability to complete and use/sell, probable economic benefits, availability of resources, and reliable cost measurement — all before commercial production. Costs after commercial production begins are operating costs, not development.', 2),
  ('FAR', 'Intangibles & Investment Property',
   'An intangible asset with an indefinite useful life is:',
   'Amortized over a maximum period of 20 years', 'Amortized over its expected useful life and tested for impairment when indicators exist', 'Not amortized, but tested for impairment at least annually', 'Expensed immediately because its life cannot be determined',
   2, 'Indefinite-life intangibles are not amortized. Instead, PAS 36 requires an impairment test at least annually and whenever there is an indication of impairment, plus an annual review of whether the indefinite-life assessment remains appropriate.', 1),
  ('FAR', 'Intangibles & Investment Property',
   'A parent leases a building to its subsidiary, which uses it as its head office. How is the building classified?',
   'Investment property in both the parent''s separate and the consolidated financial statements', 'Owner-occupied property in both the parent''s separate and the consolidated financial statements', 'Investment property in the parent''s separate financial statements, but owner-occupied property in the consolidated financial statements', 'Owner-occupied property in the parent''s separate financial statements, but investment property in the consolidated financial statements',
   2, 'From the parent''s separate-FS perspective, the building earns rentals and qualifies as investment property under PAS 40. From the group''s perspective, the property is occupied by a group member, so in the consolidated FS it is owner-occupied and accounted for under PAS 16.', 3),
  ('FAR', 'Investments in Debt & Equity Securities',
   'Transaction costs directly attributable to the acquisition of equity securities classified as fair value through profit or loss are:',
   'Expensed immediately in profit or loss', 'Capitalized as part of the initial cost of the investment', 'Recognized in other comprehensive income', 'Deferred and amortized over the holding period',
   0, 'Financial assets at FVPL are initially measured at fair value, and transaction costs are expensed outright. Capitalization of transaction costs applies to financial assets not at FVPL (e.g., FVOCI and amortized cost categories).', 1),
  ('FAR', 'Investments in Debt & Equity Securities',
   'An entity acquired 30% of an associate''s ordinary shares for P5,000,000. During the year, the associate reported net income of P2,000,000 and declared cash dividends of P500,000. The year-end carrying amount of the investment under the equity method is:',
   'P5,000,000', 'P5,150,000', 'P5,450,000', 'P5,600,000',
   2, 'Equity method: P5,000,000 + share in net income (30% × P2,000,000 = P600,000) − share in dividends (30% × P500,000 = P150,000) = P5,450,000. Dividends reduce the investment; they are not income under the equity method.', 2),
  ('FAR', 'Investments in Debt & Equity Securities',
   'Under PFRS 9, reclassification of debt investments between measurement categories is permitted:',
   'Whenever the fair value of the investment changes significantly', 'At each reporting date, at the entity''s option', 'Never, once the initial classification is made', 'Only when the entity changes its business model for managing financial assets, applied prospectively',
   3, 'Debt instruments are reclassified only when the entity changes its business model for managing financial assets — expected to be rare — and the reclassification is applied prospectively from the reclassification date. Equity investments and the FVO designation are never reclassified.', 2),
  ('FAR', 'Liabilities & Provisions',
   'A possible obligation arising from past events, whose existence will be confirmed by uncertain future events not wholly within the entity''s control, and whose likelihood of outflow is not remote, should be:',
   'Recognized as a provision', 'Disclosed as a contingent liability', 'Ignored until the outflow becomes certain', 'Recognized directly in retained earnings',
   1, 'A possible (not present) obligation is a contingent liability under PAS 37: it is not recognized but disclosed, unless the possibility of outflow is remote, in which case no disclosure is required.', 1),
  ('FAR', 'Liabilities & Provisions',
   'An entity sells goods with a one-year warranty and expects 5% of the 20,000 units sold during the year to require repairs averaging P200 per unit. Actual warranty costs paid during the year were P120,000. The warranty liability at year-end is:',
   'P80,000', 'P120,000', 'P200,000', 'P280,000',
   0, 'Estimated warranty provision = 20,000 × 5% × P200 = P200,000. Actual costs of P120,000 are charged against the provision, leaving a year-end liability of P200,000 − P120,000 = P80,000.', 2),
  ('FAR', 'Liabilities & Provisions',
   'When bonds are issued at a discount and interest is recognized using the effective interest method, periodic interest expense:',
   'Increases each period as the carrying amount increases', 'Decreases each period as the carrying amount increases', 'Stays constant and equals the cash interest paid', 'Equals the cash interest paid less discount amortization',
   0, 'For discount bonds, the carrying amount rises toward face value as the discount is amortized. Interest expense = carrying amount × effective rate, so expense increases each period and exceeds the cash interest paid by the amortization.', 2),
  ('FAR', 'Leases',
   'Which of the following situations would normally lead a lessor to classify a lease as a finance lease?',
   'The lease term covers an insignificant part of the asset''s economic life', 'The present value of lease payments is substantially all of the asset''s fair value', 'The asset is a standard model readily usable by other lessees', 'Ownership remains with the lessor and no purchase option exists',
   1, 'PFRS 16 lessor indicators of a finance lease include transfer of ownership, a reasonably certain purchase option, a lease term for the major part of the economic life, present value of payments amounting to substantially all of the fair value, and a specialized asset. Choice B is one of these indicators.', 2),
  ('FAR', 'Leases',
   'A lessee enters a five-year lease requiring payments of P1,000,000 at the end of each year. The interest rate implicit in the lease is 10% (PV of an ordinary annuity of 1 at 10% for 5 periods = 3.7908). The initial lease liability is:',
   'P3,000,000', 'P3,790,800', 'P4,168,880', 'P5,000,000',
   1, 'The lease liability is the present value of the remaining lease payments: P1,000,000 × 3.7908 = P3,790,800. The undiscounted P5,000,000 total ignores the time value of money.', 2),
  ('FAR', 'Leases',
   'Under PFRS 16, variable lease payments that depend on the lessee''s sales from the leased store are:',
   'Included in the lease liability at their expected amount', 'Included in the lease liability at their minimum guaranteed amount only', 'Excluded from the lease liability and recognized as expense when the sales occur', 'Capitalized as part of the right-of-use asset only',
   2, 'Variable payments linked to future sales or usage do not depend on an index or rate, so they are excluded from the lease liability and ROU asset. They are recognized in profit or loss in the period in which the triggering event (the sales) occurs.', 2),
  ('FAR', 'Employee Benefits & Income Taxes',
   'Under PAS 19, the components of defined benefit cost recognized in profit or loss are:',
   'Service cost and net interest on the net defined benefit liability or asset', 'Service cost only', 'Service cost, net interest, and remeasurements', 'Remeasurements only',
   0, 'Profit or loss takes service cost (current, past, and settlement gains/losses) and net interest computed on the net defined benefit liability (asset). Remeasurements — actuarial gains/losses, return on plan assets excluding net interest — go to OCI.', 2),
  ('FAR', 'Employee Benefits & Income Taxes',
   'At year-end, an asset has a carrying amount of P3,000,000 and a tax base of P2,400,000. The enacted tax rate is 25%. The entity should recognize:',
   'A deferred tax asset of P150,000', 'A deferred tax liability of P600,000', 'Current tax expense of P150,000', 'A deferred tax liability of P150,000',
   3, 'Carrying amount exceeding tax base on an asset creates a taxable temporary difference of P600,000, giving a deferred tax liability of P600,000 × 25% = P150,000. A deferred tax asset would arise if the tax base exceeded the carrying amount.', 2),
  ('FAR', 'Employee Benefits & Income Taxes',
   'An entity''s employees earn vacation leave that accumulates and vests (unused leave is paid on separation). The cost of unused vacation leave at year-end should be:',
   'Expensed only when employees actually take the vacation', 'Disclosed only, because the timing of use is uncertain', 'Recognized only if the entity has a formal vacation policy in writing', 'Accrued as a liability measured at the amount expected to be paid',
   3, 'Accumulating, vesting compensated absences are short-term employee benefits accrued as services are rendered, measured at the additional amount the entity expects to pay for the accumulated entitlement. Non-accumulating absences are expensed when taken.', 2),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'An entity reissued treasury shares at a price above their cost. The excess of the reissue price over cost is credited to:',
   'Share premium from treasury share transactions', 'Gain on sale of treasury shares in profit or loss', 'Retained earnings', 'Revaluation surplus',
   0, 'Transactions in an entity''s own shares never produce profit or loss. Reissuance above cost is credited to share premium — treasury shares; reissuance below cost is debited first against that share premium, then retained earnings.', 1),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'An entity declared a 10% share dividend when the fair value of its shares exceeded par value. Under Philippine practice for a small share dividend, retained earnings should be debited for the:',
   'Par value of the shares to be issued', 'Fair value of the shares at the date of issuance', 'Average carrying amount of equity per share', 'Fair value of the shares at the date of declaration',
   3, 'A share dividend of less than 20% is a small share dividend, capitalized at the fair value of the shares at the declaration date. Large share dividends (20% or more) are capitalized at par or stated value. Total equity is unchanged either way.', 2),
  ('FAR', 'Shareholders'' Equity & Share-Based Payment',
   'On January 1, an entity granted 100 share options to each of its 100 employees, vesting after three years of service. Grant-date fair value is P30 per option, and 10% of employees are expected to leave before vesting. Compensation expense for Year 1 is:',
   'P90,000', 'P100,000', 'P270,000', 'P300,000',
   0, 'Expense = options expected to vest × grant-date fair value × portion of vesting period elapsed: (100 × 100 × 90%) × P30 × 1/3 = 9,000 × P30 × 1/3 = P90,000. The estimate of forfeitures is revised each period until vesting.', 3),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'An online platform arranges the sale of goods owned and shipped by third-party merchants, earning a 15% fee on each sale. It never obtains control of the goods and the merchants set the prices. The platform should recognize revenue equal to:',
   'Its 15% fee, because it is acting as an agent', 'The gross amount paid by customers', 'The gross amount paid by customers less payment processing costs', 'Nothing until the merchant remits payment',
   0, 'The platform does not control the goods before transfer, does not set prices, and bears no inventory risk — it is an agent under PFRS 15. An agent recognizes as revenue only its fee or commission, not the gross transaction amount.', 2),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'An entity sells equipment bundled with two years of support services for P1,000,000. Sold separately, the equipment''s standalone selling price is P1,000,000 and the support''s is P250,000. Revenue allocated to the equipment upon delivery is:',
   'P200,000', 'P750,000', 'P800,000', 'P1,000,000',
   2, 'The transaction price is allocated by relative standalone selling prices: P1,000,000 × (P1,000,000 ÷ P1,250,000) = P800,000 to the equipment, and P200,000 to the support services recognized over the two-year period.', 2),
  ('FAR', 'Revenue Recognition (PFRS 15)',
   'Under PFRS 15, variable consideration (such as a performance bonus) is included in the transaction price:',
   'Always, at the maximum possible amount', 'Only when the consideration is actually received', 'Never, until the contract is completed', 'Only to the extent it is highly probable that a significant reversal of cumulative revenue will not occur',
   3, 'Variable consideration is estimated (expected value or most likely amount) but constrained: it enters the transaction price only to the extent it is highly probable that a significant revenue reversal will not occur when the uncertainty is resolved.', 2),
  ('FAR', 'Cash Flows, Interim, Segment & Other Topics',
   'An entity acquired equipment during the year by issuing its own ordinary shares to the supplier. In the statement of cash flows, this transaction is:',
   'Excluded from the statement and disclosed as a noncash investing and financing activity', 'Reported as an investing outflow and a financing inflow', 'Reported as an operating activity', 'Reported as a financing outflow only',
   0, 'PAS 7 excludes noncash investing and financing transactions from the statement of cash flows because no cash flows occur; they are disclosed elsewhere in the FS in a way that provides relevant information.', 1),
  ('FAR', 'Cash Flows, Interim, Segment & Other Topics',
   'Under PAS 34, income tax expense for an interim period is computed using:',
   'The statutory tax rate applied to interim pre-tax income', 'The best estimate of the weighted average annual effective income tax rate applied to interim pre-tax income', 'The prior year''s effective tax rate', 'Zero, because tax is assessed only annually',
   1, 'PAS 34 requires interim income tax expense to be accrued using the best estimate of the weighted average annual income tax rate expected for the full financial year, applied to the interim period''s pre-tax income.', 2),
  ('FAR', 'Cash Flows, Interim, Segment & Other Topics',
   'An entity reported profit of P1,000,000, depreciation of P200,000, an increase in accounts receivable of P150,000, a decrease in inventory of P50,000, and an increase in accounts payable of P80,000. Net cash provided by operating activities under the indirect method is:',
   'P980,000', 'P1,080,000', 'P1,180,000', 'P1,280,000',
   2, 'P1,000,000 + P200,000 depreciation − P150,000 AR increase + P50,000 inventory decrease + P80,000 AP increase = P1,180,000. Noncash expenses are added back; working capital increases in assets are deducted, increases in liabilities added.', 2)
)
insert into public.questions (topic_id, stem, choices, correct_index, explanation, difficulty)
select t.id, q.stem, jsonb_build_array(q.a, q.b, q.c, q.d), q.correct_index, q.explanation, q.difficulty
from q join t on t.code = q.subject_code and lower(t.name) = lower(q.topic)
where not exists (select 1 from public.questions x where x.stem = q.stem);
