-- Generated from content/mas-batch-002.csv by scripts/csv-to-seed-sql.mjs — do not edit by hand.
-- Idempotent: skips any question whose stem already exists.
with t as (
  select tp.id, tp.name, s.code from public.topics tp
  join public.subjects s on s.id = tp.subject_id
),
q(subject_code, topic, stem, a, b, c, d, correct_index, explanation, difficulty) as (values
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'A responsibility center whose manager is accountable for revenues, costs, and the assets invested in the segment is best described as a:',
   'Cost center', 'Profit center', 'Revenue center', 'Investment center',
   3, 'An investment center manager controls revenues, costs, and the level of invested assets; profit centers control only revenues and costs.', 1),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'A division reported sales of P5,000,000, operating income of P600,000, and average operating assets of P3,000,000. The division''s return on investment is:',
   '12%', '16.7%', '20%', '60%',
   2, 'ROI = P600,000 ÷ P3,000,000 = 20%. Equivalently, margin of 12% × asset turnover of 1.67 = 20%.', 2),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'A division earned operating income of P900,000 on average invested capital of P4,000,000. The required rate of return is 18%. Residual income is:',
   'P162,000', 'P180,000', 'P720,000', 'P738,000',
   1, 'Capital charge = P4,000,000 × 18% = P720,000. Residual income = P900,000 − P720,000 = P180,000.', 2),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'A division has a profit margin of 8% and an asset turnover of 2.5 times. Its return on investment is:',
   '3.2%', '10.5%', '20%', '32%',
   2, 'Under the DuPont decomposition, ROI = margin × turnover = 8% × 2.5 = 20%.', 2),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'Division S sells its only product to outside customers at P200 per unit and is operating at full capacity. Variable cost is P120 per unit. Division B wants to buy units internally. The minimum transfer price Division S should accept is:',
   'P80', 'P120', 'P200', 'P320',
   2, 'At full capacity the minimum transfer price = variable cost + lost contribution margin = P120 + (P200 − P120) = P200, which equals the outside market price.', 2),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'Division X has sufficient idle capacity to fill an internal order. Variable cost is P150 per unit, allocated fixed overhead is P40 per unit, and the outside market price is P260. The minimum transfer price Division X should accept is:',
   'P110', 'P150', 'P190', 'P260',
   1, 'With idle capacity there is no opportunity cost, so the minimum transfer price is the variable cost of P150; allocated fixed overhead is not incremental.', 2),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'A company reports earnings before interest and taxes of P2,000,000 and is subject to a 30% income tax rate. Invested capital is P9,000,000 and the weighted-average cost of capital is 10%. Economic value added (EVA) is:',
   'P500,000', 'P770,000', 'P1,100,000', 'P1,400,000',
   0, 'NOPAT = P2,000,000 × (1 − 30%) = P1,400,000. Capital charge = P9,000,000 × 10% = P900,000. EVA = P1,400,000 − P900,000 = P500,000.', 3),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'Under the controllability principle, a responsibility center manager should be evaluated based on:',
   'Only revenues and costs the manager can significantly influence', 'All costs allocated to the segment', 'Corporate-wide net income', 'Costs incurred by other segments that benefit the manager''s unit',
   0, 'Performance evaluation should isolate items the manager can control or significantly influence; allocated and external items distort the evaluation.', 1),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'A division currently earns an ROI of 25%. Its manager, evaluated solely on ROI, rejected a project expected to earn 20% even though the company''s cost of capital is 15%. Which performance measure would most likely have led the manager to accept the project?',
   'Return on investment computed on gross assets', 'Profit margin ratio', 'Payback period', 'Residual income',
   3, 'Residual income charges the project only the 15% cost of capital, so the 20% project adds positive residual income and promotes goal congruence; ROI evaluation discourages it because it dilutes the 25% average.', 2),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'A segment reports sales of P2,400,000, variable costs of P1,440,000, traceable fixed costs of P600,000, and allocated common fixed costs of P200,000. The segment margin is:',
   'P160,000', 'P360,000', 'P760,000', 'P960,000',
   1, 'Contribution margin = P2,400,000 − P1,440,000 = P960,000. Segment margin = P960,000 − P600,000 traceable fixed costs = P360,000; common costs are excluded.', 2),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'A division earns operating income of P400,000 on average assets of P2,000,000. It is considering a project requiring P400,000 of additional assets that will generate operating income of P60,000 per year. If the project is accepted, the division''s ROI will be closest to:',
   '15.0%', '19.2%', '20.0%', '23.0%',
   1, 'New ROI = (P400,000 + P60,000) ÷ (P2,000,000 + P400,000) = P460,000 ÷ P2,400,000 = 19.17%. The project''s 15% return drags the division average below 20%, so an ROI-evaluated manager may reject it.', 3),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'In transfer pricing, the maximum price the buying division should be willing to pay is generally:',
   'The outside market price of the product', 'The selling division''s variable cost', 'The selling division''s full cost plus markup', 'The selling division''s fixed cost per unit',
   0, 'The buying division will not pay more internally than what it would cost to buy the same item from an outside supplier, so the market price sets the ceiling.', 1),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'Division X earned P500,000 on average assets of P2,500,000, while Division Y earned P330,000 on average assets of P1,500,000. The required rate of return is 16%. Which statement is correct?',
   'X has both the higher ROI and the higher residual income', 'Y has both the higher ROI and the higher residual income', 'X has the higher ROI; Y has the higher residual income', 'Y has the higher ROI; X has the higher residual income',
   3, 'ROI: X = 20%, Y = 22%. Residual income: X = P500,000 − (16% × P2,500,000) = P100,000; Y = P330,000 − P240,000 = P90,000. Y wins on ROI but X wins on residual income.', 3),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'Which cost is most likely controllable by a production department supervisor?',
   'Direct materials usage in the department', 'Depreciation on the factory building', 'The plant manager''s salary', 'Allocated head-office insurance',
   0, 'A supervisor can influence the quantity of materials used in the department; depreciation, superiors'' salaries, and allocated insurance are outside the supervisor''s control.', 1),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'A division with average operating assets of P2,400,000 generated sales of P7,200,000 and an ROI of 24%. The division''s profit margin is:',
   '3%', '8%', '24%', '72%',
   1, 'Asset turnover = P7,200,000 ÷ P2,400,000 = 3 times. Margin = ROI ÷ turnover = 24% ÷ 3 = 8%.', 2),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'Division S has capacity of 50,000 units and currently sells 45,000 units to outside customers at P100 each; variable cost is P60 per unit. Division B requests 10,000 units. The minimum transfer price per unit that keeps Division S whole is:',
   'P60', 'P80', 'P90', 'P100',
   1, 'The transfer displaces 5,000 outside units. Minimum price = P60 + lost CM ÷ units transferred = P60 + (5,000 × P40) ÷ 10,000 = P60 + P20 = P80.', 3),
  ('MAS', 'Responsibility Accounting & Transfer Pricing',
   'A major weakness of transfer prices based on the actual full cost of the selling division is that they:',
   'Always exceed the outside market price', 'Cannot be used when idle capacity exists', 'Understate the selling division''s profit in all cases', 'Pass the selling division''s inefficiencies on to the buying division',
   3, 'When actual cost is reimbursed, cost overruns and inefficiencies are simply transferred to the buyer, removing the selling division''s incentive to control costs; standard cost avoids this.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'Which of the following costs is irrelevant to a decision to replace an old machine?',
   'Disposal value of the old machine', 'Purchase price of the new machine', 'Annual operating cost savings of the new machine', 'Book value of the old machine',
   3, 'The book value of the old machine is a sunk cost that cannot be changed by any current decision; disposal value, the new price, and future savings are all future amounts that differ between alternatives.', 1),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A company needs 10,000 units of a part. Making the part costs per unit: direct materials P24, direct labor P16, variable overhead P8, and fixed overhead P12, of which P4 is avoidable if the part is bought. An outside supplier offers the part at P54. The company should:',
   'Buy; it will save P20,000', 'Buy; it will save P60,000', 'Make; it will save P20,000', 'Make; it will save P60,000',
   2, 'Relevant cost to make = 24 + 16 + 8 + 4 = P52 versus P54 to buy, so making saves P2 × 10,000 = P20,000. Comparing the P60 full cost with P54 wrongly suggests buying.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A company with idle capacity normally sells its product at P90. Variable cost is P50, which includes P5 of variable selling cost that will not be incurred on a special order for 5,000 units at P52 each. Accepting the order will change operating income by:',
   'A decrease of P190,000', 'An increase of P10,000', 'An increase of P35,000', 'An increase of P60,000',
   2, 'Relevant cost per unit = P50 − P5 = P45. Increase = (P52 − P45) × 5,000 = P35,000; the regular P90 price is irrelevant when capacity is idle.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A product line shows sales of P1,000,000, variable costs of P650,000, and fixed costs of P450,000, of which P280,000 is avoidable if the line is dropped. Dropping the line will cause operating income to:',
   'Decrease by P70,000', 'Decrease by P350,000', 'Increase by P70,000', 'Increase by P100,000',
   0, 'Lost contribution margin = P350,000 versus fixed costs avoided of P280,000, so income falls by P70,000; the line''s P100,000 reported loss is misleading because P170,000 of fixed costs continue.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'Product A is allocated P150,000 of joint costs. It can be sold at split-off for P200,000, or processed further at a cost of P80,000 and sold for P300,000. The company should:',
   'Sell at split-off; the advantage is P130,000', 'Sell at split-off; the advantage is P60,000', 'Process further; the advantage is P100,000', 'Process further; the advantage is P20,000',
   3, 'Incremental revenue = P300,000 − P200,000 = P100,000 versus incremental cost of P80,000, an advantage of P20,000 from processing further. The allocated joint cost is irrelevant.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'Machine hours are the binding constraint. Product X has a contribution margin of P40 per unit and uses 2 hours; Product Y, P36 and 1.5 hours; Product Z, P50 and 2.5 hours. Which product should be produced first?',
   'Product Y, because its CM per machine hour is P24', 'Product Z, because it has the highest CM per unit', 'Product X, because its CM per machine hour is P20', 'Product Z, because its CM per machine hour is P25',
   0, 'CM per machine hour: X = 40 ÷ 2 = P20; Y = 36 ÷ 1.5 = P24; Z = 50 ÷ 2.5 = P20. With a scarce resource, rank by CM per unit of the constraint, so Y comes first.', 3),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A company has 10,000 machine hours available. Product A has a CM of P30 per unit and uses 2 hours (maximum demand 3,000 units); Product B has a CM of P20 per unit and uses 1 hour (maximum demand 6,000 units). The maximum total contribution margin is:',
   'P120,000', 'P170,000', 'P180,000', 'P210,000',
   2, 'B earns P20 per hour versus P15 for A, so fill B first: 6,000 units use 6,000 hours (CM P120,000); the remaining 4,000 hours make 2,000 units of A (CM P60,000). Total = P180,000.', 3),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'In a decision to replace an old machine, the book value of the old machine is:',
   'A relevant cost because it affects the decision', 'An opportunity cost of keeping the old machine', 'A sunk cost that is irrelevant to the decision', 'An incremental cost of buying the new machine',
   2, 'The book value of an existing asset is a sunk cost arising from a past, irreversible outlay; it does not differ between keeping and replacing, so it is irrelevant. Only future differential cash flows and the current salvage value of the old machine are relevant.', 1),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A company operating at full capacity sells its product at P100 with a unit variable cost of P70. A special order would displace regular sales unit for unit. The minimum acceptable special-order price per unit is:',
   'P70', 'P100', 'P115', 'P130',
   1, 'At full capacity, minimum price = variable cost + opportunity cost = P70 + (P100 − P70) lost CM = P100, the regular selling price.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A company needs 20,000 units of a component. Buying costs P25 per unit. Making costs P21 per unit in variable cost plus P30,000 of avoidable fixed cost. If the component is bought, the freed facilities can be rented out for P80,000 per year. The company should:',
   'Buy; it is better off by P30,000', 'Buy; it is better off by P50,000', 'Make; it is better off by P30,000', 'Make; it is better off by P50,000',
   0, 'Cost to make = (P21 × 20,000) + P30,000 + P80,000 forgone rent = P530,000 versus P500,000 to buy, so buying is better by P30,000. Ignoring the rental income wrongly favors making by P50,000.', 3),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'In deciding whether to accept a one-time special order, which of the following is least likely to be relevant?',
   'Variable manufacturing cost of the order', 'Incremental tooling cost required by the order', 'Contribution margin of regular sales displaced by the order', 'Allocated fixed overhead that will continue regardless of the order',
   3, 'Fixed overhead that is merely allocated and will be incurred whether or not the order is accepted does not differ between alternatives and is therefore irrelevant.', 1),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A company expects fixed costs of P600,000 if it continues to operate during the off-season; shutting down temporarily would still require P240,000 of fixed costs. The contribution margin ratio is 40%. The shutdown point in peso sales is:',
   'P600,000', 'P900,000', 'P1,500,000', 'P2,100,000',
   1, 'Shutdown point = avoidable fixed costs ÷ CM ratio = (P600,000 − P240,000) ÷ 0.40 = P900,000. Below this sales level, shutting down is preferable.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A plant currently produces 20,000 units. Variable cost is P12 per unit and total fixed costs of P100,000 will not change within the relevant range. The differential cost of increasing production to 25,000 units is:',
   'P60,000', 'P100,000', 'P160,000', 'P300,000',
   0, 'Only variable costs change: 5,000 additional units × P12 = P60,000. Fixed costs are the same at both volumes and are not differential.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'Which cost is never relevant to a short-term decision?',
   'Sunk cost', 'Avoidable fixed cost', 'Opportunity cost', 'Differential variable cost',
   0, 'Sunk costs have already been incurred and are identical under every alternative, so they can never be relevant; the other three differ among alternatives.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A company with idle capacity receives a special order for 6,000 units at P45. Variable manufacturing cost is P38 per unit; full cost is P47 including P9 of allocated fixed overhead. The order requires special tooling of P24,000. Accepting the order will change operating income by:',
   'A decrease of P36,000', 'A decrease of P12,000', 'An increase of P18,000', 'An increase of P42,000',
   2, 'Incremental CM = (P45 − P38) × 6,000 = P42,000, less tooling of P24,000, for a net increase of P18,000. Using the P47 full cost wrongly signals rejection.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A company produces 10,000 units of Product P that can be sold at split-off for P15 each. Further processing costs P60,000, after which the units sell for P22 each. Joint costs of P90,000 have already been allocated to P. The company should:',
   'Sell at split-off because joint costs exceed further-processing gains', 'Sell at split-off; income falls by P20,000 if processed', 'Process further; income rises by P70,000', 'Process further; income rises by P10,000',
   3, 'Incremental revenue = (P22 − P15) × 10,000 = P70,000 versus P60,000 of further processing cost, so income rises by P10,000. The P90,000 joint cost is sunk and irrelevant.', 3),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'In a make-or-buy decision, which of the following is NOT relevant?',
   'The outside purchase price', 'Variable production cost of the part', 'Common fixed overhead allocated to the part that will continue either way', 'Salary of an inspector hired only when the part is made',
   2, 'Allocated common fixed overhead that continues under both alternatives does not differ and is irrelevant; the inspector''s salary is avoidable and therefore relevant.', 1),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A segment reports sales of P800,000, variable costs of P560,000, and traceable fixed costs of P300,000, all of which are avoidable. Dropping the segment will cause company operating income to:',
   'Increase by P60,000', 'Increase by P300,000', 'Decrease by P60,000', 'Decrease by P240,000',
   0, 'Dropping loses CM of P800,000 − P560,000 = P240,000 but avoids P300,000 of fixed costs, so income increases by P60,000.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'Materials that originally cost P50,000 are in inventory. They have no other production use, and the only alternative is to sell them as scrap for P8,000. The relevant cost of using these materials on a special job is:',
   'P0', 'P8,000', 'P42,000', 'P50,000',
   1, 'The historical P50,000 is sunk. Using the materials forfeits the P8,000 scrap proceeds, so the relevant (opportunity) cost is P8,000.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A company is evaluating a special order at a price below the regular selling price. Which qualitative factor most strongly argues against acceptance?',
   'The order will use otherwise idle capacity', 'The order requires no incremental selling costs', 'The customer is in a market segment the company does not normally serve', 'Regular customers may learn of the lower price and demand similar discounts',
   3, 'Price erosion among existing customers can permanently damage regular margins, outweighing the one-time gain; the other factors support acceptance.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'In a sell-or-process-further decision, the costs that are relevant are:',
   'Incremental processing costs and incremental revenues beyond split-off', 'Allocated joint costs and incremental revenues', 'Total joint costs only', 'All production costs incurred up to the split-off point',
   0, 'Joint costs are incurred before split-off under either choice and are sunk; only revenues and costs that change beyond split-off matter.', 1),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A part used in production has these unit costs: direct materials P10, direct labor P8, variable overhead P6, and fixed overhead P10, of which 40% is avoidable if the part is purchased. The maximum price the company should pay an outside supplier is:',
   'P24', 'P28', 'P30', 'P34',
   1, 'Avoidable cost of making = 10 + 8 + 6 + (P10 × 40%) = P28 per unit; paying more than P28 outside makes the company worse off.', 2),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'A company at full capacity receives a special order for 8,000 units at P60 each; variable cost is P40 per unit. Accepting the order requires giving up 3,000 units of regular sales priced at P75 with the same P40 variable cost. Accepting the order will change operating income by:',
   'A decrease of P65,000', 'An increase of P55,000', 'An increase of P160,000', 'An increase of P225,000',
   1, 'Order CM = (P60 − P40) × 8,000 = P160,000 less displaced CM of (P75 − P40) × 3,000 = P105,000, a net increase of P55,000. Deducting lost revenue instead of lost CM wrongly shows a decrease.', 3),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'Differential (incremental) cost is best described as:',
   'The cost that has been incurred in the past', 'A cost common to all alternatives', 'The difference in total cost between two alternatives', 'Fixed cost per unit at normal capacity',
   2, 'Differential cost is the change in total cost when one alternative is chosen over another; it is the heart of relevant-cost analysis.', 1),
  ('MAS', 'Relevant Costing & Short-Term Decisions',
   'Product A has a contribution margin of P24 per unit and requires 4 hours of the constrained resource; Product B has a contribution margin of P18 and requires 2 hours. When the resource is fully utilized, which product should be prioritized?',
   'Product A, because its CM per unit is higher', 'Product A, because it uses more of the resource', 'Either product, because both are profitable', 'Product B, because its CM per hour of P9 exceeds Product A''s P6',
   3, 'CM per constraint hour: A = 24 ÷ 4 = P6; B = 18 ÷ 2 = P9. With a binding constraint, maximize CM per unit of the scarce resource, so B is prioritized.', 2),
  ('MAS', 'Capital Budgeting',
   'A machine costing P900,000 is expected to generate equal annual net cash inflows of P225,000. The payback period is:',
   '3.0 years', '3.5 years', '4.0 years', '4.5 years',
   2, 'Payback = P900,000 / P225,000 = 4.0 years.', 1),
  ('MAS', 'Capital Budgeting',
   'A project requires an initial investment of P1,200,000 and produces net cash inflows of P300,000, P400,000, P500,000, and P600,000 in years 1 through 4. The payback period is approximately:',
   '2.6 years', '3.0 years', '3.4 years', '3.7 years',
   1, 'Cumulative inflows reach P1,200,000 exactly at the end of year 3 (P300,000 + P400,000 + P500,000), so payback is 3.0 years.', 2),
  ('MAS', 'Capital Budgeting',
   'An investment of P500,000 returns net cash inflows of P150,000, P200,000, P250,000, and P100,000 over four years. The payback period is:',
   '2.6 years', '2.8 years', '3.0 years', '3.2 years',
   0, 'After 2 years cumulative inflow is P350,000; the remaining P150,000 is recovered in year 3 (P150,000 / P250,000 = 0.6), so payback = 2.6 years.', 2),
  ('MAS', 'Capital Budgeting',
   'Discounted payback differs from ordinary payback primarily because it:',
   'Ignores cash flows after the payback point', 'Uses accounting income instead of cash flow', 'Discounts each cash inflow to present value before accumulating it', 'Measures profitability over the full project life',
   2, 'Discounted payback applies the time value of money by discounting each inflow to present value before counting toward recovery; it still ignores flows after payback.', 2),
  ('MAS', 'Capital Budgeting',
   'Equipment costing P800,000 with no salvage value and a 5-year life generates average annual net income of P120,000. The accounting rate of return on the initial investment is:',
   '12%', '15%', '20%', '24%',
   1, 'ARR on initial investment = P120,000 / P800,000 = 15%.', 2),
  ('MAS', 'Capital Budgeting',
   'An asset costs P1,000,000, has zero salvage value, and yields average annual net income of P90,000. The accounting rate of return based on the average investment is:',
   '4.5%', '9.0%', '12.0%', '18.0%',
   3, 'Average investment = (P1,000,000 + 0) / 2 = P500,000. ARR = P90,000 / P500,000 = 18.0%.', 2),
  ('MAS', 'Capital Budgeting',
   'A project requires P600,000, has a P100,000 salvage value, and produces average annual net income of P70,000. The accounting rate of return on the average investment is:',
   '20.0%', '14.0%', '11.7%', '23.3%',
   0, 'Average investment = (P600,000 + P100,000) / 2 = P350,000. ARR = P70,000 / P350,000 = 20.0%.', 3),
  ('MAS', 'Capital Budgeting',
   'The principal weakness of the accounting rate of return as a capital budgeting tool is that it:',
   'Requires forecasting cash flows', 'Overstates the payback period', 'Cannot rank competing projects', 'Ignores the time value of money',
   3, 'The accounting rate of return uses accrual net income and does not discount future amounts, so it ignores the time value of money.', 1),
  ('MAS', 'Capital Budgeting',
   'A project costs P400,000 and returns P120,000 per year for 5 years. Using a PV-of-annuity factor of 3.605 at 12%, the net present value is:',
   'P32,600', 'P38,200', 'P40,000', 'P46,800',
   0, 'PV of inflows = P120,000 × 3.605 = P432,600. NPV = P432,600 - P400,000 = P32,600.', 2),
  ('MAS', 'Capital Budgeting',
   'A machine costing P700,000 returns P200,000 per year for 5 years and has a P50,000 salvage value at the end. Using PV-of-annuity factor 3.791 and PV-of-P1 factor 0.621 at 10%, the net present value is:',
   'P58,200', 'P31,050', 'P89,250', 'P120,300',
   2, 'PV of annual inflows = P200,000 × 3.791 = P758,200. PV of salvage = P50,000 × 0.621 = P31,050. NPV = P758,200 + P31,050 - P700,000 = P89,250.', 3),
  ('MAS', 'Capital Budgeting',
   'A firm in the 30% tax bracket buys equipment for P500,000, depreciated straight-line over 5 years with no salvage. The annual depreciation tax shield is:',
   'P30,000', 'P35,000', 'P100,000', 'P150,000',
   0, 'Annual depreciation = P500,000 / 5 = P100,000. Tax shield = P100,000 × 30% = P30,000.', 2),
  ('MAS', 'Capital Budgeting',
   'A project generates P400,000 in pretax operating cash inflow and P150,000 of depreciation annually; the tax rate is 25%. The after-tax operating cash inflow is:',
   'P225,000', 'P300,000', 'P337,500', 'P400,000',
   2, 'After-tax cash flow = (P400,000 - P150,000) × (1 - 0.25) + P150,000 = P187,500 + P150,000 = P337,500.', 3),
  ('MAS', 'Capital Budgeting',
   'At the internal rate of return, a project''s net present value equals:',
   'Zero', 'Its initial investment', 'The sum of undiscounted cash flows', 'The cost of capital',
   0, 'The internal rate of return is the discount rate at which the net present value of a project equals zero.', 1),
  ('MAS', 'Capital Budgeting',
   'A project costing P450,000 yields equal annual cash inflows of P90,000 for 8 years. The PV-of-annuity factor that corresponds to its internal rate of return is:',
   '4.0', '4.5', '5.0', '5.5',
   2, 'For even cash flows, the IRR factor = investment / annual cash flow = P450,000 / P90,000 = 5.0.', 2),
  ('MAS', 'Capital Budgeting',
   'An investment of P318,000 produces level annual cash inflows of P60,000 for 10 years. The PV-of-annuity factor used to locate its internal rate of return is:',
   '4.30', '5.30', '6.30', '7.30',
   1, 'IRR factor = investment / annual cash flow = P318,000 / P60,000 = 5.30.', 2),
  ('MAS', 'Capital Budgeting',
   'A project with an internal rate of return of 14% should be accepted when the firm''s cost of capital is:',
   '16%', '15%', '14.5%', '11%',
   3, 'A project is acceptable when its internal rate of return exceeds the hurdle rate; 14% exceeds an 11% cost of capital.', 1),
  ('MAS', 'Capital Budgeting',
   'A project has present value of future cash inflows of P660,000 against an initial investment of P600,000. Its profitability index is:',
   '0.91', '1.00', '1.10', '1.60',
   2, 'Profitability index = PV of inflows / initial investment = P660,000 / P600,000 = 1.10.', 2),
  ('MAS', 'Capital Budgeting',
   'A project has an initial outlay of P800,000 and a present value of inflows of P920,000. Its net present value and profitability index, respectively, are:',
   'P120,000 and 1.15', 'P120,000 and 0.87', 'P920,000 and 1.15', 'P120,000 and 1.13',
   0, 'NPV = P920,000 - P800,000 = P120,000. Profitability index = P920,000 / P800,000 = 1.15.', 2),
  ('MAS', 'Capital Budgeting',
   'Two projects are mutually exclusive. This means that:',
   'Both must be accepted together', 'Their cash flows are independent', 'They share the same internal rate of return', 'Accepting one precludes accepting the other',
   3, 'With mutually exclusive projects, choosing one automatically rules out the other, so only the better single project is selected.', 1),
  ('MAS', 'Capital Budgeting',
   'In discounted cash flow analysis, the cost of capital generally functions as the:',
   'Salvage value of the project', 'Payback threshold', 'Accounting rate of return', 'Required rate of return used to discount cash flows',
   3, 'The cost of capital is the hurdle rate; cash flows are discounted at this required rate of return to test acceptability.', 1),
  ('MAS', 'Capital Budgeting',
   'A project requires P900,000 of equipment plus P100,000 of additional working capital recovered at the end of year 5. Using a PV-of-P1 factor of 0.567 at 12% for year 5, the present value of the working-capital recovery is:',
   'P56,700', 'P100,000', 'P62,700', 'P51,000',
   0, 'PV of working-capital recovery = P100,000 × 0.567 = P56,700.', 2),
  ('MAS', 'Capital Budgeting',
   'Equipment is sold at the end of a project for P80,000 when its book value is P50,000; the tax rate is 30%. The after-tax cash proceeds from the disposal are:',
   'P56,000', 'P71,000', 'P80,000', 'P74,000',
   1, 'Gain = P80,000 - P50,000 = P30,000; tax on gain = P30,000 × 30% = P9,000. After-tax proceeds = P80,000 - P9,000 = P71,000.', 3),
  ('MAS', 'Capital Budgeting',
   'A project returns P50,000, P60,000, and P70,000 over three years against an initial cost of P130,000. The payback period is:',
   '2.0 years', '2.3 years', '2.5 years', '2.7 years',
   1, 'After 2 years cumulative inflow is P110,000; the remaining P20,000 is recovered in year 3 (P20,000 / P70,000 = 0.29), so payback is about 2.3 years.', 2),
  ('MAS', 'Capital Budgeting',
   'A new product line needs P1,500,000 in equipment and P200,000 in initial working capital. The total initial investment recognized at time zero is:',
   'P1,300,000', 'P200,000', 'P1,500,000', 'P1,700,000',
   3, 'The initial investment includes both the equipment outlay and the increase in working capital: P1,500,000 + P200,000 = P1,700,000.', 1),
  ('MAS', 'Capital Budgeting',
   'Which item is treated as a relevant cash flow in capital budgeting?',
   'Sunk cost already incurred for a prior study', 'Allocated fixed corporate overhead that does not change', 'Incremental after-tax operating cash inflow from the project', 'Historical depreciation on existing assets',
   2, 'Only incremental, future cash flows that change because of the decision are relevant; sunk costs and unchanged allocations are excluded.', 2),
  ('MAS', 'Financial Statement Analysis',
   'A company has current assets of P800,000 and current liabilities of P400,000. Its current ratio is:',
   '0.5 to 1', '1.0 to 1', '2.0 to 1', '4.0 to 1',
   2, 'Current ratio = current assets / current liabilities = P800,000 / P400,000 = 2.0 to 1.', 1),
  ('MAS', 'Financial Statement Analysis',
   'A firm reports cash P100,000, receivables P200,000, inventory P300,000, and current liabilities P250,000. Its quick (acid-test) ratio is:',
   '1.2 to 1', '1.6 to 1', '2.4 to 1', '0.8 to 1',
   0, 'Quick assets = cash + receivables = P100,000 + P200,000 = P300,000. Quick ratio = P300,000 / P250,000 = 1.2 to 1.', 2),
  ('MAS', 'Financial Statement Analysis',
   'Net credit sales are P3,600,000 and average accounts receivable are P450,000. The receivable turnover is:',
   '6.0 times', '7.0 times', '8.0 times', '9.0 times',
   2, 'Receivable turnover = net credit sales / average receivables = P3,600,000 / P450,000 = 8.0 times.', 2),
  ('MAS', 'Financial Statement Analysis',
   'Cost of goods sold is P2,400,000 and average inventory is P300,000. Using a 360-day year, the average days inventory on hand is:',
   '30 days', '75 days', '60 days', '45 days',
   3, 'Inventory turnover = P2,400,000 / P300,000 = 8 times. Days = 360 / 8 = 45 days.', 2),
  ('MAS', 'Financial Statement Analysis',
   'A company has days inventory of 50 and days receivable of 40. Its operating cycle is:',
   '10 days', '40 days', '50 days', '90 days',
   3, 'Operating cycle = days inventory + days receivable = 50 + 40 = 90 days.', 2),
  ('MAS', 'Financial Statement Analysis',
   'A firm has days inventory of 60, days receivable of 45, and days payable of 30. Its cash conversion cycle is:',
   '75 days', '90 days', '105 days', '135 days',
   0, 'Cash conversion cycle = days inventory + days receivable - days payable = 60 + 45 - 30 = 75 days.', 2),
  ('MAS', 'Financial Statement Analysis',
   'Total liabilities are P1,500,000 and total equity is P2,500,000. The debt-to-equity ratio is:',
   '0.40 to 1', '0.60 to 1', '1.67 to 1', '2.50 to 1',
   1, 'Debt-to-equity = total liabilities / total equity = P1,500,000 / P2,500,000 = 0.60 to 1.', 2),
  ('MAS', 'Financial Statement Analysis',
   'Operating income (EBIT) is P900,000 and annual interest expense is P150,000. The times-interest-earned ratio is:',
   '6.0 times', '5.0 times', '4.0 times', '7.5 times',
   0, 'Times interest earned = EBIT / interest expense = P900,000 / P150,000 = 6.0 times.', 1),
  ('MAS', 'Financial Statement Analysis',
   'Net sales are P5,000,000 and cost of goods sold is P3,250,000. The gross profit margin is:',
   '30%', '65%', '45%', '35%',
   3, 'Gross profit = P5,000,000 - P3,250,000 = P1,750,000. Gross margin = P1,750,000 / P5,000,000 = 35%.', 1),
  ('MAS', 'Financial Statement Analysis',
   'Net sales are P4,000,000 and average total assets are P2,000,000. The total asset turnover is:',
   '0.5 times', '1.5 times', '2.0 times', '4.0 times',
   2, 'Total asset turnover = net sales / average total assets = P4,000,000 / P2,000,000 = 2.0 times.', 1),
  ('MAS', 'Financial Statement Analysis',
   'A firm has a net profit margin of 10%, total asset turnover of 2.0, and an equity multiplier of 1.5. Using the DuPont model, its return on equity is:',
   '20%', '25%', '30%', '15%',
   2, 'DuPont ROE = net margin × asset turnover × equity multiplier = 10% × 2.0 × 1.5 = 30%.', 3),
  ('MAS', 'Financial Statement Analysis',
   'Net income available to common is P1,200,000 and the weighted-average common shares outstanding are 400,000. Earnings per share is:',
   'P2.00', 'P2.50', 'P3.00', 'P4.00',
   2, 'EPS = net income to common / weighted-average shares = P1,200,000 / 400,000 = P3.00.', 1),
  ('MAS', 'Financial Statement Analysis',
   'A share trades at P60 and its earnings per share is P5. The price-earnings ratio is:',
   '12 times', '10 times', '8 times', '15 times',
   0, 'Price-earnings ratio = market price per share / EPS = P60 / P5 = 12 times.', 1),
  ('MAS', 'Financial Statement Analysis',
   'A share priced at P80 pays an annual dividend of P4 per share. Its dividend yield is:',
   '5%', '4%', '8%', '20%',
   0, 'Dividend yield = dividend per share / market price = P4 / P80 = 5%.', 2),
  ('MAS', 'Financial Statement Analysis',
   'A firm with a current ratio of 1.5 to 1 uses cash to pay a current liability. The effect on the current ratio is to:',
   'Decrease it', 'Increase it', 'Leave it unchanged', 'Make it exactly 1.0',
   1, 'When the current ratio is above 1, paying a current liability reduces both numerator and denominator by the same amount, which raises the ratio.', 3),
  ('MAS', 'Financial Statement Analysis',
   'A firm with a current ratio of 0.8 to 1 pays a short-term payable with cash. The effect on the current ratio is to:',
   'Decrease it', 'Increase it', 'Leave it unchanged', 'Raise it above 1.0',
   0, 'When the current ratio is below 1, paying a current liability lowers both amounts equally, which decreases the ratio further.', 3),
  ('MAS', 'Financial Statement Analysis',
   'Expressing each income statement line as a percentage of net sales for a single period is an example of:',
   'Horizontal analysis', 'Vertical analysis', 'Trend analysis', 'Ratio benchmarking',
   1, 'Vertical analysis (common-size analysis) states each statement item as a percentage of a base amount within the same period, such as net sales.', 2),
  ('MAS', 'Working Capital Management',
   'Under an aggressive working capital financing policy, a firm tends to:',
   'Finance most current assets with long-term sources', 'Finance a large portion of current assets with short-term debt', 'Hold large balances of cash and inventory', 'Avoid all short-term borrowing',
   1, 'An aggressive policy relies heavily on cheaper short-term debt to finance current assets, accepting higher liquidity and refinancing risk.', 2),
  ('MAS', 'Working Capital Management',
   'A conservative working capital financing policy is generally characterized by:',
   'Higher liquidity and lower risk', 'Lower financing cost and higher risk', 'Maximum use of short-term debt', 'Minimal investment in current assets',
   0, 'A conservative policy funds even temporary current assets with long-term capital, increasing liquidity and reducing refinancing risk while usually costing more.', 2),
  ('MAS', 'Working Capital Management',
   'Annual demand is 9,000 units, the order cost is P160 per order, and the carrying cost is P4 per unit per year. The economic order quantity is:',
   '600 units', '849 units', '1,200 units', '720 units',
   1, 'EOQ = sqrt(2 × 9,000 × 160 / 4) = sqrt(720,000) = approximately 849 units. Recompute: 2 × 9,000 × 160 = 2,880,000; divided by 4 = 720,000; square root = 848.5, which rounds to 849 units.', 3),
  ('MAS', 'Working Capital Management',
   'Annual demand is 10,000 units, the cost per order is P125, and the annual carrying cost is P5 per unit. The economic order quantity is:',
   '500 units', '707 units', '625 units', '1,000 units',
   1, 'EOQ = sqrt(2 × 10,000 × 125 / 5) = sqrt(500,000) = approximately 707 units.', 2),
  ('MAS', 'Working Capital Management',
   'A firm uses 50 units per day and the supplier lead time is 6 days. With no safety stock, the reorder point is:',
   '56 units', '150 units', '300 units', '350 units',
   2, 'Reorder point = daily usage × lead time = 50 × 6 = 300 units.', 1),
  ('MAS', 'Working Capital Management',
   'Daily usage is 40 units, lead time is 5 days, and the firm keeps safety stock of 80 units. The reorder point is:',
   '120 units', '200 units', '240 units', '280 units',
   3, 'Reorder point = (daily usage × lead time) + safety stock = (40 × 5) + 80 = 200 + 80 = 280 units.', 2),
  ('MAS', 'Working Capital Management',
   'Credit terms are 2/10, net 30. Using a 360-day year, the approximate annualized cost of forgoing the cash discount is:',
   '24.0%', '36.7%', '48.0%', '18.4%',
   1, 'Cost = (2 / 98) × (360 / (30 - 10)) = 0.020408 × 18 = approximately 36.7%.', 3),
  ('MAS', 'Working Capital Management',
   'Credit terms are 1/10, net 40. Using a 360-day year, the approximate annualized cost of not taking the discount is:',
   '12.1%', '18.2%', '9.1%', '24.0%',
   0, 'Cost = (1 / 99) × (360 / (40 - 10)) = 0.010101 × 12 = approximately 12.1%.', 3),
  ('MAS', 'Working Capital Management',
   'Disbursement float refers to the:',
   'Delay between writing a check and its clearing the bank', 'Time customers take to mail payments', 'Interest earned on idle cash', 'Cost of factoring receivables',
   0, 'Disbursement float is the time between when a firm writes a check and when funds are actually deducted from its bank account.', 2),
  ('MAS', 'Working Capital Management',
   'The principal benefit of a lockbox system is that it:',
   'Eliminates bad debts entirely', 'Removes the need for safety stock', 'Increases the cost of forgoing discounts', 'Speeds the collection and deposit of customer payments',
   3, 'A lockbox shortens mail and processing delays so customer payments are deposited faster, reducing collection float.', 2),
  ('MAS', 'Working Capital Management',
   'A firm borrows P500,000 for one year on a discount basis at a 10% stated rate, receiving the loan net of interest. The effective annual interest rate is approximately:',
   '10.0%', '11.1%', '9.0%', '12.5%',
   1, 'Interest = P500,000 × 10% = P50,000; proceeds = P450,000. Effective rate = P50,000 / P450,000 = approximately 11.1%.', 3),
  ('MAS', 'Working Capital Management',
   'Factoring of accounts receivable is best described as:',
   'Pledging receivables as loan collateral only', 'Holding receivables until maturity', 'Extending longer credit terms to customers', 'Selling receivables to a third party for immediate cash',
   3, 'Factoring is the outright sale of receivables to a factor in exchange for immediate cash, transferring collection to the factor.', 2),
  ('MAS', 'Working Capital Management',
   'Holding all else equal, an increase in a firm''s investment in current assets relative to sales generally results in:',
   'Higher risk and lower liquidity', 'Lower liquidity and higher return', 'Higher liquidity and lower expected return', 'No effect on risk or return',
   2, 'Carrying more current assets raises liquidity and lowers risk, but the lower-yielding assets typically reduce the firm''s expected return.', 2),
  ('MAS', 'Economics & Strategy Concepts',
   'If a 10% increase in price causes total revenue to fall, the demand for the product is:',
   'Perfectly inelastic', 'Inelastic', 'Unit elastic', 'Elastic',
   3, 'When a price increase reduces total revenue, quantity falls more than proportionally, indicating elastic demand.', 2),
  ('MAS', 'Economics & Strategy Concepts',
   'When demand for a good is inelastic, a firm that raises its price will experience:',
   'An increase in total revenue', 'A decrease in total revenue', 'No change in total revenue', 'A proportional fall in quantity',
   0, 'With inelastic demand, quantity falls less than proportionally to the price increase, so total revenue rises.', 2),
  ('MAS', 'Economics & Strategy Concepts',
   'A shift of the entire demand curve to the right, rather than a movement along it, is most likely caused by:',
   'A rise in consumer incomes for a normal good', 'A decrease in the good''s own price', 'An increase in the good''s own price', 'A change in quantity demanded only',
   0, 'A change in a determinant such as income shifts the whole demand curve; a change in the good''s own price only causes movement along the curve.', 2),
  ('MAS', 'Economics & Strategy Concepts',
   'A market with many firms selling identical products, with free entry and exit and no single firm able to influence price, is:',
   'Monopoly', 'Oligopoly', 'Perfect competition', 'Monopolistic competition',
   2, 'Perfect competition features many price-taking firms, homogeneous products, and free entry and exit.', 1),
  ('MAS', 'Economics & Strategy Concepts',
   'A market dominated by a few large firms whose pricing decisions are interdependent is best described as:',
   'Perfect competition', 'Monopoly', 'Oligopoly', 'Pure competition',
   2, 'An oligopoly consists of a few firms whose actions and pricing strategies are mutually interdependent.', 1),
  ('MAS', 'Economics & Strategy Concepts',
   'A sustained general increase in the overall price level in an economy is called:',
   'Deflation', 'Inflation', 'Recession', 'Appreciation',
   1, 'Inflation is a sustained rise in the general level of prices, which erodes the purchasing power of money.', 1),
  ('MAS', 'Economics & Strategy Concepts',
   'Gross domestic product is best defined as the:',
   'Total income earned by citizens abroad', 'Market value of all final goods and services produced within a country in a period', 'Sum of all financial transactions in an economy', 'Value of exports minus imports only',
   1, 'GDP measures the market value of all final goods and services produced within a country''s borders during a given period.', 2),
  ('MAS', 'Economics & Strategy Concepts',
   'In Porter''s five forces, the threat that customers can demand lower prices or higher quality reflects the:',
   'Threat of new entrants', 'Rivalry among existing firms', 'Threat of substitutes', 'Bargaining power of buyers',
   3, 'The bargaining power of buyers is the force describing customers'' ability to push prices down or demand more value.', 2),
  ('MAS', 'Economics & Strategy Concepts',
   'A firm that seeks competitive advantage by achieving the lowest production and distribution costs in its industry is pursuing a generic strategy of:',
   'Differentiation', 'Cost leadership', 'Focus on quality', 'Market development',
   1, 'Cost leadership aims to be the lowest-cost producer in the industry, allowing the firm to compete on price or earn higher margins.', 2),
  ('MAS', 'Economics & Strategy Concepts',
   'A company that commands premium prices through unique product features and strong brand image is following a strategy of:',
   'Cost leadership', 'Differentiation', 'Cost focus', 'Liquidation',
   1, 'A differentiation strategy builds competitive advantage through unique attributes that customers value and will pay a premium for.', 1),
  ('MAS', 'Economics & Strategy Concepts',
   'In Porter''s value chain, activities such as inbound logistics, operations, and outbound logistics are classified as:',
   'Support activities', 'Discretionary costs', 'Financing activities', 'Primary activities',
   3, 'Primary activities directly create and deliver the product and include inbound logistics, operations, outbound logistics, marketing and sales, and service.', 2),
  ('MAS', 'Economics & Strategy Concepts',
   'Which of the following is a perspective of the balanced scorecard?',
   'Liquidity perspective', 'Internal business process perspective', 'Tax compliance perspective', 'Capital structure perspective',
   1, 'The four balanced scorecard perspectives are financial, customer, internal business process, and learning and growth.', 2),
  ('MAS', 'Economics & Strategy Concepts',
   'In the balanced scorecard, employee training hours are best classified as a:',
   'Lagging (outcome) indicator', 'Leading (driver) indicator', 'Financial outcome measure', 'Final result measure',
   1, 'Training hours are a leading indicator because they drive future performance, whereas lagging indicators such as profit report past results.', 2)
)
insert into public.questions (topic_id, stem, choices, correct_index, explanation, difficulty)
select t.id, q.stem, jsonb_build_array(q.a, q.b, q.c, q.d), q.correct_index, q.explanation, q.difficulty
from q join t on t.code = q.subject_code and lower(t.name) = lower(q.topic)
where not exists (select 1 from public.questions x where x.stem = q.stem);
