-- Generated from content/rfbt-batch-001.csv by scripts/csv-to-seed-sql.mjs — do not edit by hand.
-- Idempotent: skips any question whose stem already exists.
with t as (
  select tp.id, tp.name, s.code from public.topics tp
  join public.subjects s on s.id = tp.subject_id
),
q(subject_code, topic, stem, a, b, c, d, correct_index, explanation, difficulty) as (values
  ('RFBT', 'Law on Obligations',
   'Which of the following is NOT an essential element of an obligation?',
   'An active subject or creditor', 'A public instrument evidencing the agreement', 'A juridical or legal tie binding the parties', 'A prestation to give, to do, or not to do',
   1, 'The essential elements are the active subject, passive subject, prestation, and the vinculum juris or juridical tie. A written instrument is not essential; obligations may arise even from purely oral agreements.', 1),
  ('RFBT', 'Law on Obligations',
   'While his neighbor Carlo was abroad, Ben hired workers to repair Carlo''s roof which had been torn off by a typhoon, without any authority from Carlo. Carlo''s obligation to reimburse Ben for the necessary expenses arises from:',
   'Quasi-contract', 'Contract', 'Quasi-delict', 'Delict',
   0, 'This is negotiorum gestio, the voluntary management of another''s neglected property or business without authority (Art. 2144), a quasi-contract obliging the owner to reimburse necessary and useful expenses.', 2),
  ('RFBT', 'Law on Obligations',
   'Dina paid Carlo P20,000 in the honest but mistaken belief that she owed him that amount, when in fact the debt had already been extinguished. Carlo''s obligation to return the P20,000 arises from:',
   'Delict', 'Law', 'Solutio indebiti, which is a quasi-contract', 'Quasi-delict',
   2, 'Under Art. 2154, if something is received when there is no right to demand it and it was unduly delivered through mistake, the obligation to return it arises. This is solutio indebiti, a quasi-contract.', 2),
  ('RFBT', 'Law on Obligations',
   'Ana negligently left a flowerpot on her window ledge; it fell and injured Pedro, a passerby. No criminal action was filed and there was no pre-existing contractual relation between them. Ana''s civil liability to Pedro is based on:',
   'Contract', 'Delict', 'Law', 'Quasi-delict',
   3, 'Fault or negligence causing damage to another, there being no pre-existing contractual relation, is a quasi-delict under Art. 2176, which itself is a source of obligation.', 2),
  ('RFBT', 'Law on Obligations',
   'When the law and the stipulation of the parties are silent as to the diligence required in performing an obligation, the obligor must observe:',
   'Extraordinary diligence', 'The diligence of a good father of a family', 'Slight diligence', 'The utmost diligence required of common carriers',
   1, 'Under Art. 1173, if the law or contract does not state the diligence required, that which is expected of a good father of a family (ordinary diligence) is the standard.', 1),
  ('RFBT', 'Law on Obligations',
   'In an obligation to deliver a determinate thing, the creditor acquires a right to the fruits of the thing:',
   'From the time the obligation to deliver the thing arises', 'Only upon actual delivery of the thing', 'Only upon full payment of the price', 'Only upon execution of a public instrument',
   0, 'Art. 1164 gives the creditor a right to the fruits from the time the obligation to deliver arises; however, he acquires no real right over the thing until it has been delivered to him.', 2),
  ('RFBT', 'Law on Obligations',
   'As a general rule, an obligor who is unable to deliver the determinate thing due because it was destroyed by a fortuitous event is:',
   'Liable, because obligations have the force of law between the parties', 'Liable for one-half of the value of the thing', 'Not liable, because no person shall be responsible for events which could not be foreseen, or which, though foreseen, were inevitable', 'Liable for moral damages only',
   2, 'Art. 1174 excuses the debtor from liability for fortuitous events, except when the law or stipulation provides otherwise or when the nature of the obligation requires the assumption of risk.', 1),
  ('RFBT', 'Law on Obligations',
   'Carlo bound himself to deliver his specific racehorse to Ben on June 1. Ben made a demand on June 2 but Carlo ignored it. On June 10 the horse was killed by lightning. Is Carlo liable?',
   'No, because the loss was due to a fortuitous event', 'No, because the horse is a determinate thing', 'Yes, but only if Carlo was also negligent', 'Yes, because the loss occurred after Carlo had already incurred in delay',
   3, 'A debtor in mora is liable even for fortuitous events (Arts. 1165 and 1170). Demand was made and ignored, so Carlo was in delay when the horse perished and he bears the loss.', 2),
  ('RFBT', 'Law on Obligations',
   'Ana, under two separate contracts, obligated herself to deliver the same specific car to Ben and later to Carlo. Before delivery, the car was destroyed by a flood without Ana''s fault. Which is correct?',
   'Ana is excused from liability because of the fortuitous event', 'Ana is liable despite the fortuitous event, because she promised to deliver the same thing to two persons who do not have the same interest', 'Ana is liable only to Ben, the first promisee', 'Ana is liable only if she was already in delay',
   1, 'Under Art. 1165, when the obligor promises to deliver the same determinate thing to two or more persons who do not have the same interest, he is responsible for fortuitous events until delivery.', 2),
  ('RFBT', 'Law on Obligations',
   'On May 1, Dina signed a document stating only: ''I promise to pay Ben P50,000.'' The obligation is:',
   'Pure, and therefore demandable at once', 'Conditional, demandable only upon Ben''s demand in court', 'With a period, demandable after a reasonable time', 'Void for lack of a due date',
   0, 'An obligation whose performance does not depend upon a future or uncertain event or a past event unknown to the parties, and which states no period, is pure and demandable at once (Art. 1179).', 1),
  ('RFBT', 'Law on Obligations',
   'Lola Carmen bound herself to give her grandson Marco a monthly allowance until he passes the CPALE. Marco''s passing of the CPALE is:',
   'A suspensive condition', 'A period, because it is sure to come', 'A resolutory condition, because its fulfillment extinguishes the obligation to give the allowance', 'A purely potestative condition that voids the obligation',
   2, 'The allowance is demandable at once but ceases upon the happening of the uncertain event. A condition whose fulfillment extinguishes rights already acquired is resolutory (Art. 1181).', 2),
  ('RFBT', 'Law on Obligations',
   'Carlo owes Ana P100,000. At Carlo''s initiative and with Ana''s consent, Dina agreed to assume the debt and Ana released Carlo. This substitution of debtor is known as:',
   'Expromision', 'Objective or real novation', 'Legal subrogation', 'Delegacion',
   3, 'In delegacion, the debtor offers and the creditor accepts a third person who consents to substitute the original debtor. In expromision, the initiative comes from a third person without the debtor''s participation.', 3),
  ('RFBT', 'Law on Obligations',
   'Ben promised to pay Carlo P200,000 ''if I feel like paying.'' The conditional obligation is:',
   'Valid, because conditions are allowed', 'Void, because the condition''s fulfillment depends upon the sole will of the debtor', 'Valid, because it is facultative', 'Valid but unenforceable until ratified',
   1, 'Under Art. 1182, when the fulfillment of the condition depends upon the sole will of the debtor, the conditional obligation is void.', 2),
  ('RFBT', 'Law on Obligations',
   'Ana promised Ben a bonus if Ben finishes constructing her warehouse by December 1. In November, Ana barred Ben''s workers from the site, making timely completion impossible. The condition is:',
   'Deemed fulfilled, because the obligor voluntarily prevented its fulfillment', 'Extinguished, releasing Ana from the bonus', 'Merely suspended until the parties agree', 'Void, rendering the whole obligation ineffective',
   0, 'Art. 1186 provides that the condition shall be deemed fulfilled when the obligor voluntarily prevents its fulfillment, so Ben may demand the bonus.', 2),
  ('RFBT', 'Law on Obligations',
   'When an obligation fixes a period for its performance, the period is presumed to have been established for the benefit of:',
   'The debtor only, so he may pay at any time', 'The creditor only, so he may demand at any time', 'Both the creditor and the debtor', 'Whichever party first invokes it',
   2, 'Under Art. 1196, whenever a period is designated, it is presumed established for the benefit of both parties, unless the tenor of the obligation or other circumstances show a contrary intent.', 1),
  ('RFBT', 'Law on Obligations',
   'The debtor loses the benefit of the period in all of the following cases, EXCEPT:',
   'When he becomes insolvent after the obligation was contracted, unless he gives a guaranty or security', 'When he fails to furnish the guaranties or securities he promised', 'When by his own acts he impairs the guaranties or securities given', 'When his business merely suffers a temporary drop in sales',
   3, 'Art. 1198 enumerates the instances when the debtor loses the right to make use of the period. Ordinary business reverses, without insolvency or impairment of securities, are not among them.', 2),
  ('RFBT', 'Law on Obligations',
   'In an alternative obligation, the right to choose which prestation shall be performed belongs to:',
   'The creditor in all cases', 'The debtor, unless the right of choice has been expressly granted to the creditor', 'The courts, upon petition', 'Both parties acting jointly',
   1, 'Under Art. 1200, the right of choice in alternative obligations belongs to the debtor, unless it has been expressly granted to the creditor.', 2),
  ('RFBT', 'Law on Obligations',
   'Dina bound herself to deliver her carabao to Ben, with a stipulation that she may deliver her horse as a substitute. Before any substitution was made, the horse died through Dina''s negligence. What is the effect on the obligation?',
   'None; Dina must still deliver the carabao, and she incurs no liability for the loss of the substitute', 'The obligation is totally extinguished', 'Dina is liable for damages for the loss of the substitute', 'Ben may demand the value of the horse instead',
   0, 'The obligation is facultative. Under Art. 1206, the loss or deterioration of the thing intended as a substitute, before the substitution is made, does not render the obligor liable; only the principal thing is due.', 3),
  ('RFBT', 'Law on Obligations',
   'Ana, Ben, and Carlo borrowed P90,000 from Dina under a promissory note that is silent on the nature of their liability. How much may Dina collect from Ben?',
   'P90,000', 'P45,000', 'P30,000 only', 'Nothing, until Ana and Carlo are first sued',
   2, 'Solidarity is never presumed. When two or more debtors concur in one obligation and the contract is silent, the obligation is presumed joint, so each debtor answers only for his proportionate share (Arts. 1207-1208).', 1),
  ('RFBT', 'Law on Obligations',
   'Ana, Ben, and Carlo are solidary debtors of Dina for P120,000 in equal shares. Ana paid Dina the entire P120,000 at maturity. Ana may recover:',
   'Nothing, because payment extinguished everything', 'P120,000 from either Ben or Carlo', 'P60,000 from Ben only', 'P40,000 each from Ben and Carlo, with interest from the time of payment',
   3, 'Under Art. 1217, the solidary debtor who pays may claim from his co-debtors only the share which corresponds to each, with interest for the payment already made.', 3),
  ('RFBT', 'Law on Obligations',
   'X, Y, and Z solidarily owe W P90,000 in equal shares. W gratuitously remitted X''s P30,000 share. How much may W still collect from Y alone?',
   'P90,000', 'P60,000', 'P30,000', 'P45,000',
   1, 'Remission of the share of one solidary debtor reduces the total obligation by that share, but the remaining balance of P60,000 may still be collected in full from any remaining solidary debtor.', 3),
  ('RFBT', 'Law on Obligations',
   'A, B, and C are solidary debtors of D for P150,000 in equal shares. C became insolvent, and B paid D the full P150,000. How much may B collect from A?',
   'P75,000', 'P50,000', 'P100,000', 'P25,000',
   0, 'Under Art. 1217, the share of the insolvent co-debtor is borne proportionately by the others. B may recover A''s P50,000 share plus P25,000, which is A''s proportionate share of insolvent C''s P50,000.', 3),
  ('RFBT', 'Law on Obligations',
   'A construction contract contains a P100,000 penalty clause for delay, with no stipulation allowing additional damages. The contractor incurred delay without fraud, causing the owner P150,000 in actual losses. The owner may recover:',
   'P150,000 as proven actual damages', 'P250,000, both the penalty and actual damages', 'Only the P100,000 penalty, which substitutes for the indemnity for damages and interest', 'P50,000, the excess of the loss over the penalty',
   2, 'Under Art. 1226, the penalty substitutes the indemnity for damages and payment of interests in case of breach, absent a contrary stipulation, refusal to pay the penalty, or fraud by the debtor.', 2),
  ('RFBT', 'Law on Obligations',
   'Ben paid his P40,000 debt directly to Marco, his 16-year-old creditor. Marco squandered P25,000 and deposited P15,000 in his savings account. Ben''s payment is valid to the extent of:',
   'P40,000', 'Zero; payment to a minor is totally void', 'P25,000', 'P15,000',
   3, 'Payment to an incapacitated creditor is valid only insofar as it has redounded to his benefit or insofar as he has kept the thing delivered (Art. 1241). Only the P15,000 saved benefited Marco.', 2),
  ('RFBT', 'Law on Obligations',
   'Unable to pay his P500,000 loan in cash, Carlo, with the creditor''s consent, conveyed his delivery van to the creditor in full settlement of the debt. This mode of extinguishment is:',
   'Novation by change of object requiring a new contract in writing', 'Dation in payment, which is governed by the law on sales', 'Consignation', 'Condonation',
   1, 'In dacion en pago, property is alienated to the creditor in satisfaction of a debt in money; the law on sales governs because it is in effect a sale where the debt is the price (Art. 1245).', 2),
  ('RFBT', 'Law on Obligations',
   'Dina owes Ben three separate debts, all of them due. She tenders P20,000, which cannot cover all of them. Who has the first right to designate the debt to which the payment shall be applied?',
   'Dina, the debtor, at the time of making the payment', 'Ben, the creditor, in all cases', 'The law, which automatically applies it to the most onerous debt', 'The court, upon motion',
   0, 'Under Art. 1252, the debtor who has various debts of the same kind to a single creditor may declare, at the time of payment, to which of them the payment is to be applied.', 2),
  ('RFBT', 'Law on Obligations',
   'Carlo tendered the exact amount due to Ana, who refused to accept it without just cause. Carlo then simply kept the money in his office vault. Is Carlo''s obligation extinguished?',
   'Yes, because a valid tender of payment by itself extinguishes the obligation', 'Yes, because Ana''s refusal was unjustified', 'No; tender of payment must generally be followed by consignation with the proper judicial authority to release the debtor', 'No, because tender must always be made through a bank',
   2, 'Tender of payment alone does not extinguish the obligation. To be released, the debtor must consign the amount in court after refusal, with notice to interested parties before and after consignation (Arts. 1256-1258).', 3),
  ('RFBT', 'Law on Obligations',
   'Ben obliged himself to deliver 100 cavans of ordinary white rice to Ana. His entire warehouse stock was destroyed by fire without his fault. Ben is:',
   'Released, because of the fortuitous event', 'Released, because the object of the obligation was lost', 'Liable only for damages, not delivery', 'Still bound to deliver, because a generic thing never perishes',
   3, 'The obligation is generic, and under the principle genus nunquam perit, the loss of the debtor''s particular stock does not extinguish an obligation to deliver a generic thing (Art. 1263).', 1),
  ('RFBT', 'Law on Obligations',
   'Dina deposited P50,000 in cash with Carlo as depositary. Carlo happens to be Dina''s creditor for a matured P50,000 loan. May Carlo refuse to return the deposit by setting up legal compensation?',
   'Yes, since all the requisites of legal compensation are present', 'No; compensation cannot be set up by the depositary against the obligation to return the thing deposited', 'Yes, but only as to one-half of the deposit', 'No, because compensation never applies to money obligations',
   1, 'Under Art. 1287, compensation shall not be proper when one of the debts arises from a depositum or from the obligations of a depositary, as against the depositor''s claim.', 2),
  ('RFBT', 'Law on Contracts',
   'A contract between Ben and an insurance company contains a clear and deliberate stipulation conferring a benefit upon Dina, a third person. Dina communicated her acceptance to the obligor before the stipulation was revoked. May Dina demand its fulfillment?',
   'No, because of the principle of relativity of contracts', 'No, unless she gave a separate consideration', 'Yes; this is a stipulation pour autrui, and she accepted before revocation', 'Yes, but only by suing through the contracting parties',
   2, 'A third person may demand fulfillment of a stipulation in his favor if it is a deliberate conferment of a favor, not a mere incidental benefit, and he communicated his acceptance before revocation (Art. 1311).', 2),
  ('RFBT', 'Law on Contracts',
   'A loan agreement stipulates that the lender may, at its sole discretion and without the borrower''s consent, increase the interest rate at any time. The escalation stipulation is:',
   'Void, for violating the principle of mutuality of contracts', 'Valid, under the autonomy of contracts', 'Voidable at the option of the borrower', 'Unenforceable until ratified by the borrower',
   0, 'Under Art. 1308, the contract must bind both parties; its validity or compliance cannot be left to the will of one of them. One-sided escalation clauses violate mutuality and are void.', 2),
  ('RFBT', 'Law on Contracts',
   'Under the principle of autonomy, the contracting parties may establish such stipulations as they may deem convenient, provided they are not contrary to:',
   'The wishes of their respective creditors', 'Law, morals, good customs, public order, or public policy', 'The customs of the place of execution only', 'Existing jurisprudence only',
   1, 'Art. 1306 allows parties to establish any stipulations, clauses, terms and conditions, provided they are not contrary to law, morals, good customs, public order, or public policy.', 1),
  ('RFBT', 'Law on Contracts',
   'The stage of a contract at which the offer and the acceptance concur on the object and the cause is called:',
   'Negotiation or preparation', 'Consummation', 'Generation', 'Perfection',
   3, 'Contracts pass through preparation (negotiation), perfection (birth, upon meeting of minds), and consummation (performance). The concurrence of offer and acceptance marks perfection.', 1),
  ('RFBT', 'Law on Contracts',
   'On March 1, Ana mailed her letter accepting Ben''s written offer to sell. Ben received and read the letter on March 5. Under the Civil Code, the contract was perfected on:',
   'March 1, when the acceptance was mailed', 'The date the letter was postmarked by the post office', 'March 5, when knowledge of the acceptance came to Ben', 'Only upon Ben''s written confirmation of receipt',
   2, 'Under Art. 1319, acceptance by letter or telegram does not bind the offeror except from the time it came to his knowledge. The Civil Code follows the cognition theory.', 2),
  ('RFBT', 'Law on Contracts',
   'Carlo bought a watch only because the seller falsely represented that it was a genuine Swiss original; without that misrepresentation Carlo would never have bought it. The fraud is:',
   'Dolo causante, which makes the contract voidable and entitles Carlo to damages', 'Dolo incidente, which gives rise to damages only', 'A mere expression of opinion that does not affect validity', 'Fraud in the performance of an obligation',
   0, 'Causal fraud (dolo causante) is that without which the other party would not have consented; it vitiates consent and makes the contract voidable (Arts. 1338, 1344). Incidental fraud merely obliges the payment of damages.', 2),
  ('RFBT', 'Law on Contracts',
   'In drawing up the statement of account attached to their contract, the parties committed a simple arithmetical error that overstated the balance due. The mistake:',
   'Voids the entire contract', 'Does not vitiate consent and gives rise only to the correction of the account', 'Makes the contract voidable', 'Makes the contract unenforceable',
   1, 'Under Art. 1331, a simple mistake of account gives rise only to its correction; it is not the substantial mistake that vitiates consent.', 2),
  ('RFBT', 'Law on Contracts',
   'To collect a valid and overdue debt, Ana told Ben: ''Sign this promissory note covering your debt, or I will file a collection case against you.'' Ben signed. Was Ben''s consent vitiated by intimidation?',
   'Yes, because fear of litigation is intimidation', 'Yes, if Ben is of timid disposition', 'No, because intimidation requires actual physical force', 'No; a threat to enforce one''s claim through competent authority, when the claim is just or legal, does not vitiate consent',
   3, 'Under Art. 1335, a threat to enforce a just or legal claim through competent authority does not constitute intimidation that vitiates consent.', 2),
  ('RFBT', 'Law on Contracts',
   'The spouses Reyes executed a deed of absolute sale of their lot in favor of their daughter, but the evidence shows they really intended a donation, and all the formalities for a valid donation were observed. The contract is:',
   'Absolutely simulated and therefore void', 'Void, because no price was actually paid', 'Relatively simulated; the parties are bound by the donation they really intended', 'Automatically rescissible at the instance of creditors',
   2, 'In relative simulation, the parties conceal their true agreement. The contract binds them to the real agreement when it does not prejudice third persons and is not contrary to law (Art. 1346).', 3),
  ('RFBT', 'Law on Contracts',
   'Ben, whose wealthy father is still alive, sold to Carlo his expected share in his father''s estate. As a general rule, the sale is:',
   'Void, because future inheritance cannot be the object of a contract', 'Valid, as a sale of future property', 'Voidable at the instance of the father', 'Valid but unenforceable against the other heirs',
   0, 'Under Art. 1347, no contract may be entered into upon future inheritance except in cases expressly authorized by law. The sale of a mere expectancy in the estate of a living person is void.', 1),
  ('RFBT', 'Law on Contracts',
   'Dina bought a condominium unit solely so she could live near her office. She later resigned from her job. May she have the sale annulled because her purpose was frustrated?',
   'Yes, because the cause of the contract ceased to exist', 'No; her purpose was a mere motive, which is distinct from the cause and does not affect the validity of the contract', 'Yes, provided the seller knew of her purpose', 'No, unless the developer consents to the annulment',
   1, 'Cause is the essential and immediate reason for the contract (for the buyer, acquisition of the unit), while motive is the personal or private reason. Falsity or failure of motive does not affect validity (Art. 1351).', 2),
  ('RFBT', 'Law on Contracts',
   'As a general rule, lesion or gross inadequacy of price in a contract:',
   'Voids the contract automatically', 'Always makes the contract rescissible', 'Makes the contract voidable', 'Does not invalidate the contract, except in cases specified by law or when there has been fraud, mistake, or undue influence',
   3, 'Under Arts. 1355 and 1470, lesion or inadequacy of cause or price does not, of itself, invalidate a contract, save in cases specified by law (such as Art. 1381) or where consent was vitiated.', 1),
  ('RFBT', 'Law on Contracts',
   'As a general rule, contracts are obligatory:',
   'Only when reduced to writing', 'Only when notarized', 'In whatever form they may have been entered into, provided all the essential requisites for validity are present', 'Only when registered with the proper registry',
   2, 'Art. 1356 embodies the spirit of consensuality: form is generally not required for validity, except when the law requires a specific form for validity or enforceability.', 1),
  ('RFBT', 'Law on Contracts',
   'Lolo Andres orally donated a parcel of land to his grandson Marco, who immediately took possession and introduced improvements. The donation is:',
   'Void, because a donation of an immovable must be in a public instrument to be valid', 'Valid, because possession was actually delivered', 'Merely unenforceable under the Statute of Frauds', 'Voidable within four years',
   0, 'For donations of immovable property, Art. 749 requires a public instrument for validity, not mere enforceability. The form is essential, so an oral donation of land is void even if possession is delivered.', 2),
  ('RFBT', 'Law on Contracts',
   'Which of the following agreements is NOT covered by the Statute of Frauds?',
   'An agreement that by its terms is not to be performed within one year from its making', 'A simple loan of P100,000 payable within 30 days', 'A sale of real property or an interest therein', 'A special promise to answer for the debt, default, or miscarriage of another',
   1, 'The Statute of Frauds (Art. 1403[2]) enumerates specific agreements that must be in writing to be enforceable. A simple loan of money, regardless of amount, is not among them.', 2),
  ('RFBT', 'Law on Contracts',
   'Ben orally sold his lot to Carlo, received half of the price, and allowed Carlo to occupy and fence the lot. Ben later refused to execute the deed, invoking the Statute of Frauds. Is Ben''s defense tenable?',
   'Yes, because a sale of realty must always be in writing', 'Yes, unless Carlo first pays the price in full', 'No, because the Statute of Frauds covers only sales of goods', 'No; the Statute of Frauds applies only to executory contracts, and this contract has been partially executed',
   3, 'The Statute of Frauds is inapplicable to contracts that have been totally or partially performed, since the performance itself is evidence of the agreement. Partial payment and delivery of possession take the sale out of the Statute.', 3),
  ('RFBT', 'Law on Contracts',
   'During trial involving an oral agreement covered by the Statute of Frauds, the defendant cross-examined the plaintiff''s witnesses on the terms of the agreement without objecting to the oral evidence. The contract is:',
   'Still unenforceable despite the trial', 'Void for lack of written form', 'Deemed ratified by the failure to object to the presentation of oral evidence', 'Rescissible at the defendant''s option',
   2, 'Under Art. 1405, contracts infringing the Statute of Frauds are ratified by the failure to object to the presentation of oral evidence to prove them, or by the acceptance of benefits under them.', 2),
  ('RFBT', 'Law on Contracts',
   'An action for reformation of an instrument requires all of the following requisites, EXCEPT:',
   'That there was no meeting of the minds between the parties', 'That the instrument fails to express the true intention of the parties', 'That the failure is due to mistake, fraud, inequitable conduct, or accident', 'That there is a valid and existing agreement between the parties',
   0, 'Reformation presupposes a meeting of the minds; only the instrument fails to express the true agreement (Art. 1359). If there was no meeting of minds at all, the proper remedy is annulment, not reformation.', 2),
  ('RFBT', 'Law on Contracts',
   'In which of the following cases is reformation of the instrument NOT available?',
   'Where mutual mistake caused the deed to state the wrong lot number', 'Where the instrument is a simple donation inter vivos wherein no condition is imposed', 'Where the instrument states an absolute sale although the parties intended an equitable mortgage', 'Where the fraud of one party caused the writing to omit an agreed stipulation',
   1, 'Under Art. 1366, there shall be no reformation in cases of simple donations inter vivos wherein no condition is imposed, wills, and when the real agreement is void.', 3),
  ('RFBT', 'Law on Contracts',
   'A guardian sold the ward''s parcel of land worth P1,000,000 for only P700,000, without court approval of the price. With respect to the lesion, the contract is:',
   'Void from the beginning', 'Voidable for vitiated consent', 'Unenforceable for lack of authority', 'Rescissible, because the ward suffered lesion by more than one-fourth of the value',
   3, 'Under Art. 1381(1), contracts entered into by guardians are rescissible whenever the ward suffers lesion by more than one-fourth of the value of the things which are the object thereof. The lesion here is 30%.', 2),
  ('RFBT', 'Law on Contracts',
   'Carlo, who is heavily indebted, donated his only remaining asset to his cousin to defeat the claim of his creditor Ana. May Ana immediately file an action to rescind the donation?',
   'Yes, because accion pauliana is a primary and independent remedy', 'Yes, at any time within ten years', 'No; rescission is a subsidiary remedy available only after Ana has exhausted all other legal means to satisfy her claim', 'No, because donations can never be rescinded',
   2, 'The accion pauliana to rescind contracts in fraud of creditors cannot be instituted except when the party suffering damage has no other legal means to obtain reparation (Arts. 1383, 1387).', 3),
  ('RFBT', 'Law on Contracts',
   'Through intimidation, Ben forced Dina to sign a contract in 2022. The intimidation ceased in 2023. Until when may Dina bring the action for annulment?',
   'Within four years from the time the intimidation ceased, or until 2027', 'Within four years from the signing of the contract, or until 2026', 'Within ten years from the signing of the contract', 'At any time, because the contract is void',
   0, 'Voidable contracts must be annulled within four years, counted from the time the intimidation, violence, or undue influence ceases (Art. 1391).', 2),
  ('RFBT', 'Law on Contracts',
   'Marco, without any authority from Ana, signed a contract selling Ana''s land in her name. The contract is:',
   'Void and cannot produce any effect whatsoever', 'Unenforceable, unless ratified expressly or impliedly by Ana', 'Voidable within four years', 'Rescissible for fraud of creditors',
   1, 'Contracts entered into in the name of another by one without authority or in excess of authority are unenforceable, unless ratified by the person on whose behalf they were executed (Art. 1403[1]).', 2),
  ('RFBT', 'Law on Contracts',
   'Ana and Ben knowingly entered into a contract for the delivery of smuggled cigarettes. Ana paid the price but Ben never delivered. May Ana recover what she paid?',
   'Yes, to prevent unjust enrichment', 'Yes, provided she sues within four years', 'Yes, because Ben was the first to breach', 'No; both being in pari delicto in an illegal contract, the law leaves them as they are and neither may recover',
   3, 'When the nullity proceeds from the illegality of the cause or object and both parties are equally at fault, they have no action against each other (Art. 1411). The courts leave them where they are.', 3),
  ('RFBT', 'Law on Contracts',
   'Which of the following contracts is VOID?',
   'An oral sale of a parcel of land', 'A sale of land entered into by a 17-year-old seller', 'A contract for the sale of prohibited drugs', 'A guardian''s sale of the ward''s property where the ward suffered lesion of one-third',
   2, 'A contract whose object is contrary to law is void and inexistent (Art. 1409). The oral sale of land is merely unenforceable, the minor''s sale is voidable, and the guardian''s sale with lesion over one-fourth is rescissible.', 1),
  ('RFBT', 'Sales',
   'Which combination correctly describes the nature of a contract of sale?',
   'Real, unilateral, gratuitous, and aleatory', 'Consensual, bilateral, onerous, and commutative', 'Consensual, unilateral, onerous, and aleatory', 'Real, bilateral, gratuitous, and commutative',
   1, 'A sale is perfected by mere consent (consensual), creates reciprocal obligations (bilateral), involves valuable consideration (onerous), and the parties contemplate roughly equivalent values (commutative).', 1),
  ('RFBT', 'Sales',
   'Ana hands Ben 5,000 pesos described in their signed receipt as part of the purchase price for Ben lot. Under Art. 1482, this payment is presumed to be:',
   'Earnest money, proof of a perfected sale and part of the price', 'Option money giving Ana time to decide whether to buy', 'A loan that Ben must later return to Ana', 'A mere deposit that does not bind either party',
   0, 'Art. 1482 states that whenever earnest money is given in a contract of sale, it is considered part of the price and proof of the perfection of the contract; option money, by contrast, is consideration for an option and is separate from the price.', 1),
  ('RFBT', 'Sales',
   'Carlo grants Dina a 30-day option to buy his car, but Dina pays nothing for that option. Before the period ends Carlo sells the car to someone else. Dina sues. Will she succeed in compelling Carlo to honor the option?',
   'Yes, because every option period is automatically binding once granted in writing', 'Yes, because the 30-day promise is itself sufficient consideration', 'No, because an option unsupported by a consideration separate from the price is not binding on the offeror', 'No, because options over movables are void as a matter of law',
   2, 'An option contract requires a consideration distinct from the purchase price to bind the offeror; without it, the offeror may withdraw the offer before acceptance despite the stated period.', 2),
  ('RFBT', 'Sales',
   'A key feature distinguishing a contract to sell from a contract of sale is that in a contract to sell:',
   'Ownership passes to the buyer upon perfection regardless of payment', 'Delivery is legally impossible until a court approves it', 'The buyer never acquires any right to the thing sold', 'Ownership is reserved by the seller until full payment of the price',
   3, 'In a contract to sell, the seller expressly reserves title and ownership does not pass until the buyer fully pays the price; in a contract of sale ownership passes upon delivery, with nonpayment giving rise to rescission rather than automatic non-transfer.', 2),
  ('RFBT', 'Sales',
   'In a contract to sell, the buyer fails to pay the full price on the agreed date. What is the legal effect?',
   'Ownership that already passed must be judicially rescinded', 'The seller is compelled to deliver title and merely sue for the balance', 'The suspensive condition is not fulfilled, so the obligation to convey ownership never arises', 'The contract is converted by law into a lease',
   2, 'Full payment in a contract to sell is a positive suspensive condition; failure to pay is not a breach but an event that prevents the seller obligation to convey title from becoming demandable.', 2),
  ('RFBT', 'Sales',
   'The thing that is the object of a perfected sale is lost entirely through a fortuitous event BEFORE delivery but AFTER perfection. As a general rule, who bears the loss?',
   'The seller, who must restore any amount received and cannot demand the price', 'The loss is borne by whoever was negligent, regardless of perfection', 'Both parties equally share the loss', 'The buyer, who must still pay the price under the res perit domino exception in sales',
   3, 'Under the rules on loss in sale, where a determinate thing is lost after perfection but before delivery without the seller fault, the buyer generally still bears the risk and must pay the price, an exception to res perit domino.', 3),
  ('RFBT', 'Sales',
   'If the specific thing sold is entirely lost at the very moment of perfection because, unknown to the parties, it had already perished, the contract is:',
   'Valid but rescissible at the buyer option', 'Merely voidable for mistake', 'Inexistent and void for want of object', 'Valid, with the buyer bearing the loss',
   2, 'When the object has been entirely lost at the time of perfection, there is no object and the contract is void; if only partially lost, the buyer may withdraw or take the remainder with a proportionate price reduction.', 2),
  ('RFBT', 'Sales',
   'Ben sells the same parcel of registered land first to Ana and later to Carlo. Carlo, in good faith, registers his deed first while Ana merely took possession. Under Art. 1544, who owns the land?',
   'Ana, because she possessed before Carlo registered', 'Carlo, as the first to register in good faith', 'Whoever presents the oldest deed of sale', 'Both as co-owners in equal shares',
   1, 'For double sales of immovables, Art. 1544 awards ownership to the buyer who first registers in good faith; only absent registration does the law look to first possession in good faith, and then to the oldest title.', 2),
  ('RFBT', 'Sales',
   'Dina sells the same unregistered diamond ring first to Ana and then to Ben. Neither buyer registers anything. Ben takes actual possession in good faith before Ana does. Who owns the ring under Art. 1544?',
   'Ana, as the first buyer in time', 'Whoever holds the oldest receipt', 'Dina, since neither buyer registered', 'Ben, as the first to take possession in good faith',
   3, 'For movables, Art. 1544 gives ownership to the buyer who first takes possession in good faith; the first-in-time rule does not control when a later good-faith buyer obtains possession first.', 2),
  ('RFBT', 'Sales',
   'Two buyers of the same immovable both fail to register, and neither has taken possession. Under Art. 1544, ownership is awarded to:',
   'The buyer who paid the higher price', 'The seller, who may keep the land', 'Whichever buyer first demands delivery in court', 'The buyer who presents the oldest title, provided there is good faith',
   3, 'Art. 1544 hierarchy for immovables is: first registrant in good faith, then first possessor in good faith, and finally the person who presents the oldest title in good faith.', 2),
  ('RFBT', 'Sales',
   'Handing the buyer the keys to the warehouse where the sold goods are stored, enabling control, is an example of:',
   'Real or actual delivery', 'Traditio brevi manu', 'Constructive (symbolic) delivery', 'Quasi-traditio of incorporeal rights',
   2, 'Delivering keys to a place where movables are kept is a recognized form of constructive or symbolic delivery, transferring control without physical handing over of each item.', 1),
  ('RFBT', 'Sales',
   'Ana was already leasing Ben painting when she bought it from him; she simply continues holding it, now as owner. This mode of delivery is called:',
   'Traditio brevi manu', 'Constitutum possessorium', 'Traditio longa manu', 'Quasi-traditio',
   0, 'Traditio brevi manu occurs when one already in possession by another title (here, as lessee) continues to possess but now as owner; constitutum possessorium is the reverse, where the seller stays in possession in a new capacity.', 2),
  ('RFBT', 'Sales',
   'A breach of the implied warranty against hidden defects must be enforced through a redhibitory action that prescribes within:',
   'Four years from discovery of the defect', 'Six months from delivery of the thing', 'One year from perfection of the sale', 'Ten years from the date of the contract',
   1, 'The action arising from hidden defects (redhibitory action) prescribes six months from the delivery of the thing sold; this short period distinguishes it from ordinary breach actions.', 1),
  ('RFBT', 'Sales',
   'For the seller warranty against eviction to be enforced, which requisite is essential?',
   'The buyer voluntarily surrenders the thing to a claimant without suit', 'The deprivation arises from a cause created after the sale by the buyer', 'The buyer is deprived of the thing by a final judgment based on a right prior to the sale', 'The seller expressly promised the thing would never decline in value',
   2, 'Warranty against eviction requires that the buyer be deprived, by final judgment, of the whole or part of the thing on the basis of a right existing prior to the sale; voluntary surrender or post-sale causes do not trigger it.', 3),
  ('RFBT', 'Sales',
   'Carlo sold a motorcycle to Dina payable in 12 monthly installments, secured by a chattel mortgage on the motorcycle. Dina defaults; Carlo forecloses the chattel mortgage and the proceeds fall short. Under the Recto Law, may Carlo still recover the deficiency?',
   'No, foreclosure of the chattel mortgage bars any further action for the deficiency', 'Yes, the deficiency is always recoverable in chattel mortgages', 'Yes, but only up to half of the unpaid balance', 'No, but Carlo may instead cancel the sale and also keep all installments',
   0, 'Under the Recto Law (Art. 1484), once the seller forecloses the chattel mortgage on personal property sold in installments, he cannot recover any unpaid balance; any contrary stipulation is void.', 3),
  ('RFBT', 'Sales',
   'Under the Maceda Law, a buyer of residential realty on installments who has paid at least two years of installments and then defaults is entitled to:',
   'Immediate forfeiture of all payments with no grace period', 'A full refund of one hundred percent of payments in all cases', 'A grace period of one month for every year of installments paid, exercisable once a year', 'Automatic transfer of title despite the default',
   2, 'The Maceda Law grants a buyer who has paid at least two years of installments a grace period of one month for every year paid (exercisable once a year) and, on cancellation, a cash surrender value of the payments.', 1),
  ('RFBT', 'Sales',
   'Which badge below indicates that a purported sale with right to repurchase is really an equitable mortgage under the Civil Code?',
   'The price of the supposed sale is unusually inadequate', 'The seller has fully surrendered possession to the buyer', 'The deed expressly waives any right to repurchase', 'The buyer immediately paid in full and registered title',
   0, 'Art. 1602 lists indicators that a sale with right to repurchase is really an equitable mortgage, including an unusually inadequate price and the vendor remaining in possession; these signal a loan secured by the property.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'A stipulation allowing the creditor to automatically appropriate the thing given as security upon the debtor default, without foreclosure, is:',
   'Valid as a dacion en pago clause', 'Void as a prohibited pactum commissorium', 'Valid because freely agreed upon by the parties', 'Voidable only at the debtor option',
   1, 'Pactum commissorium, where the creditor automatically appropriates the security on default, is prohibited and void in pledge, mortgage, and antichresis; the creditor must instead foreclose and sell.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'Which characteristic is common to pledge, real mortgage, and antichresis?',
   'They are principal contracts that stand on their own', 'They transfer ownership of the security to the creditor', 'They are accessory contracts that depend on a principal obligation', 'They require no debt to be valid',
   2, 'Security contracts like pledge, mortgage, and antichresis are accessory: their existence and validity depend on a valid principal obligation they secure; they do not transfer ownership of the thing.', 1),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'Ana pledges her bracelet to Ben to secure a loan but keeps the bracelet in her own drawer. Is the pledge perfected?',
   'Yes, because pledges are perfected by mere consent', 'No, because bracelets cannot be pledged', 'Yes, provided the loan was in writing', 'No, because a pledge is a real contract that requires delivery of the thing to the creditor',
   3, 'A pledge is a real contract perfected only by the delivery of the thing pledged to the creditor or a third person by agreement; without delivery, no pledge arises.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'For a pledge to bind third persons, the law additionally requires that:',
   'A description of the thing and the date of the pledge appear in a public instrument', 'The pledge be annotated on a land title', 'The debtor publish a notice in a newspaper', 'The creditor take an oath before a notary',
   0, 'To affect third persons, a pledge must appear in a public instrument showing a description of the thing pledged and the date of the pledge; delivery alone binds only the parties.', 1),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'After a pledged thing is sold at public auction, the proceeds are less than the debt. Absent any stipulation, may the pledgee recover the deficiency from the debtor?',
   'Yes, the deficiency is always recoverable like in a real mortgage', 'Yes, but only half of the deficiency', 'No, the sale extinguishes the principal obligation even if the proceeds fall short', 'No, and the pledgee must also refund the difference to the debtor',
   2, 'In pledge, if the proceeds of the public auction are less than the debt, the creditor is not entitled to recover the deficiency notwithstanding any contrary stipulation; conversely any excess belongs to the debtor unless otherwise stipulated.', 3),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'In a real estate mortgage, ownership of the mortgaged immovable:',
   'Transfers to the mortgagee upon execution of the deed', 'Passes to the registry of deeds until the debt is paid', 'Is held jointly by mortgagor and mortgagee', 'Remains with the mortgagor, who only encumbers it as security',
   3, 'A real estate mortgage merely creates a real right and lien over the property; the mortgagor retains ownership and possession, and the mortgagee acquires only the right to foreclose upon default.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'Carlo real estate mortgage is foreclosed and the auction proceeds are insufficient to cover the debt. May the mortgagee recover the deficiency?',
   'No, recovery of any deficiency is barred as in pledge', 'No, the mortgagee must keep silent and absorb the loss', 'Yes, but only if a chattel mortgage was also constituted', 'Yes, in a real estate mortgage the creditor may sue for the deficiency',
   3, 'Unlike pledge, a real estate mortgage allows the creditor to recover the deficiency after foreclosure, since mortgage law contains no rule extinguishing the balance.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'A real estate mortgage binds third persons only when it is:',
   'Registered in the Registry of Property', 'Signed before two witnesses', 'Delivered physically to the mortgagee', 'Published once in a newspaper of general circulation',
   0, 'While a mortgage is valid between the parties even if unregistered, it binds and prejudices third persons only from the time it is registered in the Registry of Property.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'Following an extrajudicial foreclosure of a real estate mortgage under Act No. 3135, the mortgagor right of redemption generally lasts:',
   'Ninety days from the auction date', 'One year from the registration of the certificate of sale', 'Until the mortgagee resells the property', 'There is no redemption in extrajudicial foreclosure',
   1, 'In extrajudicial foreclosure under Act No. 3135, the mortgagor has a right of redemption of one year reckoned from the registration of the certificate of sale; in judicial foreclosure, what exists is the equity of redemption before confirmation.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'Which document is essential to the validity of a chattel mortgage and distinguishes it from a pledge?',
   'A public auction notice posted in advance', 'A deposit of the chattel with a third person', 'An affidavit of good faith stating the mortgage is made to secure a just obligation', 'A guarantor solidary undertaking',
   2, 'A chattel mortgage requires an affidavit of good faith attesting that it is made to secure a just and valid obligation; the chattel stays with the mortgagor, unlike in pledge where delivery is required.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'Dina is a guarantor, not a surety, for Ben debt to Ana. When Ben defaults, Ana sues Dina directly. Dina may:',
   'Be held solidarily liable immediately like a surety', 'Demand that the debt be cut in half', 'Refuse to pay forever because guaranty is gratuitous', 'Invoke the benefit of excussion and require Ana to first exhaust Ben property',
   3, 'A guarantor liability is subsidiary; by the benefit of excussion he can require the creditor to first exhaust the debtor properties before proceeding against him, a defense unavailable to a surety who is solidarily bound.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'The benefit of excussion is LOST and the guarantor becomes liable as if no such benefit existed when:',
   'The guarantor expressly renounces it or binds himself solidarily with the debtor', 'The principal obligation is merely reduced', 'The creditor sends a single demand letter', 'The debt is secured by a separate pledge',
   0, 'Excussion is lost when, among others, the guarantor renounces it, binds himself solidarily, the debtor is insolvent, or cannot be sued within the Philippines; mere reduction or demand does not remove it.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'A guarantor who pays the creditor after the debtor default is entitled to:',
   'Nothing, because guaranty is presumed gratuitous', 'Only the moral satisfaction of having helped', 'Indemnity and subrogation to the creditor rights against the debtor', 'Ownership of the secured property automatically',
   2, 'A guarantor who pays is subrogated to all the rights the creditor had against the debtor and may also claim indemnity covering the total amount of the debt, legal interest, and expenses.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'Ana is surety for Ben loan to Carlo. Carlo, without Ana consent, grants Ben an extension of time to pay. The effect on Ana is that she is:',
   'Still fully bound because sureties can never be released', 'Released from the suretyship by the extension granted without her consent', 'Bound only for half the obligation', 'Converted into a mere guarantor',
   1, 'An extension of time for payment granted by the creditor to the debtor without the consent of the surety extinguishes the suretyship, because it varies the obligation the surety agreed to answer for.', 2),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'In antichresis, the creditor who receives the fruits of the debtor immovable must apply them:',
   'First to the interest, if owing, and then to the principal', 'Entirely to the principal before any interest', 'Only to the creditor own profit', 'To taxes alone and never to the debt',
   0, 'In antichresis the creditor acquires the right to receive the fruits of the immovable, obliged to apply them first to the interest, if owing, and thereafter to the principal of the credit.', 1),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'A contract of antichresis is void unless:',
   'The amount of the principal and the interest are specified in writing', 'It is registered within thirty days', 'The fruits are delivered to a notary', 'The debtor signs three copies',
   0, 'The Civil Code requires that the amount of the principal and of the interest in an antichresis be specified in writing; otherwise the contract of antichresis is void.', 1),
  ('RFBT', 'Credit Transactions: Pledge, Mortgage & Guaranty',
   'The benefit of division applies when:',
   'A single guarantor secures multiple debts', 'The debtor divides the collateral', 'The creditor splits the debt among banks', 'There are several guarantors of the same debtor for the same debt, limiting each to his share',
   3, 'Where there are several guarantors of one debtor for the same debt, the obligation is divided among them, and the creditor can claim from each only the share for which that guarantor is liable (benefit of division).', 2),
  ('RFBT', 'Negotiable Instruments',
   'An instrument states: Pay to the order of Ana 10,000 pesos out of the proceeds of the sale of my car. Under Section 1, the instrument is:',
   'Negotiable, because a payee and a sum certain are named', 'Non-negotiable, because the order to pay is not unconditional but limited to a particular fund', 'Negotiable, because it is payable to order', 'Non-negotiable, only because no date appears',
   1, 'An order to pay solely out of a particular fund makes the promise conditional and destroys negotiability; merely indicating the account to be debited or reimbursed, however, does not.', 3),
  ('RFBT', 'Negotiable Instruments',
   'A note promising to pay 50,000 pesos with interest at 12 percent per annum and 25 percent attorney fees in case of suit:',
   'Still carries a sum certain and is negotiable', 'Loses negotiability because the total cannot be computed in advance', 'Is non-negotiable because attorney fees are illegal', 'Is non-negotiable because interest is stated',
   0, 'Negotiability is not defeated by stated interest, installments, exchange, costs of collection, or attorney fees; the sum remains certain because it is determinable from the face of the instrument.', 2),
  ('RFBT', 'Negotiable Instruments',
   'An instrument is payable to bearer when, among others, it is:',
   'Payable to the order of a named, existing payee', 'Indorsed specially to a named indorsee', 'Payable to the order of a person known by the maker to be fictitious', 'Made payable to a specified person only',
   2, 'An instrument is payable to bearer when, among others, it is payable to a fictitious or non-existing person and that fact is known to the person making it so payable; such an instrument is negotiated by mere delivery.', 1),
  ('RFBT', 'Negotiable Instruments',
   'A bearer instrument is specially indorsed by the holder to Carlo. To further negotiate it, the next holder must:',
   'Obtain Carlo specific indorsement, because the special indorsement converted it to order', 'Simply deliver it, because an originally bearer instrument remains payable to bearer', 'Have the maker re-issue the note', 'Return it to the drawer for cancellation',
   1, 'Once bearer, always bearer: an instrument originally payable to bearer remains negotiable by mere delivery despite a subsequent special indorsement, although the special indorser is liable to those who take by delivery.', 3),
  ('RFBT', 'Negotiable Instruments',
   'The principal practical difference between negotiation and ordinary assignment of an instrument is that:',
   'Assignment passes better title than negotiation', 'Negotiation always requires a notarized deed', 'Only assignment can transfer a bearer instrument', 'A holder in due course by negotiation can take free of personal defenses, while an assignee takes subject to all defenses',
   3, 'Negotiation can vest a holder in due course with rights free from personal defenses, whereas an assignee merely steps into the assignor shoes and takes subject to all defenses available against the assignor.', 2),
  ('RFBT', 'Negotiable Instruments',
   'Ana indorses a note adding the words without recourse above her signature. This is a:',
   'Restrictive indorsement prohibiting further negotiation', 'Conditional indorsement subject to an event', 'Qualified indorsement that relieves her of secondary liability for nonpayment', 'Blank indorsement payable to bearer',
   2, 'A qualified indorsement (sans recourse / without recourse) makes the indorser a mere assignor of title and relieves her of the secondary liability to pay if the instrument is dishonored, though warranties remain.', 1),
  ('RFBT', 'Negotiable Instruments',
   'Which is a requisite for one to be a holder in due course?',
   'That the holder received it gratuitously after maturity', 'That the holder is the original payee only', 'That the holder took it in good faith and for value, complete and regular on its face, before maturity and without notice of any defect', 'That the holder notarized the instrument',
   2, 'A holder in due course must take an instrument complete and regular on its face, before maturity and without notice of prior dishonor, in good faith and for value, and without notice of any infirmity or defect in title.', 1),
  ('RFBT', 'Negotiable Instruments',
   'Under the shelter rule, a holder who is not himself a holder in due course but derives title through one:',
   'Can never enforce the instrument against personal defenses', 'Acquires the rights of a holder in due course, unless he was party to any fraud or illegality affecting the instrument', 'Must return the instrument to the original payee', 'Becomes a holder in due course in his own right for all purposes',
   1, 'The shelter rule lets a transferee who derives title through a holder in due course enjoy the latter rights, provided that transferee was not himself a party to any fraud or illegality affecting the instrument.', 2),
  ('RFBT', 'Negotiable Instruments',
   'Material alteration of a completed instrument is which kind of defense against a holder in due course?',
   'A purely personal defense that cannot be raised against anyone', 'A defense that voids the instrument entirely even for original tenor', 'No defense at all because alteration is always the maker fault', 'A real defense, but the holder in due course may enforce it according to its original tenor',
   3, 'Material alteration is a real defense; however, a holder in due course may still enforce the instrument according to its original tenor, recovering the amount as it stood before alteration.', 3),
  ('RFBT', 'Negotiable Instruments',
   'Which of the following is a REAL (absolute) defense available even against a holder in due course?',
   'Fraud in the inducement to sign', 'Failure of consideration', 'Want of delivery of a complete instrument', 'Minority of the maker, which is a defense available to the minor',
   3, 'Minority is a real defense available to the minor (rendering the obligation voidable as to him); fraud in inducement, failure of consideration, and want of delivery of a complete instrument are merely personal defenses.', 1),
  ('RFBT', 'Negotiable Instruments',
   'Ben fraudulently induces Ana to sign a note by misrepresenting its terms, then negotiates it to Carlo, a holder in due course. Against Carlo, Ana defense of fraud in inducement is:',
   'Unavailable, because fraud in the inducement is only a personal defense', 'Available, because all fraud is a real defense', 'Available only if Ana is a minor', 'Unavailable only if the note was post-dated',
   0, 'Fraud in the inducement is a personal defense that cannot be set up against a holder in due course; only fraud in factum (fraud as to the very character of the instrument) by a party without negligence is a real defense.', 3),
  ('RFBT', 'Negotiable Instruments',
   'Carlo delivers an INCOMPLETE and unsigned-as-to-amount note to Dina merely for safekeeping; she fills it in and negotiates it to a holder in due course. The defense of want of delivery of this incomplete instrument is:',
   'A personal defense usable only against ordinary holders', 'A real defense, so Carlo is not liable even to a holder in due course', 'No defense because incomplete instruments are void', 'A defense only against the immediate party',
   1, 'Want of delivery of an incomplete instrument is a real defense good even against a holder in due course; in contrast, want of delivery of a complete instrument is only a personal defense.', 3),
  ('RFBT', 'Negotiable Instruments',
   'The party primarily liable on a promissory note is the:',
   'Indorser', 'Maker', 'Drawer', 'Drawee before acceptance',
   1, 'On a promissory note the maker is primarily and absolutely liable to pay; on a bill, primary liability attaches to the drawee only once it accepts, becoming the acceptor.', 1),
  ('RFBT', 'Negotiable Instruments',
   'A general indorser, by indorsing, warrants among other things that:',
   'Nothing at all, since indorsement is gratuitous', 'That the maker is solvent forever', 'Only that he physically delivered the paper', 'The instrument is genuine, he has good title, prior parties had capacity, and the instrument is valid and subsisting',
   3, 'A general indorser warrants that the instrument is genuine and in all respects what it purports to be, that he has good title, that all prior parties had capacity to contract, and that the instrument is at the time valid and subsisting.', 2),
  ('RFBT', 'Negotiable Instruments',
   'Where a drawer signature on a check is forged, the general rule is that the drawee bank:',
   'Bears the loss and cannot charge the drawer account, since the forged drawer signature is wholly inoperative', 'May freely debit the drawer account because it acted in good faith', 'Shifts the loss to the last indorser in all cases', 'Recovers from the payee automatically',
   0, 'The drawee bank is generally bound to know its depositor signature; paying on a forged drawer signature, the bank bears the loss and cannot charge the drawer account, absent the drawer negligence or estoppel.', 3),
  ('RFBT', 'Negotiable Instruments',
   'When an indorsement on an order instrument is forged, as a general rule:',
   'Title passes normally to subsequent holders despite the forgery', 'The forged indorsement is merely a personal defense', 'No right to retain, discharge, or enforce payment can be acquired through the forged indorsement', 'Only the drawer, never the indorsers, bears the loss',
   2, 'A forged indorsement is wholly inoperative; no party can acquire the right to enforce payment through or under it, so parties after the forgery generally cannot enforce the instrument against those before it.', 2),
  ('RFBT', 'Negotiable Instruments',
   'Dina holds a check and, instead of the drawer, has it certified by the bank. The legal effect is that:',
   'Only the drawee bank is discharged', 'The drawer and all prior indorsers are discharged from liability', 'Nothing changes regarding the drawer liability', 'The check immediately becomes non-negotiable',
   1, 'Where the holder of a check procures it to be certified, the drawer and all prior indorsers are discharged from liability; certification at the holder request operates as the holder acceptance of the bank as sole obligor.', 3),
  ('RFBT', 'Negotiable Instruments',
   'Notice of dishonor to a party is dispensed with (excused) when:',
   'The holder simply forgets to send it', 'The drawer is a corporation', 'The instrument is for a small amount', 'The party to be notified is the very person who dishonored the instrument or notice cannot be given despite due diligence',
   3, 'Notice of dishonor may be excused, among other situations, when after due diligence it cannot be given, or where the party to be charged is the person who dishonored the instrument, such as a drawer who has no funds.', 2),
  ('RFBT', 'Negotiable Instruments',
   'A check presented for payment an unreasonable time after its issue is considered a stale check, the practical effect being that:',
   'The bank may refuse to pay it, and the holder may need to seek a replacement from the drawer', 'The drawer is automatically released from all liability on the underlying debt', 'The check becomes payable to bearer', 'The bank must still pay it regardless of how old it is',
   0, 'A check becomes stale when presented an unreasonable time after issue (commonly six months in banking practice); the drawee may, but is not obliged to, dishonor it, though the underlying obligation may persist.', 2),
  ('RFBT', 'Negotiable Instruments',
   'The crossing of a check (two parallel lines on its face) generally means that:',
   'The check has become non-negotiable and cannot be transferred', 'The check may be paid only through a bank, not over the counter in cash', 'The drawer signature has been canceled', 'The check must be paid in foreign currency',
   1, 'A crossed check serves as a warning that it must be deposited and collected through a bank rather than paid over the counter, alerting the holder to the limited purpose for which it may have been issued.', 2),
  ('RFBT', 'Negotiable Instruments',
   'A note promising payment on or before December 31, 2026 is payable at:',
   'An uncertain time, which destroys negotiability', 'A determinable future time, which does not impair negotiability', 'A time contingent on a condition, hence non-negotiable', 'The maker pleasure only',
   1, 'An instrument payable on or before a fixed date is payable at a determinable future time; this satisfies the requisite of certainty as to time and does not affect negotiability.', 2)
)
insert into public.questions (topic_id, stem, choices, correct_index, explanation, difficulty)
select t.id, q.stem, jsonb_build_array(q.a, q.b, q.c, q.d), q.correct_index, q.explanation, q.difficulty
from q join t on t.code = q.subject_code and lower(t.name) = lower(q.topic)
where not exists (select 1 from public.questions x where x.stem = q.stem);
