-- Generated from content/tax-batch-002.csv by scripts/csv-to-seed-sql.mjs — do not edit by hand.
-- Idempotent: skips any question whose stem already exists.
with t as (
  select tp.id, tp.name, s.code from public.topics tp
  join public.subjects s on s.id = tp.subject_id
),
q(subject_code, topic, stem, a, b, c, d, correct_index, explanation, difficulty) as (values
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'Which of the following items is excluded from gross income?',
   'Recovery of a bad debt previously deducted with full tax benefit', 'Cancellation of a debt in consideration of services rendered by the debtor', 'Interest earned on life insurance proceeds left on deposit with the insurer', 'Proceeds of a life insurance policy paid to the beneficiary upon the death of the insured',
   3, 'Life insurance proceeds paid by reason of the insured''s death are excluded from gross income. Interest on such proceeds, recoveries with tax benefit, and debt cancelled as payment for services are all taxable.', 1),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'In 2024, Mr. Reyes wrote off a P100,000 receivable as a bad debt, but only P60,000 of the write-off actually reduced his taxable income because his income before the deduction was only P60,000. In 2026 the debtor unexpectedly paid the P100,000 in full. How much of the recovery is taxable in 2026?',
   'P0', 'P40,000', 'P60,000', 'P100,000',
   2, 'Under the tax benefit rule, a bad debt recovery is taxable only to the extent the earlier deduction produced a tax benefit. Only P60,000 of the write-off reduced taxable income, so only P60,000 of the recovery is income.', 3),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'A lessor received P120,000 representing advance rent for the last two months of the lease and a P60,000 security deposit that is refundable at the end of the lease if no damages occur. How much is taxable income upon receipt?',
   'P0', 'P60,000', 'P120,000', 'P180,000',
   2, 'Advance rent is taxable in full when received regardless of accounting method. A refundable security deposit is not income because the lessor has an obligation to return it; it becomes income only upon forfeiture or application to unpaid rent.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'A resident citizen won an P8,000 raffle prize from a mall promotion and a P50,000 prize in a singing contest he joined. The correct income tax treatment is:',
   'The P8,000 is subject to the graduated income tax while the P50,000 is subject to a 20% final tax', 'Both prizes are subject to a 20% final tax', 'Both prizes are subject to the graduated income tax', 'The P8,000 is exempt while the P50,000 is subject to the graduated income tax',
   0, 'Prizes exceeding P10,000 received by citizens and residents are subject to a 20% final withholding tax, while prizes of P10,000 or less are included in gross income subject to the graduated rates.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'A domestic corporation incurred interest expense of P200,000 on a bank loan and earned P100,000 interest income on its peso time deposits that was subjected to final withholding tax. How much interest expense is deductible?',
   'P100,000', 'P160,000', 'P180,000', 'P200,000',
   2, 'The otherwise deductible interest expense is reduced by 20% of the interest income subjected to final tax. Reduction = P100,000 × 20% = P20,000, so deductible interest = P200,000 − P20,000 = P180,000.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'Which of the following taxes is deductible from gross income in computing taxable income from business?',
   'Philippine income tax', 'Estate tax paid on inherited business assets', 'Special assessment on land benefited by a public improvement', 'Local business tax paid to the city',
   3, 'Income tax, estate and donor''s taxes, and special assessments are expressly non-deductible. Local business taxes, licenses, percentage taxes and similar business-connected taxes are deductible.', 1),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'An individual taxpayer with taxable income of P800,000 before charitable contributions donated P100,000 to an accredited charitable institution (not for priority government programs). How much contribution expense is deductible?',
   'P40,000', 'P70,000', 'P80,000', 'P100,000',
   2, 'Ordinary charitable contributions of individuals are deductible up to 10% of taxable income before the contributions. Limit = P800,000 × 10% = P80,000, which is lower than the actual P100,000.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'A taxpayer had net sales of goods of P4,000,000 and net service revenues of P2,000,000, with actual entertainment, amusement and recreation expenses of P100,000 properly allocated by revenue. The deductible EAR expense is:',
   'P20,000', 'P40,000', 'P60,000', 'P100,000',
   1, 'The ceilings are 0.5% of net sales for goods (P4,000,000 × 0.5% = P20,000) and 1% of net revenues for services (P2,000,000 × 1% = P20,000). The actual EAR apportioned by revenue (P66,667 and P33,333) exceeds both ceilings, so the deduction is capped at P20,000 + P20,000 = P40,000.', 3),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'Retirement benefits received under a reasonable private benefit plan are excluded from gross income if the retiring employee:',
   'Is at least 60 years old and has served at least 5 years', 'Is at least 55 years old regardless of length of service', 'Has served at least 20 years regardless of age', 'Is at least 50 years old, has served at least 10 years, and avails of the exemption for the first time',
   3, 'The exclusion requires that the employee be at least 50 years old at retirement, have rendered at least 10 years of service to the employer, and avail of the benefit of the exclusion only once.', 1),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'A 35-year-old employee with 4 years of service received P500,000 separation pay after his position was declared redundant. The separation pay is:',
   'Taxable in full because he is below 50 years old', 'Taxable only to the extent it exceeds P90,000', 'Exempt regardless of his age and length of service', 'Exempt only if he is at least 50 years old with 10 years of service',
   2, 'Amounts received because of separation due to death, sickness, disability or causes beyond the employee''s control, such as redundancy or retrenchment, are excluded from gross income without any age or service requirement.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'A corporation had a net operating loss of P500,000 in 2023. It had taxable income before NOLCO of P200,000 in 2024 and P400,000 in 2025, claiming the maximum NOLCO each year. How much NOLCO may be deducted in 2025?',
   'P0', 'P100,000', 'P200,000', 'P300,000',
   3, 'In 2024 the corporation deducted P200,000, leaving a P300,000 carryover within the 3-year period. In 2025 the deduction is the lower of the remaining P300,000 and the P400,000 income before NOLCO, so P300,000.', 3),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'Which statement correctly describes the basis of the 40% optional standard deduction?',
   'Individuals compute OSD on gross sales or gross receipts, while corporations compute it on gross income', 'Both individuals and corporations compute OSD on gross income', 'Both individuals and corporations compute OSD on gross sales or gross receipts', 'Individuals compute OSD on gross income, while corporations compute it on gross sales',
   0, 'Under the law as amended by TRAIN, individuals deduct 40% of gross sales or receipts (cost of sales is not separately deductible), while corporations deduct 40% of gross income.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'A self-employed individual elected the optional standard deduction. Her gross sales were P2,000,000, cost of sales P800,000, and operating expenses P300,000. Her taxable income is:',
   'P720,000', 'P900,000', 'P1,200,000', 'P1,700,000',
   2, 'For individuals, OSD is 40% of gross sales and replaces both cost of sales and itemized deductions. OSD = P2,000,000 × 40% = P800,000; taxable income = P2,000,000 − P800,000 = P1,200,000.', 3),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'Which of the following tax refunds received by a business taxpayer is taxable income?',
   'Refund of Philippine income tax', 'Refund of donor''s tax', 'Refund of a special assessment', 'Refund of local business tax claimed as a deduction in a prior year',
   3, 'Under the tax benefit rule, a refunded tax is income only if it was deductible when paid. Income tax, donor''s tax and special assessments are non-deductible, so their refunds are not income; local business tax is deductible, so its refund is taxable.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'During the year, a taxpayer had gambling winnings of P80,000 (not from PCSO games) and gambling losses of P120,000. How much wagering loss is deductible?',
   'P0', 'P40,000', 'P80,000', 'P120,000',
   2, 'Losses from wagering transactions are deductible only to the extent of gains from such transactions, so only P80,000 of the P120,000 losses may be deducted.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'An insured outlived his endowment policy and received the P500,000 maturity value. Total premiums he paid amounted to P350,000. How much is taxable income?',
   'P0', 'P150,000', 'P350,000', 'P500,000',
   1, 'Amounts received as a return of premium are excluded from gross income. The excess of the maturity proceeds over premiums paid, P500,000 − P350,000 = P150,000, is taxable interest income.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'An employee injured in a vehicular accident sued and received actual damages for hospital expenses, moral damages for his physical injuries, and damages representing his lost salary during recovery. Which amount is taxable?',
   'The actual damages for hospital expenses', 'The moral damages arising from the physical injuries', 'None, because all court-awarded damages are exempt', 'The damages representing lost salary',
   3, 'Compensation for personal injuries and damages flowing from the injury are excluded, but amounts that replace taxable income, such as lost salary or lost profits, are taxable because the income they replace would have been taxed.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'Which requirement must be met before a bad debt may be deducted from gross income?',
   'A reasonable reserve for doubtful accounts has been set up in the books', 'The debtor has merely been delinquent for more than one year', 'The debt was actually ascertained to be worthless and charged off the books within the taxable year', 'The debt need not be connected with the taxpayer''s trade or business',
   2, 'Only debts ascertained to be worthless and actually charged off during the year, arising from or connected with the trade or business, are deductible. Mere reserves or provisions are not deductible.', 1),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'Equipment costing P1,200,000 with a salvage value of P200,000 is depreciated over a 5-year useful life using the straight-line method. The annual depreciation deduction is:',
   'P166,667', 'P200,000', 'P240,000', 'P280,000',
   1, 'Depreciable cost = P1,200,000 − P200,000 = P1,000,000. Annual depreciation = P1,000,000 ÷ 5 years = P200,000.', 1),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'Which of the following is deductible from business gross income?',
   'Facilitation fee paid to a government official to speed up a permit', 'Living expenses of the owner''s family', 'Cost of constructing a new warehouse', 'Ordinary repairs that merely keep business equipment in operating condition',
   3, 'Bribes and kickbacks, personal expenses, and capital expenditures are non-deductible; capital outlays are recovered through depreciation. Ordinary repairs that do not extend asset life are deductible expenses.', 1),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'Which statement best reflects the principle that gross income includes income from whatever source derived?',
   'Gains from illegal activities are taxable income', 'Only income from lawful sources is taxable', 'Gifts received are taxable income to the recipient', 'Treasure found is exempt because there is no source',
   0, 'The phrase from whatever source derived covers all realized accessions to wealth, legal or illegal, including found treasure. Gifts are excluded by a specific statutory provision, not because of the source rule.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'A domestic corporation with taxable income of P1,000,000 before contributions donated P80,000 to the national government for an ordinary public purpose and P60,000 to an accredited NGO meeting all utilization and administrative expense requirements. The total deductible contributions amount to:',
   'P50,000', 'P110,000', 'P130,000', 'P140,000',
   1, 'The donation to the accredited NGO is deductible in full (P60,000). The donation to the government for a non-priority purpose is subject to the 5% corporate limit: P1,000,000 × 5% = P50,000. Total = P60,000 + P50,000 = P110,000.', 3),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'An employee received a 13th month pay of P100,000 and other benefits of P20,000 during the year. How much is taxable?',
   'P0', 'P10,000', 'P30,000', 'P120,000',
   2, '13th month pay and other benefits are excluded only up to P90,000. Total benefits = P120,000; taxable portion = P120,000 − P90,000 = P30,000.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'A corporation condoned the P500,000 loan of one of its shareholders without any consideration and without the shareholder rendering services. For tax purposes, the condonation is treated as:',
   'An exempt gift to the shareholder', 'Compensation income of the shareholder', 'A deductible bad debt of the corporation', 'A distribution in the nature of a dividend taxable to the shareholder',
   3, 'When a corporation forgives a shareholder''s debt without consideration, the condonation has the effect of a dividend distribution and is taxable to the shareholder as such.', 2),
  ('TAX', 'Gross Income, Deductions & Exemptions',
   'A resident citizen paid income taxes to a foreign country on income earned abroad. For Philippine income tax purposes, the foreign income tax may be:',
   'Claimed either as a deduction from gross income or as a tax credit, at the taxpayer''s option', 'Claimed only as a deduction from gross income', 'Claimed only as a tax credit against Philippine income tax', 'Claimed as both a deduction and a tax credit in the same year',
   0, 'Taxpayers taxable on worldwide income may elect to treat foreign income taxes either as a deduction or as a tax credit subject to the per-country and overall limitations, but not both in the same year.', 2),
  ('TAX', 'Withholding Taxes & Compliance',
   'Which of the following best describes a final withholding tax?',
   'The tax withheld constitutes the full and final settlement of the income tax on that income', 'The withholding agent may opt not to remit if the payee is exempt', 'The tax withheld is creditable against the payee income tax due for the year', 'The payee must still file an annual return to compute any balance',
   0, 'Under a final withholding tax system, the amount withheld by the payor is the full and final payment of the income tax due on that income; the payee no longer reports it in the annual return.', 1),
  ('TAX', 'Withholding Taxes & Compliance',
   'Beta Realty pays monthly rent of P100,000 to its lessor. The expanded withholding tax (5%) that Beta must withhold each month is:',
   'P2,000', 'P5,000', 'P10,000', 'P12,000',
   1, 'Rentals of real and personal property are subject to 5% creditable withholding tax: P100,000 x 5% = P5,000.', 1),
  ('TAX', 'Withholding Taxes & Compliance',
   'A domestic corporation engages an independent CPA whose gross professional fees for the year are expected to exceed P3,000,000. The creditable withholding tax rate on the professional fees is:',
   '2%', '15%', '10%', '5%',
   2, 'Professional fees to an individual are subject to 10% EWT if the payee gross income for the year exceeds P3,000,000 (or if no sworn declaration is given); 5% applies if income will not exceed P3,000,000.', 2),
  ('TAX', 'Withholding Taxes & Compliance',
   'Gamma Corp paid P500,000 to a general contractor for building repairs. The expanded withholding tax on the payment (contractors, 2%) is:',
   'P25,000', 'P5,000', 'P10,000', 'P60,000',
   2, 'Income payments to contractors are subject to 2% EWT: P500,000 x 2% = P10,000.', 1),
  ('TAX', 'Withholding Taxes & Compliance',
   'An employer failed to withhold and remit the correct compensation withholding tax on its employees salaries. With respect to the salary expense, the primary consequence to the employer is that:',
   'The salary expense is disallowed as a deduction for income tax purposes', 'The employees lose their personal exemption', 'The employer is barred from registering for VAT', 'The salaries become taxable income of the employer',
   0, 'Under the NIRC, expenses on which the required withholding tax was not withheld and remitted are disallowed as deductions from gross income, in addition to penalties for failure to withhold.', 2),
  ('TAX', 'Withholding Taxes & Compliance',
   'Under the EOPT Act, taxpayers are classified by gross sales for purposes of tailoring compliance. A taxpayer with gross sales of P50,000,000 falls under which classification?',
   'Large', 'Small', 'Medium', 'Micro',
   2, 'Under EOPT, Medium covers gross sales of P20,000,000 to less than P1,000,000,000; P50,000,000 falls in this range.', 2),
  ('TAX', 'Withholding Taxes & Compliance',
   'Which statement is TRUE regarding the annual registration fee for businesses following the EOPT Act?',
   'It remains P500 per year per establishment', 'It was abolished', 'It was increased to P1,000 per year', 'It is now collected only from VAT taxpayers',
   1, 'The EOPT Act abolished the P500 annual registration fee; taxpayers no longer pay it.', 1),
  ('TAX', 'Withholding Taxes & Compliance',
   'Under the EOPT Act, the single principal document required to support a sale of goods or services for tax purposes is the:',
   'Official receipt', 'Delivery receipt', 'Sales invoice', 'Statement of account',
   2, 'EOPT made the invoice the single principal sales document for both goods and services, removing the separate official-receipt requirement for services.', 1),
  ('TAX', 'Withholding Taxes & Compliance',
   'BIR Form 2307 is best described as the certificate:',
   'Of compensation payment and tax withheld for employees', 'Authorizing substituted filing for employees', 'Of final tax withheld on passive income that needs no further return', 'Of creditable tax withheld at source, used to support the payee tax credit',
   3, 'Form 2307 is the Certificate of Creditable Tax Withheld at Source; the payee attaches it to claim the withheld amount as a tax credit against the income tax due.', 2),
  ('TAX', 'Withholding Taxes & Compliance',
   'An employee earned salaries from only one employer for the entire year, and the employer correctly withheld the tax. Under substituted filing, the employee:',
   'Files only if asked by the BIR', 'Must file but pays no tax', 'Is not required to file an annual income tax return', 'Must still file an annual income tax return',
   2, 'Under substituted filing, a purely compensation earner from a single employer whose tax was correctly withheld need not file an annual return; the employer Form 2316 serves as the return.', 2),
  ('TAX', 'Withholding Taxes & Compliance',
   'Delta Co. pays a domestic corporation P800,000 for janitorial services subject to 2% EWT. The net amount the payee receives after the creditable withholding (ignoring VAT) is:',
   'P784,000', 'P640,000', 'P800,000', 'P760,000',
   0, 'EWT = P800,000 x 2% = P16,000. Net cash received = P800,000 - P16,000 = P784,000; the P16,000 is a creditable advance payment of the payee income tax.', 2),
  ('TAX', 'Withholding Taxes & Compliance',
   'Which of the following income payments is generally subject to a FINAL withholding tax rather than a creditable one?',
   'Professional fees of a resident CPA', 'Rentals paid to a resident lessor', 'Cash dividends paid by a domestic corporation to a resident individual', 'Payments to a local contractor',
   2, 'Cash dividends from a domestic corporation to a resident individual are subject to a 10% final withholding tax; the others are subject to creditable (expanded) withholding.', 2),
  ('TAX', 'Withholding Taxes & Compliance',
   'Compensation withholding tax on an employee salary is remitted by the employer. This system is an example of:',
   'A final tax that needs no annual reconciliation by anyone', 'Withholding on compensation, reconciled through year-end adjustment by the employer', 'An excise tax', 'A percentage tax',
   1, 'Withholding on compensation is creditable and is reconciled at year-end by the employer, who adjusts the December withholding so total withheld equals the annual tax due.', 1),
  ('TAX', 'Withholding Taxes & Compliance',
   'A withholding agent withheld P30,000 of expanded withholding tax in June 2026. Under the file-and-pay-anywhere principle introduced by EOPT, the agent may:',
   'Pay only in cash at the BIR national office', 'Pay through any authorized agent bank or electronic channel regardless of RDO', 'Defer payment until the annual return', 'Only pay at the RDO where registered',
   1, 'EOPT adopted file-and-pay-anywhere, allowing taxpayers to file returns and pay taxes through any authorized agent bank or accredited electronic/online channel, not just the home RDO.', 2),
  ('TAX', 'Withholding Taxes & Compliance',
   'Epsilon Inc. pays P1,200,000 in professional fees during the year to a consultant who submitted a sworn declaration that gross receipts will not exceed P3,000,000. The correct EWT is:',
   'P24,000', 'P180,000', 'P120,000', 'P60,000',
   3, 'With a valid sworn declaration of income not exceeding P3,000,000, the EWT on professional fees is 5%: P1,200,000 x 5% = P60,000.', 2),
  ('TAX', 'Withholding Taxes & Compliance',
   'Which is NOT a function of the creditable withholding tax (CWT) system?',
   'Serving as the final and full settlement of the tax on that income', 'Providing the government with revenue throughout the year', 'Approximating the income tax due on the income during the year', 'Easing the payee year-end tax burden through advance credits',
   0, 'Being the full and final settlement describes the FINAL withholding system, not the creditable one; CWT amounts are merely advance credits against the annual tax.', 1),
  ('TAX', 'Withholding Taxes & Compliance',
   'Zeta Corp pays monthly rent of P224,000 inclusive of 12% VAT. The 5% EWT must be computed on the rent NET of VAT. The EWT to withhold is:',
   'P26,880', 'P10,000', 'P13,440', 'P11,200',
   1, 'Rent net of VAT = P224,000 / 1.12 = P200,000. EWT = P200,000 x 5% = P10,000; the EWT base excludes VAT.', 3),
  ('TAX', 'Estate Tax',
   'The estate tax accrues:',
   'On the date the estate tax return is filed', 'Upon issuance of the certificate authorizing registration', 'When the heirs take possession of the property', 'At the moment of the decedent death',
   3, 'The estate tax is a tax on the privilege of transmitting property at death; it accrues as of the moment of death, even though the return is filed and tax paid later.', 1),
  ('TAX', 'Estate Tax',
   'The current estate tax rate under the TRAIN Law applied to the net taxable estate is:',
   '5% graduated', '32% flat', '20% graduated', '6% flat',
   3, 'TRAIN imposed a flat 6% estate tax on the net taxable estate, replacing the old graduated schedule.', 1),
  ('TAX', 'Estate Tax',
   'For a resident citizen decedent, the gross estate includes:',
   'Property located anywhere in the world', 'Only property located within the Philippines', 'Only real property located in the Philippines', 'Only intangible personal property',
   0, 'A resident or citizen decedent is taxed on the worldwide gross estate, whether the property is located within or outside the Philippines.', 1),
  ('TAX', 'Estate Tax',
   'A nonresident alien died leaving intangible personal property in the Philippines. These intangibles are EXCLUDED from the Philippine gross estate when:',
   'The decedent was over 60 years old', 'The heirs are nonresidents', 'The property value is below P5,000,000', 'There is reciprocity exempting similar property of Filipinos in the alien country',
   3, 'For a nonresident alien, intangible personal property with a Philippine situs is included unless the reciprocity rule applies, exempting such property where the foreign country grants a like exemption to Filipinos.', 2),
  ('TAX', 'Estate Tax',
   'Which of the following life-insurance proceeds is INCLUDED in the gross estate of the decedent?',
   'Proceeds payable to the estate, executor, or administrator', 'Proceeds under a policy where the beneficiary is irrevocable and is the spouse', 'Group insurance taken by an employer for unnamed employees', 'Proceeds where a third person is the irrevocably designated beneficiary',
   0, 'Life-insurance proceeds are included when payable to the estate, executor, or administrator, or when the designation of any beneficiary is revocable; proceeds to an irrevocable third-party beneficiary are excluded.', 2),
  ('TAX', 'Estate Tax',
   'A transfer in contemplation of death is included in the gross estate because:',
   'It is always a donation subject to donor tax instead', 'The property was located abroad', 'Title passed during the decedent lifetime for full consideration', 'The decedent retained the economic enjoyment until death and the transfer was motivated by the thought of death',
   3, 'Transfers in contemplation of death are included because the motivating cause was the thought of death and the decedent effectively retained enjoyment; they are treated as testamentary in substance.', 2),
  ('TAX', 'Estate Tax',
   'The standard deduction allowed against the gross estate of a resident or citizen decedent under the TRAIN Law is:',
   'P1,000,000', 'P2,000,000', 'P5,000,000', 'P10,000,000',
   2, 'TRAIN set the standard deduction for resident and citizen decedents at P5,000,000, requiring no substantiation.', 1),
  ('TAX', 'Estate Tax',
   'The standard deduction allowed to a nonresident alien decedent is:',
   'P10,000,000', 'P500,000', 'P5,000,000', 'P1,000,000',
   1, 'Under TRAIN, a nonresident alien decedent is allowed a standard deduction of P500,000, in contrast to the P5,000,000 for residents and citizens.', 2),
  ('TAX', 'Estate Tax',
   'The family home deduction is limited to:',
   'P1,000,000 for all decedents', 'P5,000,000 regardless of ownership', 'The full fair market value of the family home with no ceiling', 'The decedent interest in the family home, but not exceeding P10,000,000',
   3, 'The family home deduction is allowed up to P10,000,000, and only to the extent of the decedent interest in the family home; any excess is not deductible.', 2),
  ('TAX', 'Estate Tax',
   'Real property in the gross estate is valued at:',
   'Its original acquisition cost', 'The assessed value only', 'The fair market value at the time of death, being the higher of zonal value or assessed value', 'The selling price after death',
   2, 'Real property is valued at fair market value at the time of death, taken as the higher of the BIR zonal value and the FMV per the provincial or city assessor.', 2),
  ('TAX', 'Estate Tax',
   'A decedent left a family home with a zonal value of P12,000,000 and an assessor fair market value of P9,000,000. The property was exclusively owned by the decedent. The allowable family home deduction is:',
   'P9,000,000', 'P6,000,000', 'P10,000,000', 'P12,000,000',
   2, 'Value the home at the higher figure (zonal P12,000,000). The decedent interest is the full P12,000,000, but the family home deduction is capped at P10,000,000.', 3),
  ('TAX', 'Estate Tax',
   'A resident citizen decedent left a gross estate of P8,000,000. Allowable ordinary deductions (LIT) total P1,000,000, and the standard deduction applies. The net taxable estate is:',
   'P2,000,000', 'P3,000,000', 'P7,000,000', 'P5,000,000',
   0, 'Net taxable estate = P8,000,000 - P1,000,000 ordinary deductions - P5,000,000 standard deduction = P2,000,000.', 2),
  ('TAX', 'Estate Tax',
   'Continuing the prior facts, if the net taxable estate is P2,000,000, the estate tax due is:',
   'P160,000', 'P200,000', 'P120,000', 'P100,000',
   2, 'Estate tax = P2,000,000 x 6% = P120,000.', 1),
  ('TAX', 'Estate Tax',
   'Under the absolute community of property regime, which property is generally EXCLUSIVE to a spouse?',
   'Salaries earned during the marriage', 'Property acquired by gratuitous title (inheritance or donation) during the marriage', 'Income from community property', 'A car bought during the marriage from community funds',
   1, 'Under absolute community, property acquired during the marriage by gratuitous title (inheritance or donation) and its fruits generally remain exclusive to the recipient spouse, subject to exceptions.', 2),
  ('TAX', 'Estate Tax',
   'The gross estate of a married decedent includes P6,000,000 of community property and P2,000,000 of the decedent exclusive property. The surviving spouse net share is computed as one-half of the community property after community deductions. If community deductions are P1,000,000, the surviving spouse share is:',
   'P3,500,000', 'P3,000,000', 'P2,500,000', 'P4,000,000',
   2, 'Net community = P6,000,000 - P1,000,000 = P5,000,000. Surviving spouse share = P5,000,000 / 2 = P2,500,000, which is deductible from the gross estate.', 3),
  ('TAX', 'Estate Tax',
   'Property was inherited by the present decedent 2.5 years before death. The vanishing-deduction percentage applicable, where property received within 2 to 3 years before death qualifies, is:',
   '100%', '80%', '60%', '40%',
   2, 'The vanishing-deduction rate steps down by interval: more than 2 up to 3 years before death qualifies for 60%.', 2),
  ('TAX', 'Estate Tax',
   'The estate tax return must generally be filed within:',
   '2 years from death', '6 months from death', '30 days from death', '1 year from death',
   3, 'Under TRAIN, the estate tax return must be filed within one year from the decedent death, extendible in meritorious cases.', 1),
  ('TAX', 'Estate Tax',
   'A statement under oath certified by a CPA is required to accompany the estate tax return when the gross estate:',
   'Exceeds P2,000,000', 'Exceeds P10,000,000', 'Exceeds P5,000,000', 'Includes any real property',
   2, 'A CPA certification of the estate tax return is required when the value of the gross estate exceeds P5,000,000.', 2),
  ('TAX', 'Estate Tax',
   'A bank allowed the heirs to withdraw P1,000,000 from the deceased depositor account. The bank is required to withhold a final tax of:',
   'P30,000', 'P60,000', 'P120,000', 'P100,000',
   1, 'Withdrawals from a decedent bank account are subject to a 6% final withholding tax: P1,000,000 x 6% = P60,000.', 2),
  ('TAX', 'Estate Tax',
   'A resident decedent left a gross estate of P12,000,000 consisting only of exclusive property. Funeral-related claims and other LIT deductions total P2,000,000, and the family home (exclusive, valued at P7,000,000) is included. The net taxable estate, applying the standard deduction, is:',
   'P0', 'P3,000,000', 'P5,000,000', 'P10,000,000',
   0, 'Net = P12,000,000 - P2,000,000 LIT - P7,000,000 family home (within the P10M cap) - P5,000,000 standard deduction = -P2,000,000, floored at P0; no estate tax is due.', 3),
  ('TAX', 'Estate Tax',
   'A nonresident alien decedent left Philippine real property of P4,000,000 and foreign property of P10,000,000. The Philippine gross estate is:',
   'P0', 'P10,000,000', 'P14,000,000', 'P4,000,000',
   3, 'A nonresident alien is taxed only on property situated in the Philippines, so only the P4,000,000 Philippine real property is in the Philippine gross estate.', 2),
  ('TAX', 'Donor''s Tax',
   'The donor tax under the TRAIN Law is imposed at:',
   '2% of the gift', '6% of total net gifts in excess of P250,000 per calendar year', '8% of the gift', 'A graduated 2% to 15% schedule',
   1, 'TRAIN set a flat 6% donor tax on total net gifts exceeding P250,000 made during the calendar year, regardless of the donee relationship.', 1),
  ('TAX', 'Donor''s Tax',
   'Under the TRAIN Law, the donor tax rate applied to a gift to a stranger (an unrelated person) is:',
   '30% of the gift', '20% of the gift', 'Exempt', '6%, the same rate as for relatives',
   3, 'TRAIN abolished the stranger rule; gifts to relatives and strangers alike are taxed at the uniform 6% rate over the annual P250,000 exemption.', 1),
  ('TAX', 'Donor''s Tax',
   'On March 1, 2026, a donor gave a relative cash of P700,000, the donor only gift for the year. The donor tax due is:',
   'P150,000', 'P42,000', 'P45,000', 'P27,000',
   3, 'Net gift = P700,000 - P250,000 annual exemption = P450,000. Donor tax = P450,000 x 6% = P27,000.', 2),
  ('TAX', 'Donor''s Tax',
   'A donor made two donations in 2026: P200,000 on January 10 and P300,000 on June 5, both to relatives. Donor tax is cumulative within the year. The total donor tax for 2026 is:',
   'P3,000', 'P15,000', 'P0', 'P18,000',
   1, 'Cumulative net gifts = P200,000 + P300,000 = P500,000; less the one P250,000 annual exemption = P250,000 taxable; x 6% = P15,000.', 2),
  ('TAX', 'Donor''s Tax',
   'The donor tax return for a particular donation must be filed within:',
   '60 days after the donation', '1 year after the donation', '30 days after the donation', 'On April 15 of the following year',
   2, 'The donor tax return must be filed, and the tax paid, within 30 days after the date the gift is made.', 1),
  ('TAX', 'Donor''s Tax',
   'Spouses jointly donated community property to their child. For donor tax purposes, the spouses are:',
   'Separate donors, each taxed on one-half of the gift with each entitled to a P250,000 exemption', 'Treated as one donor filing a single return', 'Exempt because the donee is a child', 'Taxed only on the husband share',
   0, 'Each spouse is a separate donor of one-half of community property donated; each computes donor tax separately and each enjoys a P250,000 annual exemption.', 2),
  ('TAX', 'Donor''s Tax',
   'A sale of a personal (ordinary) asset for an amount that is insufficient compared to its fair market value is, for the inadequacy:',
   'Treated as a gift subject to donor tax', 'Subject to estate tax', 'Subject to percentage tax', 'Always exempt',
   0, 'Where property other than a real-property capital asset is transferred for less than adequate and full consideration, the excess of FMV over the consideration is deemed a gift subject to donor tax.', 2),
  ('TAX', 'Donor''s Tax',
   'A transfer for insufficient consideration of a real property classified as a CAPITAL asset is:',
   'Subject to donor tax on the deficiency', 'Not subject to donor tax but to the 6% capital gains tax', 'Exempt entirely', 'Subject to VAT',
   1, 'Transfers for insufficient consideration are deemed gifts EXCEPT for real property classified as a capital asset, which is instead subject to the 6% capital gains tax on the higher of FMV or selling price.', 2),
  ('TAX', 'Donor''s Tax',
   'Which donation is EXEMPT from donor tax?',
   'A gift of P500,000 to a friend', 'A donation of land to a cousin', 'A donation of jewelry to a sibling', 'A donation to the national government for public purposes',
   3, 'Donations to or for the use of the national government, or any of its agencies not conducted for profit, are exempt from donor tax; gifts to private individuals are not.', 2),
  ('TAX', 'Donor''s Tax',
   'A donor gives real property worth P3,000,000 to a donee on condition that the donee assumes a P1,000,000 mortgage on the property. The net gift subject to donor tax (before the annual exemption) is:',
   'P1,000,000', 'P2,000,000', 'P3,000,000', 'P4,000,000',
   1, 'An encumbrance assumed by the donee reduces the gift: P3,000,000 - P1,000,000 mortgage = P2,000,000 net gift before the P250,000 exemption.', 2),
  ('TAX', 'Donor''s Tax',
   'Political or campaign contributions are exempt from donor tax provided that:',
   'The donor is a corporation', 'They are duly reported to the Commission on Elections (COMELEC)', 'They are given to any candidate of the donor choice', 'They do not exceed P250,000',
   1, 'Campaign contributions duly reported to the COMELEC are exempt from donor tax; unutilized or unreported amounts may be subject to tax.', 2),
  ('TAX', 'Donor''s Tax',
   'On February 2026 a donor gave P900,000 to a relative; on July 2026 the same donor gave P400,000 to a friend. Using cumulative computation, the total donor tax for 2026 is:',
   'P63,000', 'P78,000', 'P39,000', 'P75,000',
   0, 'Cumulative gifts = P900,000 + P400,000 = P1,300,000; less one P250,000 exemption = P1,050,000 x 6% = P63,000. The stranger status of the second donee does not change the 6% rate.', 3),
  ('TAX', 'Donor''s Tax',
   'A donor net gifts for 2026 totaled exactly P250,000. The donor tax due is:',
   'P3,000', 'P250,000', 'P15,000', 'P0',
   3, 'Donor tax applies only to net gifts in excess of P250,000 per year; gifts of exactly P250,000 are fully covered by the exemption, so the tax is P0.', 1),
  ('TAX', 'VAT & Percentage Taxes',
   'The Philippine VAT is best characterized as a tax that is:',
   'A tax on net income', 'Direct and progressive', 'Indirect, levied on the value added and collected through the tax-credit method', 'An excise tax on production only',
   2, 'VAT is an indirect tax on the value added at each stage, computed under the tax-credit method (output VAT less creditable input VAT) and following the destination principle.', 1),
  ('TAX', 'VAT & Percentage Taxes',
   'The standard VAT rate in the Philippines is:',
   '3%', '12%', '10%', '8%',
   1, 'The VAT rate is 12% on the gross selling price of goods or gross receipts from services, subject to specific zero-rated and exempt items.', 1),
  ('TAX', 'VAT & Percentage Taxes',
   'A VAT-registered seller issued an invoice for P56,000 inclusive of VAT. The output VAT included in the amount is:',
   'P5,600', 'P6,000', 'P6,720', 'P12,000',
   1, 'Output VAT = VAT-inclusive amount / 1.12 x 0.12, or P56,000 - (P56,000 / 1.12). P56,000 / 1.12 = P50,000; VAT = P56,000 - P50,000 = P6,000.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'Gross sales (net of VAT) of a VAT-registered trader for the month were P2,000,000, with creditable input VAT of P150,000. The VAT payable is:',
   'P150,000', 'P240,000', 'P90,000', 'P390,000',
   2, 'Output VAT = P2,000,000 x 12% = P240,000. VAT payable = P240,000 output - P150,000 input = P90,000.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'The mandatory VAT registration threshold of gross annual sales or receipts is:',
   'P3,000,000', 'P1,919,500', 'P1,000,000', 'P10,000,000',
   0, 'A person whose actual or expected gross sales or receipts exceed P3,000,000 in a 12-month period must register for VAT.', 1),
  ('TAX', 'VAT & Percentage Taxes',
   'A direct export sale by a VAT-registered exporter is:',
   'Zero-rated, so output VAT is 0% but input VAT remains creditable or refundable', 'Subject to 12% output VAT', 'Subject to 3% percentage tax', 'VAT-exempt, so input VAT becomes a cost',
   0, 'Direct exports are zero-rated: output VAT is 0%, but the related input VAT remains creditable and may be refunded, preserving the destination principle.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'The key difference between a VAT zero-rated sale and a VAT-exempt sale is that in a zero-rated sale:',
   'Output VAT is 12%', 'No invoice is issued', 'The related input VAT may be credited or refunded, whereas in an exempt sale it becomes part of cost', 'The seller need not register',
   2, 'In a zero-rated sale, output is 0% but input VAT stays creditable/refundable; in an exempt sale there is no output VAT and the input VAT cannot be credited, becoming part of cost.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'Which of the following is a transaction deemed sale subject to VAT?',
   'Transfer of goods originally intended for sale, used instead for personal consumption of the owner', 'Sale of goods to a regular customer', 'Purchase of raw materials', 'Receipt of a cash advance from a customer',
   0, 'Transactions deemed sale include the transfer, use, or consumption not in the course of business of goods originally intended for sale, so VAT is imposed despite no actual sale.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'A person becomes liable to VAT for the first time and has beginning inventory of goods. The transitional input VAT allowed is:',
   '12% of the goods', '4% of gross sales', 'Equal to output VAT', '2% of the beginning inventory value or the actual VAT paid, whichever is higher',
   3, 'A taxpayer becoming VAT-liable may claim a transitional input VAT of 2% of the value of the beginning inventory of goods, or the actual VAT paid thereon, whichever is higher.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'A VAT-registered processor of sardines may claim a presumptive input VAT equal to:',
   '2% of gross sales', '10% of output VAT', '4% of the gross value of primary agricultural inputs purchased', '12% of purchases',
   2, 'Processors of sardines, mackerel, milk, refined sugar, cooking oil, and similar goods may claim a presumptive input VAT of 4% of the gross value of their primary agricultural purchases.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'Under the CREATE Law, input VAT on the purchase of capital goods is:',
   'Treated as a cost, never creditable', 'Amortized only if the purchase exceeds P1,000,000', 'Always amortized over 60 months', 'Creditable outright in the month of purchase, the amortization rule having been removed',
   3, 'CREATE removed the requirement to amortize input VAT on capital goods exceeding P1,000,000 over their useful life; input VAT on capital goods is now creditable outright.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'A VAT taxpayer has both VATable and VAT-exempt sales and incurs input VAT that cannot be directly attributed to either. The input VAT is:',
   'Fully creditable against output VAT', 'Fully treated as cost', 'Allocated between VATable and exempt sales in proportion to their respective sales', 'Carried over indefinitely with no allocation',
   2, 'Input VAT that cannot be directly attributed to a specific activity is allocated ratably between VATable and exempt sales; only the portion allocable to VATable sales is creditable.', 3),
  ('TAX', 'VAT & Percentage Taxes',
   'Excess input VAT attributable to zero-rated sales may be:',
   'Carried over but never refunded', 'Refunded within 30 days only', 'Claimed only against income tax', 'Refunded or applied for a tax credit certificate within 2 years from the close of the taxable quarter',
   3, 'Input VAT attributable to zero-rated sales may be the subject of a refund or tax-credit certificate, filed within 2 years from the close of the taxable quarter when the sales were made.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'A non-VAT person whose annual gross receipts of P2,000,000 are below the VAT threshold and who did not elect the 8% income tax option is subject to a percentage tax under Sec. 116 of:',
   '3%', '12%', '6%', '1%',
   0, 'The Sec. 116 percentage tax is 3% of gross sales or receipts; the temporary 1% rate applied only from July 2020 to June 2023.', 1),
  ('TAX', 'VAT & Percentage Taxes',
   'A non-VAT service provider with gross receipts of P1,500,000 who did NOT choose the 8% income tax option owes a Sec. 116 percentage tax of:',
   'P90,000', 'P15,000', 'P45,000', 'P180,000',
   2, 'Percentage tax = P1,500,000 x 3% = P45,000.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'A self-employed individual below the VAT threshold who validly elected the 8% income tax option is:',
   'Still liable for the 3% percentage tax', 'Liable for 12% VAT', 'Not liable for the Sec. 116 percentage tax', 'Liable for both VAT and percentage tax',
   2, 'Electing the 8% income tax on gross sales/receipts is in lieu of both the graduated income tax and the Sec. 116 percentage tax, so no percentage tax is due.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'A domestic common carrier transporting passengers by land had gross receipts of P800,000. The common carrier percentage tax of 3% is:',
   'P8,000', 'P96,000', 'P240,000', 'P24,000',
   3, 'The common carrier tax on the gross receipts of domestic carriers of passengers by land is 3%: P800,000 x 3% = P24,000.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'Sale of listed shares of stock through the local stock exchange is subject to a stock transaction tax of:',
   '0.6% of the gross selling price', '12% of the gross selling price', '6% of the gain', '0.5% of the gain',
   0, 'Sales of shares listed and traded through the local stock exchange are subject to a stock transaction tax of 0.6% of the gross selling price, in lieu of income tax on the gain.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'Shares listed on the local exchange were sold for a gross selling price of P500,000. The stock transaction tax is:',
   'P30,000', 'P3,600', 'P3,000', 'P60,000',
   2, 'Stock transaction tax = P500,000 x 0.6% = P3,000.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'The destination principle underlying the VAT means that:',
   'Goods and services are taxed in the country where they are consumed, so exports are zero-rated and imports are taxed', 'VAT is imposed where the goods are produced', 'Only domestic sales are taxed', 'VAT follows the nationality of the seller',
   0, 'Under the destination principle, VAT is imposed where goods or services are destined to be consumed; thus exports are zero-rated and imports are subject to VAT.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'A VAT-registered seller sold goods for P1,120,000 VAT-inclusive and had input VAT of P40,000 for the period. The VAT payable is:',
   'P40,000', 'P120,000', 'P134,400', 'P80,000',
   3, 'Output VAT = P1,120,000 / 1.12 x 0.12 = P120,000. VAT payable = P120,000 - P40,000 input = P80,000.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'Operators of cockpits and cabarets are subject to which tax on their gross receipts?',
   'VAT at 12%', 'Excise tax', 'Amusement (percentage) tax at the rate fixed for the place of amusement', 'Stock transaction tax',
   2, 'Operators of cockpits, cabarets, night clubs, and similar places of amusement are subject to the amusement percentage tax on gross receipts at the rates fixed by the NIRC, not VAT.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'A VAT-registered enterprise made the following net-of-VAT sales: domestic P3,000,000 and direct export P2,000,000. Total input VAT was P300,000, all attributable to combined operations and validly allocable. The output VAT on these sales is:',
   'P600,000', 'P360,000', 'P240,000', 'P0',
   1, 'Output VAT = 12% on domestic sales only (exports are zero-rated): P3,000,000 x 12% = P360,000; the export sales generate 0% output VAT.', 3),
  ('TAX', 'VAT & Percentage Taxes',
   'Which of the following is a VAT-exempt transaction, where no output VAT is charged and the related input VAT becomes part of cost?',
   'Sale of agricultural food products in their original state', 'Direct export of goods', 'Sale of services to an ecozone enterprise', 'Sale of a commercial building by a real estate dealer',
   0, 'Sale of agricultural and marine food products in their original state is VAT-exempt; the seller charges no output VAT and any input VAT becomes part of cost, unlike zero-rated exports.', 2),
  ('TAX', 'VAT & Percentage Taxes',
   'A VAT-registered taxpayer ends the quarter with output VAT of P100,000 and input VAT of P130,000, none attributable to zero-rated sales. The excess input VAT of P30,000:',
   'May be carried over to the succeeding quarters', 'Is forfeited', 'Is refundable in cash immediately', 'Must be paid to the BIR',
   0, 'Excess input VAT not attributable to zero-rated sales is not refundable; it is carried over and applied against output VAT of the succeeding quarter(s).', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'Before the BIR may examine a taxpayer books for a regular audit, the examining revenue officer must be armed with a:',
   'Subpoena duces tecum', 'Warrant of distraint', 'Final Assessment Notice', 'Letter of Authority (LOA)',
   3, 'A valid Letter of Authority issued to the specific revenue officer is a prerequisite for a regular audit; an assessment from an examination without a valid LOA is void.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'In the assessment process, the document that informs the taxpayer of the BIR initial findings and to which the taxpayer may reply within 15 days is the:',
   'Final Assessment Notice', 'Preliminary Assessment Notice (PAN)', 'Warrant of garnishment', 'Collection letter',
   1, 'The Preliminary Assessment Notice (PAN) communicates the BIR initial findings; the taxpayer is given 15 days to reply before a Formal Assessment Notice/Formal Letter of Demand is issued.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'Upon receipt of a Formal Letter of Demand/Final Assessment Notice (FLD/FAN), the taxpayer must file a protest within:',
   '15 days', '180 days', '60 days', '30 days',
   3, 'A protest against the FLD/FAN must be filed within 30 days from receipt; failure to do so renders the assessment final, executory, and demandable.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'Where a protest takes the form of a request for REINVESTIGATION, the taxpayer must submit supporting documents within:',
   '15 days from filing the protest', '60 days from filing the protest', '30 days from filing the protest', '180 days from filing the protest',
   1, 'For a request for reinvestigation, the taxpayer has 60 days from the filing of the protest to submit all relevant supporting documents; this period does not apply to a request for reconsideration.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'After a valid protest and submission of documents, the BIR generally has how long to act before the taxpayer may treat the inaction as a denial?',
   '30 days', '180 days', '90 days', '60 days',
   1, 'The BIR has 180 days (from filing the protest or from submission of documents for reinvestigation) to act; inaction within that period may be appealed to the CTA.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'If the BIR fails to act on the protest within 180 days, the taxpayer may appeal to the Court of Tax Appeals within:',
   '30 days from the lapse of the 180 days', '15 days from the lapse of the 180 days', '60 days from the lapse of the 180 days', '2 years from the lapse of the 180 days',
   0, 'Upon the lapse of the 180-day period without BIR action, the taxpayer may appeal to the CTA within 30 days from the expiration of the 180-day period (or await the decision and appeal within 30 days of receipt).', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'The general prescriptive period for the BIR to assess internal revenue taxes, where a return was filed, is:',
   '3 years', '2 years', '5 years', '10 years',
   0, 'The general period to assess is 3 years counted from the later of the deadline for filing or the actual filing of the return.', 1),
  ('TAX', 'Tax Remedies & Local Taxation',
   'Where no return is filed or the return is false or fraudulent with intent to evade tax, the BIR may assess within:',
   '3 years', '10 years', '5 years', 'No prescription applies',
   1, 'In cases of failure to file a return or a false or fraudulent return with intent to evade tax, the assessment may be made within 10 years from the discovery of the omission or fraud.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'After an assessment has become final, the BIR period to collect the tax by distraint, levy, or court proceeding is:',
   '5 years', '3 years', '10 years', '2 years',
   0, 'Once an assessment is final, the BIR has 5 years from the date of the final assessment to collect the tax.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'A compromise on the ground of doubtful validity of the assessment requires a minimum payment of:',
   '10% of the basic tax assessed', '40% of the basic tax assessed', '50% of the basic tax assessed', '100% of the basic tax assessed',
   1, 'The minimum compromise rate for doubtful validity of an assessment is 40% of the basic assessed tax; financial incapacity carries a 10% minimum.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'The surcharge imposed for a willful or fraudulent failure to file or pay, including a prima facie case of substantial underdeclaration, is:',
   '10%', '100%', '25%', '50%',
   3, 'A 50% surcharge applies in cases of willful neglect or fraud; an underdeclaration of taxable sales/income exceeding 30% is prima facie evidence of fraud. The ordinary surcharge for simple late filing is 25%.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'A taxpayer paid a basic deficiency tax of P200,000 and is subject to the ordinary 25% surcharge (no fraud). The surcharge amount is:',
   'P20,000', 'P50,000', 'P100,000', 'P60,000',
   1, 'Surcharge = P200,000 x 25% = P50,000 for simple (non-fraudulent) late or deficient payment.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'Under the TRAIN Law, the deficiency and delinquency interest on unpaid tax is set at:',
   '6% per annum', '12% per annum (double the legal interest rate)', '20% per annum', '2% per month',
   1, 'TRAIN pegged the interest at double the legal interest rate set by the BSP; with a 6% legal rate, the tax interest is 12% per annum, and deficiency and delinquency interest may not be imposed simultaneously.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'A claim for refund or tax credit of an erroneously or illegally collected internal revenue tax must be filed with the BIR within:',
   '5 years from the date of payment', '6 months from payment', '30 days from payment', '2 years from the date of payment',
   3, 'A claim for refund of erroneously or illegally paid tax must be filed within 2 years from the date of payment; under EOPT the BIR has a 180-day period to act on the claim.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'A parcel of land has a fair market value of P2,000,000 and an assessment level of 20%. In a city, the basic real property tax (1%) plus the Special Education Fund (1%) totals:',
   'P4,000', 'P40,000', 'P20,000', 'P8,000',
   3, 'Assessed value = P2,000,000 x 20% = P400,000. Basic RPT = P400,000 x 1% = P4,000; SEF = P400,000 x 1% = P4,000; total = P8,000.', 3),
  ('TAX', 'Tax Remedies & Local Taxation',
   'A taxpayer who disputes a real property tax assessment must first pay the tax under protest and then appeal to the:',
   'Court of Tax Appeals within 30 days', 'Regional Trial Court within 15 days', 'Local Board of Assessment Appeals (LBAA) within 60 days', 'Bureau of Internal Revenue within 30 days',
   2, 'For real property tax, the taxpayer must pay under protest and may appeal the assessment to the Local Board of Assessment Appeals within 60 days from receipt of the assessment.', 2),
  ('TAX', 'Tax Remedies & Local Taxation',
   'A manufacturer has a principal office in City A and a factory in City B. For local business tax situs, the sales are allocated as:',
   '100% to the principal office', '100% to the factory', '50% to each', '30% to the principal office and 70% to the factory',
   3, 'Under the situs rules of the Local Government Code, 30% of sales recorded in the principal office is taxable by the city of the principal office and 70% by the city or municipality where the factory is located.', 3)
)
insert into public.questions (topic_id, stem, choices, correct_index, explanation, difficulty)
select t.id, q.stem, jsonb_build_array(q.a, q.b, q.c, q.d), q.correct_index, q.explanation, q.difficulty
from q join t on t.code = q.subject_code and lower(t.name) = lower(q.topic)
where not exists (select 1 from public.questions x where x.stem = q.stem);
