-- SAMPLE study materials: reviewer-style readings for three FAR topics, so the
-- Subjects → topic → read/watch journey works end-to-end. Replace/grow via
-- scripts/import-materials.mjs. Idempotent: skips rows whose title already exists.
-- Video rows are not seeded — add your own with real URLs (type 'video', video_url).

with t as (
  select tp.id, tp.name from public.topics tp
  join public.subjects s on s.id = tp.subject_id and s.code = 'FAR'
),
m(topic, title, body, duration, ord) as (values
  ('Conceptual Framework & FS Presentation',
   'Reviewer notes: The Conceptual Framework in 10 minutes',
   E'## What the Framework is for\n\nThe Conceptual Framework is not a standard. It guides the IASB in developing standards and helps preparers when no standard applies to a transaction. When a PFRS conflicts with the Framework, **the standard prevails**.\n\n## The objective of financial reporting\n\nTo provide financial information about the reporting entity that is **useful to existing and potential investors, lenders, and other creditors** in making decisions about providing resources to the entity.\n\n## Qualitative characteristics\n\n**Fundamental** (make information useful):\n\n- **Relevance** — capable of making a difference in decisions; has predictive value, confirmatory value, or both. Materiality is an entity-specific aspect of relevance.\n- **Faithful representation** — complete, neutral, and free from error. Neutrality is supported by **prudence** (caution under uncertainty).\n\n**Enhancing** (make useful information more useful): comparability, verifiability, timeliness, understandability. *Memory aid: C-V-T-U.*\n\nExam trap: candidates are routinely asked to classify a characteristic as fundamental vs enhancing. Only relevance and faithful representation are fundamental.\n\n## The elements\n\n- **Asset** — a present economic resource controlled by the entity as a result of past events; a right with the potential to produce economic benefits.\n- **Liability** — a present obligation to transfer an economic resource as a result of past events.\n- **Equity** — residual interest (assets minus liabilities).\n- **Income / Expenses** — changes in assets or liabilities that result in changes in equity, other than contributions from or distributions to owners.\n\n## Recognition and measurement\n\nRecognize an element when recognition provides **relevant** information and a **faithful representation** — both, not either. Measurement bases: historical cost and current value (fair value, value in use, fulfilment value, current cost).\n\n## Current vs non-current (PAS 1)\n\nA liability is current when the entity has **no right at the end of the reporting period** to defer settlement for at least 12 months. Refinancing completed *after* the reporting date does not save the classification.',
   10, 1),

  ('Cash & Cash Equivalents',
   'Reviewer notes: Cash, cash equivalents, and bank reconciliation',
   E'## What counts as cash\n\nCash includes cash on hand and demand deposits: bills and coins, checks received (not postdated), bank drafts, money orders, and unrestricted working funds (petty cash, payroll fund, change fund).\n\n**Not cash:** postdated checks received (still receivables), IOUs, unused postage, restricted compensating balances (classify per the related loan).\n\n## Cash equivalents — the 3-month rule\n\nShort-term, highly liquid investments **acquired three months or less before maturity**: treasury bills, money market placements, commercial paper. The test is the remaining term *at acquisition*, not the original term — a 1-year T-bill bought 2 months before maturity qualifies; the same bill bought at issuance never does. Equity securities have no maturity and are never cash equivalents (except redeemable preference shares acquired near redemption date).\n\n## Bank reconciliation — adjusted balance method\n\n```\nBook balance                Bank balance\n+ Credit memos              + Deposits in transit\n- Debit memos               - Outstanding checks\n± Book errors               ± Bank errors\n= Adjusted book balance  =  = Adjusted bank balance\n```\n\nOnly **book-side items** (credit memos, debit memos, book errors) require adjusting entries. Deposits in transit and outstanding checks are timing differences — no entry.\n\nExam traps:\n\n- A *certified* check is no longer outstanding — the bank already deducted it.\n- An NSF check returned is a debit memo: debit Accounts Receivable, credit Cash.\n- Stale checks (outstanding > 6 months) revert to cash: debit Cash, credit the liability or income.\n\n## Petty cash — imprest system\n\nExpenses are recognized only on **replenishment**. At reporting date, an unreplenished fund overstates cash and understates expenses — adjust. A shortage with no accountable employee goes to loss; an overage with no claimant goes to miscellaneous income.',
   12, 1),

  ('Receivables',
   'Reviewer notes: Receivables measurement, impairment, and derecognition',
   E'## Initial measurement\n\nUnder PFRS 9, receivables are initially measured at **fair value plus transaction costs** — except trade receivables without a significant financing component, which use the **transaction price** (PFRS 15 practical expedient).\n\nLong-term notes receivable bearing no or unrealistic interest are measured at **present value**; the discount is amortized to interest income using the effective interest method.\n\n## Subsequent measurement and impairment\n\nTrade receivables are carried at **amortized cost**: face less allowance for credit losses. PFRS 9 uses the **expected credit loss (ECL)** model — losses are recognized *before* default occurs. For trade receivables, the **simplified approach** (lifetime ECL, often via a provision matrix) is allowed.\n\nEstimating the allowance:\n\n- **Percentage of sales** — income-statement approach; the computed amount *is* the bad debt expense.\n- **Aging / percentage of receivables** — balance-sheet approach; the computed amount is the *required ending allowance*; expense is the squeeze.\n\nWrite-off: debit Allowance, credit AR — **no effect on expense or net realizable value**. Recovery: reinstate, then record the collection.\n\n## Derecognition: factoring, assignment, discounting\n\n- **Factoring without recourse** — risks and rewards transfer: treat as a **sale**; derecognize, recognize gain/loss.\n- **Factoring with recourse / pledging / assignment** — typically a **secured borrowing**; keep the receivable, recognize a liability.\n- **Notes discounting (with recourse)** — compute: maturity value = face + interest to maturity; discount = maturity value × discount rate × remaining term; proceeds = maturity value − discount. With recourse it is either a conditional sale (disclose contingent liability) or secured borrowing.\n\nExam trap: in discounting problems, the discount rate applies to **maturity value** (not face) over the **remaining** (not original) term.',
   12, 1)
)
insert into public.materials (topic_id, type, title, body, duration_minutes, sort_order)
select t.id, 'reading', m.title, m.body, m.duration, m.ord
from m join t on t.name = m.topic
where not exists (select 1 from public.materials x where x.title = m.title);
